// Gunakan window.vocabData array agar file JS lain bisa di-push juga nantinya
window.vocabData = window.vocabData || [];

const kosakata_m5h5 = [
  // --- GAMBAR 1 (Kata Kerja Kelompok 1 & 2) ---
  {
    id: 'm5h5_1',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '築く',
    furigana: 'きずく',
    arti: 'Membangun / Menciptakan',
    penjelasan: 'Digunakan untuk menyatakan aktivitas membangun sesuatu secara fisik yang membutuhkan usaha besar (seperti bendungan, tembok), maupun membangun sesuatu yang abstrak seperti hubungan, keluarga, atau posisi sosial.',
    contoh1: 'ダムを築く。\n(Membangun bendungan.)',
    contoh2: '二人の間に信頼関係を築く。\n(Membangun hubungan kepercayaan di antara mereka berdua.)'
  },
  {
    id: 'm5h5_2',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '描く',
    furigana: 'えがく',
    arti: 'Menggambarkan / Membayangkan',
    penjelasan: 'Bisa berarti melukis/menggambar secara harfiah dengan alat tulis, namun kata "えがく" sangat sering digunakan secara kiasan untuk membayangkan, melukiskan di dalam hati, atau memvisualisasikan masa depan/impian.',
    contoh1: '風景を心に描く。\n(Menggambarkan pemandangan di dalam pikiran/hati.)',
    contoh2: '将来の夢を描く。\n(Membayangkan impian masa depan.)'
  },
  {
    id: 'm5h5_3',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '背く',
    furigana: 'そむく',
    arti: 'Tidak patuh / Mengingkari / Membelot',
    penjelasan: 'Menunjukkan tindakan berbalik arah, menentang, atau melanggar sesuatu yang seharusnya diikuti. Sering dipasangkan dengan perintah, hukum, atau harapan seseorang.',
    contoh1: '命令に背く。\n(Tidak patuh pada perintah / Membangkang perintah.)',
    contoh2: '親の期待に背く。\n(Mengingkari harapan orang tua.)'
  },
  {
    id: 'm5h5_4',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '相次ぐ',
    furigana: 'あいつぐ',
    arti: 'Terjadi berturut-turut / Susul-menyusul',
    penjelasan: 'Digunakan ketika suatu kejadian (biasanya kejadian besar, kecelakaan, atau masalah) terjadi secara berurutan dalam waktu yang berdekatan tanpa henti.',
    contoh1: '事故が相次ぐ。\n(Kecelakaan terjadi berturut-turut.)',
    contoh2: '客からの苦情が相次いでいる。\n(Keluhan dari pelanggan datang silih berganti.)'
  },
  {
    id: 'm5h5_5',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '試みる',
    furigana: 'こころみる',
    arti: 'Mencoba / Melakukan percobaan',
    penjelasan: 'Bentuk formal dari "試す" (tamesu). Menunjukkan tindakan mencoba melakukan sesuatu (yang belum tentu berhasil) untuk melihat hasilnya. Bentuk kata bendanya adalah 試み (kokoromi: percobaan/upaya).',
    contoh1: '実験を試みる。\n(Mencoba melakukan sebuah eksperimen.)',
    contoh2: '新しい方法を試みる。\n(Mencoba sebuah metode baru.)'
  },
  {
    id: 'm5h5_6',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '省みる',
    furigana: 'かえりみる',
    arti: 'Merenungkan / Mengintrospeksi',
    penjelasan: 'Melihat kembali ke belakang (masa lalu atau tindakan sendiri) dengan tujuan introspeksi, penyesalan, atau evaluasi agar menjadi lebih baik.',
    contoh1: '過去を省みる。\n(Merenungkan masa lalu.)',
    contoh2: '自分の行動を深く省みる。\n(Mengintrospeksi tindakan diri sendiri secara mendalam.)'
  },
  {
    id: 'm5h5_7',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '帯びる',
    furigana: 'おびる',
    arti: 'Mengandung / Memiliki unsur / Membawa',
    penjelasan: 'Kata ini memiliki beberapa arti. Bisa berarti mengenakan/membawa sesuatu (seperti pedang), mengemban tugas, atau mengandung suatu sifat/karakteristik tertentu (seperti bau, warna, atau emosi).',
    contoh1: '酒気を帯びる。\n(Mengandung bau alkohol / Dalam pengaruh sedikit alkohol.)',
    contoh2: '怒りを帯びた声で話す。\n(Berbicara dengan suara yang mengandung kemarahan.)'
  },

  // --- GAMBAR 2 (Kata Kerja Kelompok 2 - Lanjutan) ---
  {
    id: 'm5h5_8',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '経る',
    furigana: 'へる',
    arti: 'Melewati / Melalui',
    penjelasan: 'Digunakan dalam dua konteks utama: melewati suatu periode waktu yang panjang, atau melewati suatu tempat (transit/melalui) dalam sebuah perjalanan.',
    contoh1: '十年の年月を経る。\n(Melewati waktu sepuluh tahun.)',
    contoh2: 'ドイツを経てイギリスへ行く。\n(Pergi ke Inggris melalui / transit di Jerman.)'
  },
  {
    id: 'm5h5_9',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '構える',
    furigana: 'かまえる',
    arti: 'Mendirikan / Mengambil posisi / Mempersiapkan',
    penjelasan: 'Berarti mendirikan suatu bangunan (seperti rumah atau toko) di suatu lokasi. Bisa juga berarti mengambil postur atau posisi siap sedia (misalnya bersiap memotret atau bersiap bertarung).',
    contoh1: '大通りに店を構える。\n(Mendirikan toko di jalan utama.)',
    contoh2: 'カメラを構える。\n(Mempersiapkan/mengambil posisi siap dengan kamera.)'
  },
  {
    id: 'm5h5_10',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '栄える',
    furigana: 'さかえる',
    arti: 'Makmur / Berjaya / Berkembang pesat',
    penjelasan: 'Menggambarkan keadaan di mana suatu negara, kota, perusahaan, atau kebudayaan sedang dalam masa puncaknya yang makmur, ramai, dan berjaya secara ekonomi atau budaya.',
    contoh1: '国が栄える。\n(Negara menjadi makmur/berjaya.)',
    contoh2: 'その町は商業で栄えている。\n(Kota tersebut makmur karena perdagangan.)'
  },
  {
    id: 'm5h5_11',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '絶える',
    furigana: 'たえる',
    arti: 'Terputus / Berhenti / Habis',
    penjelasan: 'Sesuatu yang tadinya berlangsung (seperti kontak, keturunan, pasokan, atau suara) kini terhenti atau tidak ada lagi.',
    contoh1: '連絡が絶える。\n(Kontak/komunikasi terputus.)',
    contoh2: '家系が絶える。\n(Garis keturunan keluarga terputus/berakhir.)'
  },
  {
    id: 'm5h5_12',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '映える',
    furigana: 'はえる',
    arti: 'Bersinar / Terlihat menonjol / Cocok',
    penjelasan: 'Kondisi di mana suatu objek terlihat sangat indah, menonjol, atau bersinar karena terkena cahaya (seperti sinar matahari), atau karena kontras dengan latar belakangnya.',
    contoh1: '夕日に映える。\n(Bersinar indah terkena sinar matahari terbenam.)',
    contoh2: '青い海に白い船が映える。\n(Kapal putih terlihat menonjol dan indah di latar laut biru.)'
  },
  {
    id: 'm5h5_13',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '整える',
    furigana: 'ととのえる',
    arti: 'Merapikan / Menyiapkan / Mengatur',
    penjelasan: 'Tindakan mengatur sesuatu yang berantakan menjadi rapi atau mempersiapkan sesuatu agar berada dalam kondisi siap pakai (seperti pakaian, pernapasan, atau bentuk).',
    contoh1: '服装を整える。\n(Merapikan pakaian/penampilan.)',
    contoh2: '深呼吸をして息を整える。\n(Menarik napas dalam untuk mengatur/menenangkan pernapasan.)'
  },
  {
    id: 'm5h5_14',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '授ける',
    furigana: 'さずける',
    arti: 'Menganugerahkan / Memberikan / Mengajarkan',
    penjelasan: 'Memberikan sesuatu yang berharga dari pihak yang posisinya lebih tinggi kepada pihak yang lebih rendah. Objeknya bisa berupa penghargaan bergengsi, gelar, atau ilmu/kebijaksanaan.',
    contoh1: '賞を授ける。\n(Menganugerahkan penghargaan/hadiah.)',
    contoh2: '弟子に秘伝の技を授ける。\n(Mewariskan/mengajarkan teknik rahasia kepada murid.)'
  },
  {
    id: 'm5h5_15',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '傾ける',
    furigana: 'かたむける',
    arti: 'Memiringkan / Mencurahkan',
    penjelasan: 'Bisa berarti memiringkan suatu benda secara fisik, atau mencurahkan perhatian, tenaga, dan gairah sepenuhnya ke suatu hal (misal: memiringkan telinga untuk fokus mendengarkan).',
    contoh1: '耳を傾ける。\n(Mendengarkan dengan saksama / Memberi perhatian.)',
    contoh2: '研究に情熱を傾ける。\n(Mencurahkan seluruh gairah/semangat pada penelitian.)'
  },
  {
    id: 'm5h5_16',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '設ける',
    furigana: 'もうける',
    arti: 'Menyediakan / Mendirikan / Menciptakan',
    penjelasan: 'Membangun, mempersiapkan, atau mengatur sesuatu untuk tujuan tertentu. Sering dipakai untuk pendirian divisi, loket, hukum, peraturan, atau penciptaan kesempatan dan waktu.',
    contoh1: '相談窓口を設ける。\n(Menyediakan/mendirikan loket konsultasi.)',
    contoh2: '話し合いの機会を設ける。\n(Menciptakan/menyediakan kesempatan untuk berdiskusi.)'
  },
  {
    id: 'm5h5_17',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '手掛ける',
    furigana: 'てがける',
    arti: 'Menangani / Mengerjakan (secara langsung)',
    penjelasan: 'Menunjukkan bahwa seseorang memegang kendali atau menangani langsung suatu pekerjaan, proyek, atau membesarkan/mengasuh seseorang dengan tangan sendiri.',
    contoh1: '設計を手掛ける。\n(Menangani/mengerjakan desain sendiri.)',
    contoh2: '新しい事業を手掛ける。\n(Menangani proyek bisnis baru.)'
  },
  {
    id: 'm5h5_18',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '定める',
    furigana: 'さだめる',
    arti: 'Menetapkan / Menentukan / Memutuskan',
    penjelasan: 'Membuat keputusan yang pasti terhadap sesuatu yang sebelumnya belum jelas, atau mengesahkan aturan baku seperti undang-undang, sasaran, atau tempat tinggal.',
    contoh1: '憲法を定める。\n(Menetapkan konstitusi/undang-undang.)',
    contoh2: '今後の目標を定める。\n(Menentukan target ke depan.)'
  },
  {
    id: 'm5h5_19',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '目覚める',
    furigana: 'めざめる',
    arti: 'Terbangun / Sadar (akan sesuatu)',
    penjelasan: 'Bisa berarti bangun dari tidur atau mimpi secara fisik. Dalam arti abstrak, ini bermakna mulai sadar atau menyadari ketertarikan, bakat, atau suatu kenyataan yang selama ini terpendam.',
    contoh1: '夢から目覚める。\n(Terbangun dari mimpi.)',
    contoh2: '芸術に目覚める。\n(Mulai sadar/memiliki ketertarikan pada seni.)'
  },
  {
    id: 'm5h5_20',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '暮れる',
    furigana: 'くれる',
    arti: 'Berakhir (hari/tahun) / Menjadi gelap',
    penjelasan: 'Menunjukkan berakhirnya suatu periode, paling sering digunakan untuk matahari yang terbenam (menandakan pergantian siang ke malam), atau akhir tahun. Ada idiom "途方に暮れる" (tohō ni kureru) yang artinya kebingungan/buntu.',
    contoh1: '日が暮れる。\n(Matahari terbenam / Hari mulai gelap.)',
    contoh2: 'どうしていいかわからず途方に暮れる。\n(Bingung/buntu karena tidak tahu apa yang harus dilakukan.)'
  },
  {
    id: 'm5h5_21',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '遅らせる',
    furigana: 'おくらせる',
    arti: 'Menunda / Mengundurkan (waktu)',
    penjelasan: 'Tindakan aktif untuk menunda jadwal, memundurkan waktu, atau membuat pergerakan/progress sesuatu menjadi lebih lambat dari yang direncanakan.',
    contoh1: '出発を遅らせる。\n(Menunda keberangkatan.)',
    contoh2: '時計の針を5分遅らせる。\n(Memundurkan jarum jam sebanyak 5 menit.)'
  },
  {
    id: 'm5h5_22',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '寝かせる',
    furigana: 'ねかせる',
    arti: 'Menidurkan / Membaringkan / Mengistirahatkan',
    penjelasan: 'Tindakan membuat orang lain (biasanya anak/bayi) tidur atau membaringkan tubuh pasien. Dalam konteks kuliner, berarti mendiamkan/mengistirahatkan bahan (seperti adonan daging atau kue) agar bumbu meresap.',
    contoh1: '子どもを寝かせる。\n(Menidurkan anak.)',
    contoh2: 'パンの生地を寝かせる。\n(Mendiamkan/mengistirahatkan adonan roti.)'
  },
  {
    id: 'm5h5_23',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '震わせる',
    furigana: 'ふるわせる',
    arti: 'Menggetarkan / Membuat gemetar',
    penjelasan: 'Tindakan fisik atau akibat emosi (takut, marah, terharu) yang menyebabkan suara atau bagian tubuh bergetar hebat.',
    contoh1: '声を震わせる。\n(Membuat suara gemetar / Suara bergetar karena emosi.)',
    contoh2: '怒りで体を震わせる。\n(Membuat tubuh gemetar karena amarah.)'
  },

  // --- GAMBAR 3 (Kata Kerja Kelompok 3: ~suru dan ~jiru) ---
  {
    id: 'm5h5_24',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '値する',
    furigana: 'あたいする',
    arti: 'Bernilai / Layak / Pantas',
    penjelasan: 'Menunjukkan bahwa suatu tindakan, karya, atau perilaku memiliki kualitas yang pantas/layak untuk mendapatkan suatu perlakuan (misal: layak dibaca, layak dipuji, pantas dihukum).',
    contoh1: 'この本は一読に値する。\n(Buku ini bernilai / layak untuk dibaca sekali.)',
    contoh2: '彼の勇気ある行動は称賛に値する。\n(Tindakan beraninya layak mendapatkan pujian.)'
  },
  {
    id: 'm5h5_25',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '害する',
    furigana: 'がいする',
    arti: 'Merusak / Membahayakan / Menyakiti',
    penjelasan: 'Tindakan yang menimbulkan dampak negatif, merusak kesehatan, membahayakan keselamatan, atau menyinggung perasaan/kehormatan seseorang.',
    contoh1: '健康を害する。\n(Merusak kesehatan.)',
    contoh2: '人の気分を害する。\n(Merusak/menyinggung suasana hati orang lain.)'
  },
  {
    id: 'm5h5_26',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '称する',
    furigana: 'しょうする',
    arti: 'Mengaku / Menamakan diri / Berdalih',
    penjelasan: 'Memperkenalkan atau menamai diri sebagai seseorang (seringkali dengan nuansa pretensius atau mengaku-ngaku), atau beralasan palsu untuk menghindari sesuatu.',
    contoh1: '弁護士と称する男。\n(Pria yang mengaku-ngaku sebagai pengacara.)',
    contoh2: '病気だと称して欠席する。\n(Berdalih/beralasan sakit untuk absen.)'
  },
  {
    id: 'm5h5_27',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '制する',
    furigana: 'せいする',
    arti: 'Mengendalikan / Menguasai / Menahan',
    penjelasan: 'Menekan, menahan, atau mengatur sesuatu yang bergejolak (seperti massa, emosi, atau kondisi). Bisa juga dipakai dalam konteks olahraga (memenangkan kejuaraan).',
    contoh1: '警官が群集を制する。\n(Polisi mengendalikan kerumunan massa.)',
    contoh2: '怒りの感情を制する。\n(Menahan/mengendalikan emosi amarah.)'
  },
  {
    id: 'm5h5_28',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '脱する',
    furigana: 'だっする',
    arti: 'Melepaskan diri / Keluar dari (kondisi buruk)',
    penjelasan: 'Berhasil keluar atau melarikan diri dari keadaan darurat, bahaya, status rendah, atau krisis yang menekan.',
    contoh1: '危険を脱する。\n(Melepaskan diri / lolos dari bahaya.)',
    contoh2: 'ようやく経済的な危機を脱した。\n(Akhirnya berhasil keluar dari krisis ekonomi.)'
  },
  {
    id: 'm5h5_29',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '徹する',
    furigana: 'てっする',
    arti: 'Berdedikasi penuh / Bertahan pada suatu sikap',
    penjelasan: 'Mengabdikan diri secara total pada satu peran tertentu tanpa terpengaruh hal lain (misal: sepenuhnya menjadi pendengar yang baik atau pekerja di balik layar).',
    contoh1: '裏方に徹する。\n(Sepenuhnya mengabdikan diri bekerja di balik layar.)',
    contoh2: '今日は聞き手に徹する。\n(Hari ini akan berdedikasi sepenuhnya hanya sebagai pendengar.)'
  },
  {
    id: 'm5h5_30',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '面する',
    furigana: 'めんする',
    arti: 'Menghadap ke (arah/lokasi)',
    penjelasan: 'Mendeskripsikan posisi fisik sebuah bangunan, tanah, atau kamar yang berhadapan langsung dengan jalan, laut, gunung, dan sebagainya.',
    contoh1: '大通りに面する家。\n(Rumah yang menghadap ke jalan utama.)',
    contoh2: '海に面した部屋に泊まる。\n(Menginap di kamar yang menghadap ke laut.)'
  },
  {
    id: 'm5h5_31',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '要する',
    furigana: 'ようする',
    arti: 'Memerlukan / Membutuhkan',
    penjelasan: 'Menyatakan bahwa suatu keadaan, pekerjaan, atau tujuan mutlak membutuhkan waktu, tenaga, biaya, atau tingkat kehati-hatian tertentu.',
    contoh1: '急を要する連絡。\n(Pesan/komunikasi yang memerlukan tindakan segera atau mendesak.)',
    contoh2: '解決に長い時間を要する。\n(Membutuhkan waktu lama untuk diselesaikan.)'
  },
  {
    id: 'm5h5_32',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '案じる',
    furigana: 'あんじる',
    arti: 'Mengkhawatirkan / Memikirkan secara mendalam',
    penjelasan: 'Menunjukkan rasa khawatir atau cemas terhadap kondisi seseorang (keluarga/teman) atau situasi masa depan. Nuansanya lebih peduli dan memikirkan jalan keluar.',
    contoh1: '両親の健康を案じる。\n(Mengkhawatirkan kesehatan kedua orang tua.)',
    contoh2: '将来を案じて眠れない。\n(Tidak bisa tidur karena mengkhawatirkan masa depan.)'
  },
  {
    id: 'm5h5_33',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '重んじる',
    furigana: 'おもんじる',
    arti: 'Menghargai / Mementingkan',
    penjelasan: 'Memberikan bobot, nilai, atau prioritas yang tinggi terhadap suatu nilai, kebudayaan, tradisi, atau kualitas seseorang.',
    contoh1: '学歴を重んじる。\n(Mementingkan/memperhatikan betul riwayat pendidikan.)',
    contoh2: '古い伝統を重んじる。\n(Sangat menghargai tradisi lama.)'
  },
  {
    id: 'm5h5_34',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '演じる',
    furigana: 'えんじる',
    arti: 'Memerankan / Memainkan peran',
    penjelasan: 'Digunakan dalam dunia hiburan/seni untuk aksi memainkan karakter di dalam drama, film, atau teater. Bisa juga kiasan untuk bertindak sebagai peran tertentu dalam kehidupan nyata.',
    contoh1: 'ドラマのヒロインを演じる。\n(Memerankan tokoh utama wanita di sebuah drama.)',
    contoh2: '彼は被害者を演じている。\n(Dia sedang bermain peran seolah-olah menjadi korban.)'
  },
  {
    id: 'm5h5_35',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '興じる',
    furigana: 'きょうじる',
    arti: 'Bersenang-senang / Asyik menikmati',
    penjelasan: 'Terhanyut dalam kesenangan, permainan, atau perbincangan. Menunjukkan antusiasme tinggi saat melakukan suatu kegiatan hiburan.',
    contoh1: 'トランプに興じる。\n(Bersenang-senang/asyik bermain kartu.)',
    contoh2: '昔話に興じる。\n(Asyik terhanyut berbincang tentang masa lalu.)'
  },
  {
    id: 'm5h5_36',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '禁じる',
    furigana: 'きんじる',
    arti: 'Melarang / Tidak memperbolehkan',
    penjelasan: 'Tindakan tidak memperbolehkan sesuatu secara tegas, biasanya berdasarkan aturan formal, hukum, agama, atau otoritas.',
    contoh1: '法律で禁じられている。\n(Dilarang oleh hukum.)',
    contoh2: '未成年の飲酒は禁じられている。\n(Konsumsi alkohol oleh anak di bawah umur dilarang.)'
  },
  {
    id: 'm5h5_37',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '準じる',
    furigana: 'じゅんじる',
    arti: 'Menyesuaikan dengan / Mengacu pada',
    penjelasan: 'Mendasarkan standar, perlakuan, atau kompensasi berdasarkan aturan atau patokan tertentu yang sudah ada.',
    contoh1: '待遇は年齢に準じる。\n(Kompensasi/gaji disesuaikan mengacu pada usia.)',
    contoh2: '会社の規則に準じて処理する。\n(Memproses sesuatu menyesuaikan/berdasarkan peraturan perusahaan.)'
  },
  {
    id: 'm5h5_38',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '転じる',
    furigana: 'てんじる',
    arti: 'Berubah / Beralih (arah/status)',
    penjelasan: 'Perubahan arah, situasi, atau subjek pembicaraan dari satu kondisi ke kondisi lain yang biasanya berbeda (seperti keadaan yang membaik atau memburuk).',
    contoh1: '状況が好転に転じる。\n(Situasi berubah ke arah yang lebih baik.)',
    contoh2: '話題を転じる。\n(Mengalihkan topik pembicaraan.)'
  },
  {
    id: 'm5h5_39',
    minggu: '5',
    hari: '5',
    kategori: 'kata kerja',
    kanji: '報じる',
    furigana: 'ほうじる',
    arti: 'Melaporkan / Memberitakan',
    penjelasan: 'Tindakan menyampaikan berita, informasi, atau insiden ke publik oleh media massa seperti televisi, radio, atau surat kabar.',
    contoh1: '新聞が事件を報じる。\n(Surat kabar memberitakan insiden/kejadian tersebut.)',
    contoh2: 'ニュースで速報を報じる。\n(Melaporkan berita sela/breaking news di TV.)'
  }
];

window.vocabData.push(...kosakata_m5h5);