// Gunakan window.vocabData array agar file JS lain bisa di-push juga nantinya
window.vocabData = window.vocabData || [];

const kosakata_m5h3 = [
  // --- GAMBAR 1 (仕, 差) ---
  {
    id: 'm5h3_1',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '仕上げる',
    furigana: 'しあげる',
    arti: 'Menyelesaikan / Merampungkan',
    penjelasan: 'Menyelesaikan suatu tugas, karya, atau pekerjaan sampai benar-benar tuntas dan siap diserahkan.',
    contoh1: '作品を仕上げる。\n(Menyelesaikan sebuah karya seni.)',
    contoh2: 'レポートを明日までに仕上げる。\n(Menyelesaikan laporan paling lambat besok.)'
  },
  {
    id: 'm5h3_2',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '仕入れる',
    furigana: 'しいれる',
    arti: 'Membeli stok / Kulakan',
    penjelasan: 'Membeli barang dagangan atau bahan baku dari pemasok untuk dijual kembali atau dipakai usaha.',
    contoh1: '商品を仕入れる。\n(Membeli stok barang untuk dijual.)',
    contoh2: '新鮮な魚を市場で仕入れる。\n(Membeli stok ikan segar di pasar.)'
  },
  {
    id: 'm5h3_3',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '仕切る',
    furigana: 'しきる',
    arti: 'Membatasi / Memimpin (mengatur)',
    penjelasan: 'Mempunyai 2 arti: (1) Membagi ruangan dengan pembatas/sekat, (2) Memimpin dan memegang kendali suatu acara/kelompok.',
    contoh1: '部屋を仕切る。\n(Membagi ruangan dengan sekat.)',
    contoh2: '宴会を仕切る。\n(Memimpin dan mengatur jalannya pesta.)'
  },
  {
    id: 'm5h3_4',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '仕組み',
    furigana: 'しくみ',
    arti: 'Struktur / Mekanisme / Cara kerja',
    penjelasan: 'Sistem atau susunan tentang bagaimana suatu benda, mesin, atau organisasi bekerja.',
    contoh1: '世の中の仕組み。\n(Cara kerja sistem kehidupan masyarakat/dunia.)',
    contoh2: '機械の仕組みを理解する。\n(Memahami mekanisme/cara kerja mesin.)'
  },
  {
    id: 'm5h3_5',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '仕える',
    furigana: 'つかえる',
    arti: 'Mengabdi / Melayani',
    penjelasan: 'Bekerja dengan setia untuk melayani atasan, raja, majikan, atau Tuhan.',
    contoh1: '神に仕える。\n(Mengabdi kepada Tuhan.)',
    contoh2: '主君に仕える。\n(Setia melayani majikan/tuan.)'
  },
  {
    id: 'm5h3_6',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '日差し',
    furigana: 'ひざし',
    arti: 'Sinar matahari',
    penjelasan: 'Sorotan atau pancaran cahaya matahari yang terasa di kulit/bumi.',
    contoh1: '日差しが強い。\n(Sinar matahari sangat terik.)',
    contoh2: '春の暖かい日差し。\n(Sinar matahari musim semi yang hangat.)'
  },
  {
    id: 'm5h3_7',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '時差',
    furigana: 'じさ',
    arti: 'Perbedaan waktu',
    penjelasan: 'Selisih waktu antarwilayah atau negara. Sering dipakai pada istilah 時差ぼけ (jetlag).',
    contoh1: '時差がある。\n(Ada perbedaan waktu.)',
    contoh2: '時差ぼけで眠れない。\n(Tidak bisa tidur karena jetlag.)'
  },
  {
    id: 'm5h3_8',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '点差',
    furigana: 'てんさ',
    arti: 'Selisih poin / Perbedaan skor',
    penjelasan: 'Beda nilai atau jumlah skor antara dua tim/pihak yang bertanding.',
    contoh1: '点差が開く。\n(Selisih skor makin melebar.)',
    contoh2: '５点差で負けた。\n(Kalah dengan selisih 5 poin.)'
  },
  {
    id: 'm5h3_9',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '指差す',
    furigana: 'ゆびさす',
    arti: 'Menunjuk dengan jari',
    penjelasan: 'Mengarahkan jari telunjuk ke objek, tempat, atau seseorang.',
    contoh1: '家のほうを指差す。\n(Menunjuk ke arah rumah.)',
    contoh2: '人を指差すのは失礼だ。\n(Menunjuk orang dengan jari itu tidak sopan.)'
  },

  // --- GAMBAR 2 (利, 有, 現, 柄, 訳, 説) ---
  {
    id: 'm5h3_10',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '利子 / 利息',
    furigana: 'りし / りそく',
    arti: 'Bunga bank / Uang sewa tabungan/pinjaman',
    penjelasan: 'Uang tambahan yang dibayarkan saat meminjam uang, atau imbalan yang didapat dari menabung di bank.',
    contoh1: '銀行の利子。\n(Bunga bank.)',
    contoh2: 'お金を借りて利息を払う。\n(Meminjam uang dan membayar bunganya.)'
  },
  {
    id: 'm5h3_11',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '利点',
    furigana: 'りてん',
    arti: 'Kelebihan / Keuntungan',
    penjelasan: 'Nilai tambah atau segi positif dari suatu hal dibandingkan pilihan lainnya.',
    contoh1: 'A案には多くの利点がある。\n(Rencana A punya banyak kelebihan.)',
    contoh2: 'このシステムを使う利点は何ですか。\n(Apa keuntungan memakai sistem ini?)'
  },
  {
    id: 'm5h3_12',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '砂利',
    furigana: 'じゃり',
    arti: 'Batu kerikil',
    penjelasan: 'Batu-batu kecil yang biasa dipakai untuk jalanan, rel kereta, atau halaman rumah.',
    contoh1: '砂利道。\n(Jalan berbatu kerikil.)',
    contoh2: '庭に砂利を敷く。\n(Menabur batu kerikil di halaman.)'
  },
  {
    id: 'm5h3_13',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '左利き',
    furigana: 'ひだりきき',
    arti: 'Kidal',
    penjelasan: 'Orang yang lebih dominan menggunakan tangan kiri. Kebalikannya adalah 右利き (migikiki / tangan kanan).',
    contoh1: '左利きの人。\n(Orang kidal.)',
    contoh2: '左利き用のハサミ。\n(Gunting khusus orang kidal.)'
  },
  {
    id: 'm5h3_14',
    minggu: '5',
    hari: '3',
    kategori: 'kata sifat',
    kanji: '有望（な）',
    furigana: 'ゆうぼう',
    arti: 'Berpotensi / Masa depan cerah',
    penjelasan: 'Sifat untuk seseorang atau hal yang punya prospek hebat dan berpeluang sukses besar di masa depan.',
    contoh1: '有望な研究者。\n(Peneliti yang sangat berpotensi.)',
    contoh2: '将来有望な若者。\n(Pemuda yang masa depannya cerah.)'
  },
  {
    id: 'm5h3_15',
    minggu: '5',
    hari: '3',
    kategori: 'kata sifat',
    kanji: '有益（な）',
    furigana: 'ゆうえき',
    arti: 'Bermanfaat / Berfaedah',
    penjelasan: 'Segala hal yang memberikan nilai guna atau kegunaan positif. Lawan katanya adalah 無益 (mueki / sia-sia).',
    contoh1: '有益な本。\n(Buku yang sangat bermanfaat.)',
    contoh2: '休暇を有益に使う。\n(Memanfaatkan waktu liburan dengan baik.)'
  },
  {
    id: 'm5h3_16',
    minggu: '5',
    hari: '3',
    kategori: 'kata sifat',
    kanji: '有力（な）',
    furigana: 'ゆうりょく',
    arti: 'Berpengaruh / Berpeluang kuat',
    penjelasan: 'Memiliki pengaruh/kekuatan besar, atau menjadi kandidat terkuat untuk memenangkan sesuatu.',
    contoh1: '地域の有力者。\n(Tokoh yang sangat berpengaruh di daerah tersebut.)',
    contoh2: '優勝の有力な候補。\n(Kandidat terkuat calon juara.)'
  },
  {
    id: 'm5h3_17',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '私有',
    furigana: 'しゆう',
    arti: 'Milik pribadi / Privat',
    penjelasan: 'Kepemilikan perorangan/swasta, bukan untuk umum/publik.',
    contoh1: '私有財産。\n(Harta kekayaan milik pribadi.)',
    contoh2: 'ここは私有地です。\n(Ini adalah tanah milik pribadi.)'
  },
  {
    id: 'm5h3_18',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '有する',
    furigana: 'ゆうする',
    arti: 'Memiliki / Mempunyai',
    penjelasan: 'Bentuk formal dari "mempunyai" (hak, kemampuan, atau kualifikasi).',
    contoh1: '権利を有する。\n(Memiliki hak.)',
    contoh2: '特別な能力を有する。\n(Memiliki kemampuan khusus.)'
  },
  {
    id: 'm5h3_19',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '現行',
    furigana: 'げんこう',
    arti: 'Sedang berlaku / Saat ini',
    penjelasan: 'Aturan, sistem, atau undang-undang yang sedang dipakai/berjalan saat ini. 現行犯 (tertangkap basah).',
    contoh1: '現行犯で逮捕される。\n(Ditangkap karena tertangkap basah di lokasi.)',
    contoh2: '現行の制度。\n(Sistem yang sedang berlaku saat ini.)'
  },
  {
    id: 'm5h3_20',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '現場',
    furigana: 'げんば',
    arti: 'TKP / Lokasi kerja lapangan',
    penjelasan: 'Tempat terjadinya suatu peristiwa (kecelakaan/kejahatan) atau tempat proyek dikerjakan.',
    contoh1: '工事現場。\n(Lokasi proyek konstruksi.)',
    contoh2: '事故の現場。\n(Tempat kejadian perkara/kecelakaan.)'
  },
  {
    id: 'm5h3_21',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '現地',
    furigana: 'げんち',
    arti: 'Lokasi tujuan / Setempat',
    penjelasan: 'Tempat asli di mana suatu aktivitas atau peristiwa berlangsung (biasanya lokasi yang dituju).',
    contoh1: '現地に向かう。\n(Menuju ke lokasi tujuan.)',
    contoh2: '現地の習慣を学ぶ。\n(Mempelajari kebiasaan warga setempat.)'
  },
  {
    id: 'm5h3_22',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '出現（する）',
    furigana: 'しゅつげん',
    arti: 'Muncul / Menampakkan diri',
    penjelasan: 'Keadaan di mana sesuatu yang sebelumnya tidak kelihatan tiba-tiba muncul.',
    contoh1: 'UFOが出現する。\n(UFO muncul/menampakkan diri.)',
    contoh2: '新たなウイルスが出現した。\n(Virus baru telah muncul.)'
  },
  {
    id: 'm5h3_23',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '再現（する）',
    furigana: 'さいげん',
    arti: 'Merekonstruksi / Membuat ulang',
    penjelasan: 'Menampilkan atau membuat ulang suatu kejadian/kondisi agar sama seperti aslinya.',
    contoh1: '事故の状況を再現する。\n(Merekonstruksi ulang kronologi kecelakaan.)',
    contoh2: '当時の街並みを再現したテーマパーク。\n(Taman hiburan yang merekonstruksi tata kota zaman dulu.)'
  },
  {
    id: 'm5h3_24',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '間柄',
    furigana: 'あいだがら',
    arti: 'Hubungan / Kedekatan',
    penjelasan: 'Status atau tingkat kedekatan hubungan antarmanusia (keluarga, teman, pasangan).',
    contoh1: '親密な間柄。\n(Hubungan yang sangat akrab/dekat.)',
    contoh2: '彼とは兄弟のような間柄だ。\n(Hubungan saya dengannya sudah seperti saudara.)'
  },
  {
    id: 'm5h3_25',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '事柄',
    furigana: 'ことがら',
    arti: 'Hal / Perkara / Masalah',
    penjelasan: 'Istilah formal untuk menyebut topik, fakta, atau hal yang sedang dibahas.',
    contoh1: '重要な事柄。\n(Hal/perkara yang penting.)',
    contoh2: '次の事柄について説明します。\n(Saya akan menjelaskan tentang hal-hal berikut.)'
  },
  {
    id: 'm5h3_26',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '人柄',
    furigana: 'ひとがら',
    arti: 'Kepribadian / Sifat',
    penjelasan: 'Karakter atau sifat dasar seseorang yang terlihat dari perilakunya sehari-hari.',
    contoh1: '立派な人柄。\n(Kepribadian yang terpuji/luar biasa.)',
    contoh2: '彼の温かい人柄に惹かれる。\n(Tertarik dengan sifatnya yang hangat.)'
  },
  {
    id: 'm5h3_27',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '直訳（する）',
    furigana: 'ちょくやく',
    arti: 'Terjemahan harfiah / Mentah',
    penjelasan: 'Menerjemahkan teks kata demi kata secara langsung tanpa menyesuaikan konteksnya.',
    contoh1: '文章を直訳する。\n(Menerjemahkan kalimat secara harfiah.)',
    contoh2: '直訳すると意味が通じない。\n(Jika diterjemahkan secara harfiah, maknanya jadi aneh.)'
  },
  {
    id: 'm5h3_28',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '内訳',
    furigana: 'うちわけ',
    arti: 'Rincian / Pemecahan biaya',
    penjelasan: 'Detail pembagian angka atau biaya total ke dalam pos-pos yang lebih spesifik.',
    contoh1: '請求書の内訳。\n(Rincian komponen biaya dalam tagihan.)',
    contoh2: '出費の内訳をチェックする。\n(Mengecek rincian pengeluaran.)'
  },
  {
    id: 'm5h3_29',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '言い訳（する）',
    furigana: 'いいわけ',
    arti: 'Mencari alasan / Ngeles',
    penjelasan: 'Membuat alasan untuk membela diri atau menutupi kesalahan.',
    contoh1: '遅刻の言い訳をする。\n(Mencari alasan atas keterlambatan.)',
    contoh2: '言い訳は聞きたくない。\n(Saya tidak mau mendengar alasanmu.)'
  },
  {
    id: 'm5h3_30',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '説得（する）',
    furigana: 'せっとく',
    arti: 'Membujuk / Meyakinkan',
    penjelasan: 'Memberikan penjelasan logis agar orang lain mau setuju atau menuruti keinginan kita.',
    contoh1: '親を説得する。\n(Membujuk/meyakinkan orang tua.)',
    contoh2: '彼を説得してプロジェクトに参加させた。\n(Membujuknya agar mau ikut dalam proyek.)'
  },
  {
    id: 'm5h3_31',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '伝説',
    furigana: 'でんせつ',
    arti: 'Legenda',
    penjelasan: 'Cerita rakyat kuno, atau julukan untuk sosok luar biasa yang sangat terkenal.',
    contoh1: '伝説上の人物。\n(Tokoh dalam legenda.)',
    contoh2: 'この村には古い伝説がある。\n(Desa ini memiliki legenda kuno.)'
  },
  {
    id: 'm5h3_32',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '説く',
    furigana: 'とく',
    arti: 'Menjelaskan / Mengajarkan',
    penjelasan: 'Menerangkan ajaran, filosofi, atau kebenaran kepada orang lain.',
    contoh1: '教えを説く。\n(Mengajarkan suatu doktrin/ajaran.)',
    contoh2: '仏教の教えを説く。\n(Menjelaskan ajaran agama Buddha.)'
  }
];

window.vocabData.push(...kosakata_m5h3);