// Gunakan window.vocabData array agar file JS lain bisa di-push juga nantinya
window.vocabData = window.vocabData || [];

const kosakata_m5h3 = [
  // --- GAMBAR 1 (仕, 差) ---
  {
    id: 'm5h3_1',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '仕上げる',
    furigana: 'しあげる',
    arti: 'Menyiapkan / Menyelesaikan',
    penjelasan: 'Kata kerja ini digunakan apabila seseorang melengkapkan atau menyempurnakan sesuatu karya, tugas, laporan, atau produk sehingga mencapai tahap akhir yang berkualiti dan memuaskan.',
    contoh1: '作品を仕上げる。\n(Menyiapkan/menyempurnakan sebuah karya seni.)',
    contoh2: 'レポートを明日までに仕上げる。\n(Menyiapkan laporan menjelang hari esok.)'
  },
  {
    id: 'm5h3_2',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '仕入れる',
    furigana: 'しいれる',
    arti: 'Membeli stok / Memasukkan barang',
    penjelasan: 'Banyak digunakan dalam konteks perniagaan di mana seseorang pengusaha atau pekedai membeli barang niaga, bahan mentah, atau maklumat dari pembekal untuk tujuan jualan semula atau operasi perniagaan.',
    contoh1: '商品を仕入れる。\n(Membeli stok barangan untuk dijual.)',
    contoh2: '新鮮な魚を市場で仕入れる。\n(Membeli ikan segar di pasar sebagai stok restoran.)'
  },
  {
    id: 'm5h3_3',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '仕切る',
    furigana: 'しきる',
    arti: 'Membahagikan / Mengendalikan',
    penjelasan: 'Mempunyai dua maksud utama yang berbeza: Pertama, membahagikan sesuatu ruang atau bilik secara fizikal menggunakan penghadang. Kedua, mengambil alih peranan utama untuk mengurus, memimpin, atau mengendalikan perjalanan sesuatu majlis atau kumpulan.',
    contoh1: '部屋を仕切る。\n(Membahagikan bilik dengan penghadang.)',
    contoh2: '宴会を仕切る。\n(Menjadi ketua yang menguruskan dan mengendalikan majlis jamuan.)'
  },
  {
    id: 'm5h3_4',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '仕組み',
    furigana: 'しくみ',
    arti: 'Struktur / Mekanisme',
    penjelasan: 'Merujuk kepada tatacara, susunan, atau sistem bagaimana sesuatu benda atau proses itu berfungsi. Ia boleh merujuk kepada sistem kemasyarakatan, mekanisme dalam mesin, atau operasi sesebuah organisasi.',
    contoh1: '世の中の仕組み。\n(Struktur, sistem, atau realiti bagaimana dunia/masyarakat berfungsi.)',
    contoh2: '機械の仕組みを理解する。\n(Memahami mekanisme dan cara kerja mesin tersebut.)'
  },
  {
    id: 'm5h3_5',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '仕える',
    furigana: 'つかえる',
    arti: 'Berkhidmat / Mengabdi',
    penjelasan: 'Merujuk kepada perbuatan melayani, berkhidmat, atau bekerja dengan penuh kesetiaan di bawah seseorang yang mempunyai kedudukan lebih tinggi dan dihormati, seperti Tuhan, raja, atau tuan.',
    contoh1: '神に仕える。\n(Berkhidmat atau mengabdi kepada Tuhan.)',
    contoh2: '主君に仕える。\n(Berbakti dan berkhidmat untuk tuan/majikan.)'
  },
  {
    id: 'm5h3_6',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '日差し',
    furigana: 'ひざし',
    arti: 'Sinaran matahari / Cahaya matahari',
    penjelasan: 'Merujuk kepada pancaran atau kekuatan cahaya yang jatuh dari matahari ke bumi. Ia sering digunakan untuk menggambarkan betapa kuat, terik, atau hangatnya cuaca pada hari tersebut.',
    contoh1: '日差しが強い。\n(Sinaran matahari sangat terik dan kuat.)',
    contoh2: '春の暖かい日差し。\n(Cahaya matahari musim bunga yang suam dan menyegarkan.)'
  },
  {
    id: 'm5h3_7',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '時差',
    furigana: 'じさ',
    arti: 'Perbezaan masa / Zon masa',
    penjelasan: 'Perbezaan waktu tempatan antara dua buah negara atau lokasi geografi yang berlainan di dunia. Perkataan ini juga asas kepada istilah \'時差ぼけ\' (jetlag) iaitu masalah jam biologi badan akibat penerbangan merentas zon masa.',
    contoh1: '時差がある。\n(Terdapat perbezaan waktu antara tempat tersebut.)',
    contoh2: '時差ぼけで眠れない。\n(Tidak boleh tidur akibat kelesuan jetlag.)'
  },
  {
    id: 'm5h3_8',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '点差',
    furigana: 'てんさ',
    arti: 'Jurang mata / Perbezaan skor',
    penjelasan: 'Jumlah jurang mata, markah, atau skor yang membezakan antara dua pasukan atau pihak yang sedang bertanding di dalam sesuatu perlawanan sukan, mahupun dalam keputusan peperiksaan.',
    contoh1: '点差が開く。\n(Jurang perbezaan skor semakin jauh/melebar.)',
    contoh2: '５点差で負けた。\n(Kalah dengan perbezaan 5 mata.)'
  },
  {
    id: 'm5h3_9',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '指差す',
    furigana: 'ゆびさす',
    arti: 'Menunjuk (dengan jari)',
    penjelasan: 'Tindakan fizikal mengangkat tangan dan menggunakan jari (biasanya jari telunjuk) untuk menunjuk ke arah sesuatu objek, destinasi, atau kepada seseorang.',
    contoh1: '家のほうを指差す。\n(Menunjuk ke arah rumah dengan menggunakan jari.)',
    contoh2: '人を指差すのは失礼だ。\n(Perbuatan menunjuk jari ke arah orang adalah biadab.)'
  },

  // --- GAMBAR 2 (利, 有, 現, 柄, 訳, 説) ---
  {
    id: 'm5h3_10',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '利子 / 利息',
    furigana: 'りし / りそく',
    arti: 'Faedah / Bunga (Kewangan)',
    penjelasan: 'Merujuk kepada sejumlah wang tambahan atau peratusan yang dikenakan ke atas pinjaman wang, atau keuntungan wang yang diterima hasil daripada simpanan di dalam bank (interest).',
    contoh1: '銀行の利子。\n(Kadar faedah / bunga yang diberikan oleh bank.)',
    contoh2: 'お金を借りて利息を払う。\n(Meminjam wang dan perlu membayar kadar faedahnya.)'
  },
  {
    id: 'm5h3_11',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '利点',
    furigana: 'りてん',
    arti: 'Kelebihan / Manfaat',
    penjelasan: 'Merujuk kepada ciri-ciri positif, nilai tambah, kebaikan, atau kekuatan yang terdapat pada sesuatu rancangan, keadaan, atau produk berbanding pilihan yang lain.',
    contoh1: 'A案には多くの利点がある。\n(Terdapat banyak kelebihan dan kekuatan pada pelan/cadangan A.)',
    contoh2: 'このシステムを使う利点は何ですか。\n(Apakah kelebihan jika menggunakan sistem ini?)'
  },
  {
    id: 'm5h3_12',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '砂利',
    furigana: 'じゃり',
    arti: 'Batu kerikil',
    penjelasan: 'Batu-batu yang bersaiz kecil yang biasanya terhasil akibat hakisan, sering digunakan sebagai asas untuk membina laluan jalan, diletakkan di landasan kereta api, atau sebagai hiasan taman.',
    contoh1: '砂利道。\n(Laluan atau jalan raya yang berturapkan batu kerikil.)',
    contoh2: '庭に砂利を敷く。\n(Menabur dan meratakan batu kerikil di halaman rumah.)'
  },
  {
    id: 'm5h3_13',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '左利き',
    furigana: 'ひだりきき',
    arti: 'Kidal',
    penjelasan: 'Sifat semula jadi seseorang yang lebih dominan, cekap, dan selesa menggunakan tangan kiri untuk melakukan tugasan harian seperti menulis dan makan. Lawan katanya ialah 右利き (migikiki) iaitu kinan/pengguna tangan kanan.',
    contoh1: '左利きの人。\n(Individu yang kidal.)',
    contoh2: '左利き用のハサミ。\n(Gunting yang direka khas untuk kegunaan orang kidal.)'
  },
  {
    id: 'm5h3_14',
    minggu: '5',
    hari: '3',
    kategori: 'kata sifat',
    kanji: '有望（な）',
    furigana: 'ゆうぼう',
    arti: 'Berpotensi tinggi / Penuh harapan',
    penjelasan: 'Kata sifat ini digunakan untuk menggambarkan seseorang bakat, syarikat, atau projek yang menunjukkan tanda-tanda cerah, potensi besar, dan mempunyai harapan untuk mencapai kejayaan cemerlang pada masa hadapan.',
    contoh1: '有望な研究者。\n(Penyelidik yang mempamerkan potensi yang sangat tinggi.)',
    contoh2: '将来有望な若者。\n(Golongan belia yang menjanjikan masa depan yang cerah.)'
  },
  {
    id: 'm5h3_15',
    minggu: '5',
    hari: '3',
    kategori: 'kata sifat',
    kanji: '有益（な）',
    furigana: 'ゆうえき',
    arti: 'Bermanfaat / Berfaedah',
    penjelasan: 'Sesuatu tindakan, masa, maklumat, atau aktiviti yang memberikan nilai, manfaat, dan kebaikan yang ketara kepada diri sendiri atau orang lain. Antonim bagi perkataan ini ialah 無益 (mueki) iaitu sia-sia atau tidak berfaedah.',
    contoh1: '有益な本。\n(Buku yang padat dengan ilmu dan bermanfaat.)',
    contoh2: '休暇を有益に使う。\n(Menghabiskan masa cuti dengan melakukan aktiviti yang berfaedah.)'
  },
  {
    id: 'm5h3_16',
    minggu: '5',
    hari: '3',
    kategori: 'kata sifat',
    kanji: '有力（な）',
    furigana: 'ゆうりょく',
    arti: 'Berpengaruh / Mempunyai kemungkinan tinggi',
    penjelasan: 'Merujuk kepada entiti, individu, atau hujah yang memiliki kuasa, pengaruh, dan sokongan yang besar di dalam masyarakat. Ia juga digunakan untuk menyatakan sesuatu calon yang mempunyai peratusan yang sangat tinggi untuk menang.',
    contoh1: '地域の有力者。\n(Individu ternama atau orang yang sangat berpengaruh di kawasan tersebut.)',
    contoh2: '優勝の有力な候補。\n(Calon yang paling kuat dan dijangka akan memenangi kejohanan.)'
  },
  {
    id: 'm5h3_17',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '私有',
    furigana: 'しゆう',
    arti: 'Pemilikan peribadi / Hak persendirian',
    penjelasan: 'Merujuk kepada aset, hartanah, kewangan, atau kawasan yang dimiliki sepenuhnya oleh individu perseorangan atau pihak swasta, yang tidak boleh diceroboh oleh orang awam tanpa kebenaran.',
    contoh1: '私有財産。\n(Harta benda yang menjadi hak milik peribadi.)',
    contoh2: 'ここは私有地です。\n(Kawasan ini adalah tanah hak milik persendirian, bukan tempat awam.)'
  },
  {
    id: 'm5h3_18',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '有する',
    furigana: 'ゆうする',
    arti: 'Memiliki / Mempunyai',
    penjelasan: 'Satu bentuk kata kerja yang agak rasmi (formal) yang membawa maksud mempunyai, memegang, atau memiliki sesuatu benda abstrak mahupun fizikal, seperti hak kelayakan, kebolehan, atau harta.',
    contoh1: '権利を有する。\n(Berhak atau memiliki hak sepenuhnya ke atas sesuatu urusan.)',
    contoh2: '特別な能力を有する。\n(Memiliki bakat atau keupayaan yang sangat istimewa.)'
  },
  {
    id: 'm5h3_19',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '現行',
    furigana: 'げんこう',
    arti: 'Sedang berkuat kuasa / Semasa',
    penjelasan: 'Merujuk kepada dasar, undang-undang, tata kerja, atau sistem yang sedang digunakan dan berkuat kuasa pada masa ini. Apabila digabungkan menjadi 現行犯 (genkouhan), ia bermaksud seseorang yang tertangkap basah (ditangkap ketika sedang melakukan jenayah).',
    contoh1: '現行犯で逮捕される。\n(Ditangkap polis pada waktu kejadian / tertangkap basah sedang berbuat jenayah.)',
    contoh2: '現行の制度。\n(Sistem atau peraturan yang sedang berkuat kuasa pada masa ini.)'
  },
  {
    id: 'm5h3_20',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '現場',
    furigana: 'げんば',
    arti: 'Tapak kejadian / Lokasi kerja',
    penjelasan: 'Merujuk kepada lokasi fizikal sebenar di mana berlakunya sesuatu peristiwa seperti kemalangan dan jenayah, atau tapak di mana sesuatu kerja berat fizikal seperti pembinaan sedang giat dijalankan.',
    contoh1: '工事現場。\n(Tapak kawasan pembinaan dijalankan.)',
    contoh2: '事故の現場。\n(Tempat atau lokasi kejadian kemalangan.)'
  },
  {
    id: 'm5h3_21',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '現地',
    furigana: 'げんち',
    arti: 'Lokasi sebenar / Tempatan',
    penjelasan: 'Tempat, kawasan, atau negara tempatan di mana sesuatu acara, penugasan, atau misi itu dilakukan. Ia sering merujuk kepada kawasan destinasi yang berada di luar dari tempat penutur.',
    contoh1: '現地に向かう。\n(Mula bertolak menuju ke lokasi atau destinasi tersebut.)',
    contoh2: '現地の習慣を学ぶ。\n(Mempelajari adat resam penduduk di lokasi tempatan tersebut.)'
  },
  {
    id: 'm5h3_22',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '出現（する）',
    furigana: 'しゅつげん',
    arti: 'Kemunculan / Menampakkan diri',
    penjelasan: 'Perbuatan di mana sesuatu objek, kejadian, atau seseorang yang sebelum ini tersembunyi, tidak diketahui, atau tidak wujud, tiba-tiba muncul dan dapat dilihat oleh mata kasar.',
    contoh1: 'UFOが出現する。\n(Munculnya objek terbang yang tidak dikenali / UFO.)',
    contoh2: '新たなウイルスが出現した。\n(Satu varian virus yang baharu telah muncul.)'
  },
  {
    id: 'm5h3_23',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '再現（する）',
    furigana: 'さいげん',
    arti: 'Melakonkan semula / Meniru semula',
    penjelasan: 'Proses merancang, mereka bentuk, dan menghasilkan atau mewujudkan kembali sesuatu situasi, persekitaran, atau karya seni yang pernah berlaku pada masa lampau secara teliti dan tepat.',
    contoh1: '事故の状況を再現する。\n(Melakonkan atau merangsang semula situasi sewaktu kemalangan itu berlaku.)',
    contoh2: '当時の街並みを再現したテーマパーク。\n(Taman tema yang membina semula replika susun atur bandar dari zaman dahulu.)'
  },
  {
    id: 'm5h3_24',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '間柄',
    furigana: 'あいだがら',
    arti: 'Hubungan (antara manusia)',
    penjelasan: 'Merujuk kepada status perhubungan, keintiman, atau pertalian yang wujud di antara dua individu atau lebih, seperti hubungan kekeluargaan, pertemanan, mahupun hubungan romantis.',
    contoh1: '親密な間柄。\n(Hubungan yang sangat rapat, mesra, dan intim.)',
    contoh2: '彼とは兄弟のような間柄だ。\n(Hubungan saya dengannya adalah sangat rapat ibarat adik-beradik kandung.)'
  },
  {
    id: 'm5h3_25',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '事柄',
    furigana: 'ことがら',
    arti: 'Hal / Perkara / Isu',
    penjelasan: 'Satu istilah formal yang digunakan bagi merujuk kepada sesuatu subjek, fakta, urusan, keadaan, atau maklumat secara umum yang sedang diutarakan atau dibincangkan.',
    contoh1: '重要な事柄。\n(Hal, urusan, atau isu yang dipandang sangat penting.)',
    contoh2: '次の事柄について説明します。\n(Saya akan memberikan penjelasan mengenai perkara-perkara yang berikut.)'
  },
  {
    id: 'm5h3_26',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '人柄',
    furigana: 'ひとがら',
    arti: 'Keperibadian / Sifat seseorang',
    penjelasan: 'Merujuk kepada watak, sifat, atau karakter semula jadi yang ada dalam diri seseorang yang membentuk tingkah lakunya. Selalunya digunakan untuk memuji budi pekerti individu yang dinilai baik oleh orang sekeliling.',
    contoh1: '立派な人柄。\n(Mempunyai sifat dan perwatakan peribadi yang sangat mulia serta dihormati.)',
    contoh2: '彼の温かい人柄に惹かれる。\n(Tertarik dengan keperibadiannya yang sentiasa ramah dan hangat.)'
  },
  {
    id: 'm5h3_27',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '直訳（する）',
    furigana: 'ちょくやく',
    arti: 'Terjemahan langsung / Harfiah',
    penjelasan: 'Proses menterjemahkan sesuatu teks atau ungkapan secara bulat-bulat, iaitu perkataan demi perkataan dari satu bahasa ke bahasa yang lain, tanpa menyesuaikan konteks, tatabahasa, atau makna simpulan bahasanya.',
    contoh1: '文章を直訳する。\n(Menterjemahkan ayat tersebut secara terus/harfiah.)',
    contoh2: '直訳すると意味が通じない。\n(Jika diterjemahkan secara langsung, maksudnya tidak akan dapat difahami dengan logik.)'
  },
  {
    id: 'm5h3_28',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '内訳',
    furigana: 'うちわけ',
    arti: 'Butiran / Pecahan (Kewangan)',
    penjelasan: 'Merujuk kepada huraian atau pecahan terperinci bagi satu jumlah angka yang besar. Kerap digunakan dalam urusan penyata kewangan, resit, atau invois untuk menunjukkan ke mana wang tersebut disalurkan secara spesifik.',
    contoh1: '請求書の内訳。\n(Senarai pecahan butiran caj di dalam invois/bil.)',
    contoh2: '出費の内訳をチェックする。\n(Menyemak pecahan butiran pengeluaran perbelanjaan satu persatu.)'
  },
  {
    id: 'm5h3_29',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '言い訳（する）',
    furigana: 'いいわけ',
    arti: 'Memberi alasan',
    penjelasan: 'Satu percubaan atau kenyataan lisan yang dilakukan oleh seseorang untuk membela diri, menjelaskan rasional tindakannya, atau memohon maaf bagi mengurangkan beban kesalahannya apabila melakukan kesilapan atau kegagalan.',
    contoh1: '遅刻の言い訳をする。\n(Memberikan pelbagai alasan untuk melepaskan diri kerana datang lewat.)',
    contoh2: '言い訳は聞きたくない。\n(Saya langsung tidak mahu mendengar apa-apa alasan dari awak.)'
  },
  {
    id: 'm5h3_30',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '説得（する）',
    furigana: 'せっとく',
    arti: 'Memujuk / Meyakinkan',
    penjelasan: 'Usaha yang dilakukan melalui penerangan logik atau rayuan emosi yang berterusan, bertujuan untuk mengubah fikiran seseorang supaya mereka menerima pandangan, bersetuju, atau melakukan sesuatu tindakan.',
    contoh1: '親を説得する。\n(Berusaha memujuk dan meyakinkan ibu bapa untuk bersetuju.)',
    contoh2: '彼を説得してプロジェクトに参加させた。\n(Berjaya meyakinkan dia untuk turut serta di dalam projek tersebut.)'
  },
  {
    id: 'm5h3_31',
    minggu: '5',
    hari: '3',
    kategori: 'kata benda',
    kanji: '伝説',
    furigana: 'でんせつ',
    arti: 'Legenda',
    penjelasan: 'Boleh merujuk kepada dua perkara: Pertama, sebuah kisah, mitos, atau cerita rakyat bersejarah yang disampaikan secara lisan dari generasi ke generasi. Kedua, ia digunakan untuk merujuk kepada tokoh hebat yang sangat luar biasa pencapaiannya.',
    contoh1: '伝説上の人物。\n(Seorang pahlawan atau tokoh rekaan yang wujud di dalam kisah legenda.)',
    contoh2: 'この村には古い伝説がある。\n(Terdapat sebuah legenda lama yang diwarisi di kampung ini.)'
  },
  {
    id: 'm5h3_32',
    minggu: '5',
    hari: '3',
    kategori: 'kata kerja',
    kanji: '説く',
    furigana: 'とく',
    arti: 'Menerangkan / Berdakwah',
    penjelasan: 'Perbuatan menerangkan sesuatu prinsip, falsafah, kebenaran, atau ajaran agama secara bersemuka agar pihak satu lagi dapat memahami dan menerimanya. Ia adalah satu bentuk bimbingan atau penyampaian dakwah secara verbal.',
    contoh1: '教えを説く。\n(Menjelaskan, menyampaikan dan mengajarkan satu doktrin/ajaran kepada pengikut.)',
    contoh2: '仏教の教えを説く。\n(Menyampaikan dakwah mengenai falsafah serta ajaran agama Buddha.)'
  }
];

window.vocabData.push(...kosakata_m5h3);