// Gunakan window.vocabData array agar file JS lain bisa di-push juga nantinya
window.vocabData = window.vocabData || [];

const kosakata_m5h6 = [
  // --- KOSAKATA GAMBAR 1 (Kata Benda & Kata Keterangan) ---
  {
    id: 'm5h6_1',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '最寄り',
    furigana: 'もより',
    arti: 'Terdekat',
    penjelasan: 'Lokasi atau fasilitas umum (seperti stasiun atau minimarket) yang paling dekat dari posisi kita saat ini.',
    contoh1: '最寄りの駅。\n(Stasiun terdekat.)',
    contoh2: '最寄りのコンビニで買い物をする。\n(Berbelanja di minimarket terdekat.)'
  },
  {
    id: 'm5h6_2',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '誤り',
    furigana: 'あやまり',
    arti: 'Kesalahan / Kekeliruan',
    penjelasan: 'Kesalahan yang sifatnya teknis atau keliru informasi (seperti salah hitung, salah tulis, atau salah paham).',
    contoh1: '誤りが多い。\n(Banyak kesalahan.)',
    contoh2: '誤った考えを正す。\n(Memperbaiki pemikiran yang keliru.)'
  },
  {
    id: 'm5h6_3',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '過ち',
    furigana: 'あやまち',
    arti: 'Kesalahan besar / Dosa / Khilaf',
    penjelasan: 'Beda dengan 誤り, kata ini dipakai untuk kesalahan berat akibat kecerobohan/kekhilafan tindakan yang menimbulkan rasa menyesal mendalam.',
    contoh1: '過ちを犯す。\n(Melakukan kesalahan besar/dosa.)',
    contoh2: '若い頃の過ちを悔いる。\n(Menyesali kesalahan di masa muda.)'
  },
  {
    id: 'm5h6_4',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '値打ち',
    furigana: 'ねうち',
    arti: 'Nilai / Harga / Kualitas',
    penjelasan: 'Tingkat nilai atau kualitas berharga dari suatu benda/tindakan (apakah pantas/sepadan dengan harganya atau usahanya).',
    contoh1: '値打ちがある絵。\n(Lukisan yang memiliki nilai tinggi/berharga.)',
    contoh2: 'この本は読む値打ちがある。\n(Buku ini bernilai/layak untuk dibaca.)'
  },
  {
    id: 'm5h6_5',
    minggu: '5',
    hari: '6',
    kategori: 'kata sifat',
    kanji: '勝手',
    furigana: 'かって',
    arti: 'Egois / Semaunya sendiri',
    penjelasan: 'Sikap bertindak seenaknya tanpa memikirkan aturan, perasaan, atau dampaknya bagi orang lain.',
    contoh1: '勝手な行動をとる。\n(Bertindak semaunya sendiri/egois.)',
    contoh2: '自分の勝手な都合で休む。\n(Libur hanya demi kepentingan egois sendiri.)'
  },
  {
    id: 'm5h6_6',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '初耳',
    furigana: 'はつみみ',
    arti: 'Baru pertama kali dengar',
    penjelasan: 'Ungkapan saat baru pertama kali mengetahui kabar atau gosip yang sebelumnya belum pernah didengar sama sekali.',
    contoh1: 'その話は初耳だ。\n(Kabar itu baru pertama kali saya dengar.)',
    contoh2: '彼が結婚するなんて初耳です。\n(Saya baru dengar kalau dia mau menikah.)'
  },
  {
    id: 'm5h6_7',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '人並み',
    furigana: 'ひとなみ',
    arti: 'Rata-rata / Wajar seperti orang lain',
    penjelasan: 'Taraf hidup, kemampuan, atau kondisi standar yang wajar seperti masyarakat pada umumnya.',
    contoh1: '人並みの生活。\n(Kehidupan yang layak/normal seperti orang lain.)',
    contoh2: '人並みに英語が話せる。\n(Bisa bahasa Inggris standar rata-rata orang pada umumnya.)'
  },
  {
    id: 'm5h6_8',
    minggu: '5',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '軒並み',
    furigana: 'のきなみ',
    arti: 'Semuanya merata / Berderet',
    penjelasan: 'Dipakai saat menyatakan sesuatu (seperti harga barang atau omset) yang naik/turun secara bersamaan dan merata tanpa terkecuali.',
    contoh1: '軒並みに値上がりする。\n(Harganya naik semua secara merata.)',
    contoh2: '古い軒並みが続く。\n(Deretan rumah tua berjejer panjang.)'
  },
  {
    id: 'm5h6_9',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '人任せ',
    furigana: 'ひとまかせ',
    arti: 'Pasrah / Lepas tangan ke orang lain',
    penjelasan: 'Sikap enggan repot dengan melimpahkan seluruh pekerjaan atau keputusan kepada orang lain.',
    contoh1: '仕事を人任せにする。\n(Melemparkan pekerjaan ke orang lain.)',
    contoh2: '自分の人生を人任せにしてはいけない。\n(Jangan menyerahkan keputusan hidupmu pada orang lain.)'
  },
  {
    id: 'm5h6_10',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '善し悪し',
    furigana: 'よしあし',
    arti: 'Baik dan buruk',
    penjelasan: 'Melihat dua sisi sekaligus (sisi positif dan negatif, kelebihan dan kekurangan, atau benar dan salah).',
    contoh1: '物事の善し悪し。\n(Baik buruknya suatu hal.)',
    contoh2: 'この薬には善し悪しがある。\n(Obat ini punya sisi baik dan buruknya/efek samping.)'
  },
  {
    id: 'm5h6_11',
    minggu: '5',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '目の当たり',
    furigana: 'めのあたり',
    arti: 'Tepat di depan mata / Secara langsung',
    penjelasan: 'Biasanya dipakai 「目の当たりにする」 yang artinya menyaksikan suatu kejadian secara nyata dan langsung di hadapan mata sendiri.',
    contoh1: '惨状を目の当たりにする。\n(Melihat kondisi tragis itu langsung di depan mata.)',
    contoh2: 'プロの技を目の当たりにして感動した。\n(Kagum karena melihat skill profesional secara langsung.)'
  },
  {
    id: 'm5h6_12',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '応急',
    furigana: 'おうきゅう',
    arti: 'Darurat / Pertolongan pertama',
    penjelasan: 'Penanganan cepat dan sementara untuk situasi darurat sebelum dapat penanganan medis/resmi yang lengkap.',
    contoh1: '応急処置をする。\n(Melakukan tindakan pertolongan pertama/P3K.)',
    contoh2: '応急手当のおかげで助かった。\n(Selamat berkat penanganan darurat.)'
  },
  {
    id: 'm5h6_13',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '気配',
    furigana: 'けはい',
    arti: 'Tanda-tanda / Kehadiran / Firasat',
    penjelasan: 'Perasaan atau intuisi samar bahwa ada orang/hal yang mendekat atau terjadi, walau belum terlihat jelas oleh mata.',
    contoh1: '人の気配がする。\n(Merasakan ada tanda-tanda keberadaan orang.)',
    contoh2: '秋の気配を感じる。\n(Merasakan tanda-tanda datangnya musim gugur.)'
  },
  {
    id: 'm5h6_14',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '手際',
    furigana: 'てぎわ',
    arti: 'Keterampilan / Kecekatan',
    penjelasan: 'Kelincahan dan efisiensi seseorang dalam menuntaskan tugas (seperti memasak atau merakit barang) secara rapi dan cepat.',
    contoh1: '手際がいい。\n(Sangat cekatan dan terampil.)',
    contoh2: '彼女は料理の手際が素晴らしい。\n(Kecekatannya saat memasak sangat luar biasa.)'
  },
  {
    id: 'm5h6_15',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '知恵',
    furigana: 'ちえ',
    arti: 'Kebijaksanaan / Akal cerdik',
    penjelasan: 'Akal praktis atau ide cerdas untuk menyelesaikan masalah yang didapat dari pengalaman hidup.',
    contoh1: '知恵を出し合う。\n(Saling bertukar akal/ide bersama.)',
    contoh2: 'おばあちゃんの知恵袋。\n(Kumpulan tips cerdas/kebijaksanaan ala nenek-nenek.)'
  },
  {
    id: 'm5h6_16',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '自我',
    furigana: 'じが',
    arti: 'Ego / Kesadaran diri',
    penjelasan: 'Rasa akan identitas diri sendiri. Jika dikatakan 「自我が強い」(jiga ga tsuyoi), artinya orangnya egois/keras kepala mempertahankan kemauan.',
    contoh1: '自我が強い。\n(Egonya tinggi/keras kepala.)',
    contoh2: '幼児期に自我が芽生える。\n(Ego/kesadaran diri mulai tumbuh pada balita.)'
  },
  {
    id: 'm5h6_17',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '自己',
    furigana: 'じこ',
    arti: 'Diri sendiri',
    penjelasan: 'Kata formal untuk merujuk ke diri sendiri. Sering jadi awalan kata seperti 自己紹介 (perkenalan diri) atau 自己中 (egois).',
    contoh1: '自己中心的な人。\n(Orang yang egois/berpusat pada diri sendiri.)',
    contoh2: '自己を見つめ直す。\n(Merenungkan/mengintrospeksi diri sendiri.)'
  },
  {
    id: 'm5h6_18',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '作戦',
    furigana: 'さくせん',
    arti: 'Taktik / Strategi',
    penjelasan: 'Rencana siasat yang disusun matang untuk memenangkan pertandingan, permainan, atau bisnis.',
    contoh1: '作戦を練る。\n(Mematangkan strategi/taktik.)',
    contoh2: '新しい作戦を立てる。\n(Membuat taktik baru.)'
  },
  {
    id: 'm5h6_19',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '始末',
    furigana: 'しまつ',
    arti: 'Membereskan / Akhir cerita (buruk)',
    penjelasan: 'Punya 2 arti: (1) Pemberesan akibat masalah. (2) Akhir kejadian yang buruk/memalukan (sering memakai pola ～始末だ).',
    contoh1: '事故の始末をする。\n(Mengurus penyelesaian akibat kecelakaan.)',
    contoh2: '結局、彼に謝らせる始末となった。\n(Ujung-ujungnya, malah berakhir pada kondisi di mana dia harus minta maaf.)'
  },
  {
    id: 'm5h6_20',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '決意',
    furigana: 'けつい',
    arti: 'Tekad bulat / Keputusan pasti',
    penjelasan: 'Niat dan kemauan yang sangat bulat di dalam hati untuk mencapai atau menghentikan sesuatu.',
    contoh1: '決意を固める。\n(Memantapkan tekad bulat.)',
    contoh2: '辞職の決意を伝える。\n(Menyampaikan keputusan untuk mengundurkan diri.)'
  },
  {
    id: 'm5h6_21',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '意欲',
    furigana: 'いよく',
    arti: 'Semangat / Antusiasme / Hasrat',
    penjelasan: 'Dorongan motivasi yang kuat dari dalam diri untuk belajar, bekerja, atau meraih target.',
    contoh1: '意欲がある。\n(Punya semangat/antusiasme tinggi.)',
    contoh2: '学習意欲が高まる。\n(Motivasi belajarnya meningkat.)'
  },
  {
    id: 'm5h6_22',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '片言',
    furigana: 'かたこと',
    arti: 'Bahasa patah-patah / Terbata-bata',
    penjelasan: 'Kemampuan bicara bahasa asing (atau anak kecil) yang belum lancar sehingga baru bisa mengucapkan kata per kata.',
    contoh1: '片言でしゃべる。\n(Bicara dengan terbata-bata.)',
    contoh2: '片言の日本語で挨拶した。\n(Membawa salam pakai bahasa Jepang yang masih patah-patah.)'
  },
  {
    id: 'm5h6_23',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '独自',
    furigana: 'どくじ',
    arti: 'Khas / Orisinal / Milik sendiri',
    penjelasan: 'Gaya, teknik, atau gagasan asli karya sendiri tanpa meniru atau bergantung pada pihak lain.',
    contoh1: '独自の見解。\n(Pandangan/pendapat orisinal milik sendiri.)',
    contoh2: '独自の技術を開発する。\n(Mengembangkan teknologi khas sendiri.)'
  },
  {
    id: 'm5h6_24',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '個々',
    furigana: 'ここ',
    arti: 'Masing-masing / Per individu',
    penjelasan: 'Menitikberatkan pada tiap-tiap orang atau unit secara terpisah (satu per satu), bukan sebagai kelompok.',
    contoh1: '個々に意見を聞く。\n(Mendengarkan pendapat secara individu per orang.)',
    contoh2: '個々の能力を評価する。\n(Mengevaluasi kemampuan masing-masing individu.)'
  },

  // --- KOSAKATA GAMBAR 2 (Kata Sifat "Na" & Sufiks) ---
  {
    id: 'm5h6_25',
    minggu: '5',
    hari: '6',
    kategori: 'kata benda',
    kanji: '従来',
    furigana: 'じゅうらい',
    arti: 'Cara lama / Konvensional',
    penjelasan: 'Sistem atau cara yang sudah dipakai sejak dulu hingga sekarang. Sering dibandingkan dengan inovasi baru.',
    contoh1: '従来の考え方。\n(Cara berpikir konvensional/gaya lama.)',
    contoh2: '従来通りに作業を進める。\n(Mengerjakan tugas dengan cara seperti biasa/sebelumnya.)'
  },
  {
    id: 'm5h6_26',
    minggu: '5',
    hari: '6',
    kategori: 'kata sifat',
    kanji: '無茶',
    furigana: 'むちゃ',
    arti: 'Nekat / Tidak masuk akal',
    penjelasan: 'Tindakan yang berlebihan, sembrono, atau menuntut hal absurd yang tidak menggunakan akal sehat.',
    contoh1: '無茶を言う。\n(Bicara hal yang tidak masuk akal/menuntut hal mustahil.)',
    contoh2: '無茶な運転をする。\n(Nyetir dengan ugal-ugalan/nekat.)'
  },
  {
    id: 'm5h6_27',
    minggu: '5',
    hari: '6',
    kategori: 'kata sifat',
    kanji: '過密',
    furigana: 'かみつ',
    arti: 'Sangat padat / Terlalu sesak',
    penjelasan: 'Kondisi jadwal yang sangat padat/ketat, atau wilayah yang jumlah populasinya terlalu padat.',
    contoh1: '過密スケジュール。\n(Jadwal yang sangat padat.)',
    contoh2: '都市の過密化が進む。\n(Kepadatan kota semakin meningkat.)'
  },
  {
    id: 'm5h6_28',
    minggu: '5',
    hari: '6',
    kategori: 'kata sifat',
    kanji: '不可欠',
    furigana: 'ふかけつ',
    arti: 'Sangat penting / Wajib ada',
    penjelasan: 'Sesuatu yang vital atau krusial; jika tidak ada, proses atau kehidupan tidak bisa berjalan.',
    contoh1: '生活に不可欠なもの。\n(Hal yang wajib ada dalam kehidupan.)',
    contoh2: '水は人間の体にとって不可欠だ。\n(Air sangat penting bagi tubuh manusia.)'
  },
  {
    id: 'm5h6_29',
    minggu: '5',
    hari: '6',
    kategori: 'kata sifat',
    kanji: '画期的',
    furigana: 'かっきてき',
    arti: 'Revolusioner / Terobosan baru',
    penjelasan: 'Penemuan atau ide baru yang belum pernah ada sebelumnya dan membawa perubahan besar/sejarah baru.',
    contoh1: '画期的な発見。\n(Penemuan revolusioner.)',
    contoh2: 'この薬は画期的な治療法になる。\n(Obat ini akan menjadi metode pengobatan baru yang sangat revolusioner.)'
  },
  {
    id: 'm5h6_30',
    minggu: '5',
    hari: '6',
    kategori: 'kata sifat',
    kanji: '客観的',
    furigana: 'きゃっかんてき',
    arti: 'Objektif',
    penjelasan: 'Penilaian netral berdasarkan fakta dan data nyata tanpa dicampuri emosi atau pendapat pribadi.',
    contoh1: '客観的な意見を求める。\n(Meminta pendapat yang objektif.)',
    contoh2: 'データを客観的に分析する。\n(Menganalisis data secara murni dan objektif.)'
  },
  {
    id: 'm5h6_31',
    minggu: '5',
    hari: '6',
    kategori: 'kata sifat',
    kanji: '自発的',
    furigana: 'じはつてき',
    arti: 'Inisiatif sendiri / Sukarela',
    penjelasan: 'Tindakan yang dilakukan atas kesadaran dan kemauan sendiri tanpa perlu disuruh atau dipaksa.',
    contoh1: '自発的に参加する。\n(Ikut serta secara sukarela atas inisiatif sendiri.)',
    contoh2: '社員の自発的な行動を促す。\n(Mendorong karyawan agar punya inisiatif sendiri.)'
  },
  {
    id: 'm5h6_32',
    minggu: '5',
    hari: '6',
    kategori: 'kata sifat',
    kanji: '強制的',
    furigana: 'きょうせいてき',
    arti: 'Memaksa / Diwajibkan',
    penjelasan: 'Tindakan mengharuskan orang lain menurut menggunakan wewenang/kekuatan, tanpa peduli orang itu mau atau tidak.',
    contoh1: '強制的に参加させる。\n(Memaksa seseorang untuk ikut serta.)',
    contoh2: '寄付を強制的に集める。\n(Mengumpulkan uang donasi secara paksa.)'
  }
];

window.vocabData.push(...kosakata_m5h6);