// Gunakan window.vocabData array agar file JS lain bisa di-push juga nantinya
window.vocabData = window.vocabData || [];

const kosakata_m2h5 = [
  // --- GAMBAR 1: Kata Sifat-i & Kata Sifat-na (Bahagian Atas) ---
  {
    id: 'm2h5_1',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '何気ない',
    furigana: 'なにげない',
    arti: 'Tidak disengaja / Bersahaja',
    penjelasan: 'Menggambarkan sesuatu tindakan, kata-kata, atau kelakuan yang dilakukan tanpa niat khusus, secara santai, atau tidak disengaja. Namun, kadang-kadang perkara yang "tidak disengaja" ini boleh memberi kesan mendalam kepada orang lain (seperti menyinggung perasaan).',
    contoh1: '何気ない言葉に傷つく。\n(Terluka oleh kata-kata yang tidak disengaja.)',
    contoh2: ''
  },
  {
    id: 'm2h5_2',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'あっけない',
    furigana: 'あっけない',
    arti: 'Terlalu singkat / Mengecewakan (kerana cepat berakhir)',
    penjelasan: 'Merujuk kepada perasaan tidak puas hati, hampa, atau kecewa kerana sesuatu perkara (seperti perlawanan, kehidupan, atau acara) berakhir dengan lebih cepat, mudah, atau ringkas daripada yang dijangkakan.',
    contoh1: 'あっけない人生。\n(Kehidupan yang berlalu dengan begitu singkat / mengecewakan.)',
    contoh2: ''
  },
  {
    id: 'm2h5_3',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'みすぼらしい',
    furigana: 'みすぼらしい',
    arti: 'Lusuh / Buruk rupa',
    penjelasan: 'Digunakan untuk menerangkan keadaan fizikal (seperti bangunan, pakaian, atau penampilan seseorang) yang kelihatan sangat usang, buruk, miskin, dan tidak terurus.',
    contoh1: 'みすぼらしい家。\n(Rumah yang lusuh dan buruk.)',
    contoh2: ''
  },
  {
    id: 'm2h5_4',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'みっともない',
    furigana: 'みっともない',
    arti: 'Memalukan / Tidak senonoh',
    penjelasan: 'Sifat, tingkah laku, atau penampilan yang tidak pantas dan memalukan jika dilihat oleh orang lain. Ia merosakkan imej atau martabat diri.',
    contoh1: 'みっともない態度。\n(Sikap yang memalukan / tidak senonoh untuk dilihat.)',
    contoh2: ''
  },
  {
    id: 'm2h5_5',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '汚らわしい',
    furigana: 'けがらわしい',
    arti: 'Menjijikkan / Kotor (secara moral)',
    penjelasan: 'Sesuatu yang dianggap sangat kotor, hina, atau tidak bermoral. Tahap kejijikannya sangat tinggi sehingga seseorang itu merasa tidak mahu langsung melihat, mendengar, atau menyentuhnya.',
    contoh1: '汚らわしい行為。\n(Perbuatan yang kotor dan menjijikkan dari segi moral.)',
    contoh2: ''
  },
  {
    id: 'm2h5_6',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '乏しい',
    furigana: 'とぼしい',
    arti: 'Kurang / Terhad / Miskin',
    penjelasan: 'Menunjukkan keadaan di mana sesuatu yang penting (seperti sumber alam, pengalaman, wang, atau pengetahuan) berada pada tahap yang sangat kurang, terhad, atau tidak mencukupi.',
    contoh1: 'わが国は資源に乏しい。\n(Negara kita kekurangan sumber daya alam.)',
    contoh2: ''
  },
  {
    id: 'm2h5_7',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'あくどい',
    furigana: 'あくどい',
    arti: 'Kejam / Licik / Kotor',
    penjelasan: 'Cara, taktik, atau perbuatan yang sangat jahat, licik, memeras gila-gila, dan melampaui batas etika. Sering digunakan dalam konteks perniagaan, penipuan, atau jenayah.',
    contoh1: 'あくどい商売。\n(Perniagaan yang menggunakan cara licik dan kotor.)',
    contoh2: ''
  },
  {
    id: 'm2h5_8',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '危うい',
    furigana: 'あやうい',
    arti: 'Berbahaya / Terancam',
    penjelasan: 'Keadaan yang berada di pinggir bahaya atau kegagalan. Jika tidak berhati-hati atau keadaan tidak berubah, sesuatu yang buruk pasti akan berlaku.',
    contoh1: 'このままでは合格が危うい。\n(Jika keadaan berterusan begini, peluang untuk lulus adalah terancam/tipis.)',
    contoh2: ''
  },
  {
    id: 'm2h5_9',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'ややこしい',
    furigana: 'ややこしい',
    arti: 'Rumit / Mengelirukan',
    penjelasan: 'Sesuatu yang sangat kompleks, berselirat, atau sukar diselesaikan kerana melibatkan terlalu banyak unsur atau masalah. Selalu digunakan untuk hubungan manusia atau urusan yang renyah.',
    contoh1: 'ややこしい関係。\n(Hubungan yang rumit dan kusut.)',
    contoh2: ''
  },
  {
    id: 'm2h5_10',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '素っ気ない',
    furigana: 'そっけない',
    arti: 'Dingin / Acuh tak acuh',
    penjelasan: 'Sikap, layanan, atau cara menjawab yang pendek, dingin, dan tidak menunjukkan sebarang kemesraan atau minat terhadap pihak lawan bicara.',
    contoh1: '素っ気ない返事。\n(Jawapan yang pendek, dingin dan acuh tak acuh.)',
    contoh2: ''
  },
  {
    id: 'm2h5_11',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'もろい',
    furigana: 'もろい',
    arti: 'Rapuh / Mudah hancur',
    penjelasan: 'Merujuk kepada struktur objek fizikal yang sangat mudah pecah, hancur, atau patah. Ia juga boleh digunakan secara metafora untuk hati, perasaan, atau hubungan yang mudah goyah.',
    contoh1: 'もろく壊れやすいワイングラス。\n(Gelas wain yang rapuh dan sangat mudah pecah.)',
    contoh2: ''
  },
  {
    id: 'm2h5_12',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '紛らわしい',
    furigana: 'まぎらわしい',
    arti: 'Mengelirukan',
    penjelasan: 'Keadaan di mana dua perkara kelihatan sangat serupa bentuk, bunyi, atau maknanya sehingga mudah menyebabkan seseorang salah sangka, tersilap, atau keliru.',
    contoh1: '紛らわしい言葉。\n(Perkataan yang mengelirukan kerana bunyinya/maksudnya serupa.)',
    contoh2: ''
  },
  {
    id: 'm2h5_13',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '久しい',
    furigana: 'ひさしい',
    arti: 'Sudah lama (masa berlalu)',
    penjelasan: 'Menunjukkan bahawa tempoh masa yang sangat panjang telah berlalu sejak kali terakhir sesuatu kejadian itu berlaku. Sering digunakan bersama bentuk negatif.',
    contoh1: '彼に久しく会っていない。\n(Saya sudah sangat lama tidak berjumpa dengannya.)',
    contoh2: ''
  },
  {
    id: 'm2h5_14',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'たやすい',
    furigana: 'たやすい',
    arti: 'Mudah / Gampang',
    penjelasan: 'Sesuatu yang boleh dicapai atau dilakukan dengan sangat mudah tanpa memerlukan banyak tenaga, masa, atau pemikiran yang mendalam.',
    contoh1: 'たやすく引き受ける。\n(Menerima atau bersetuju melakukan sesuatu dengan mudah tanpa berfikir panjang.)',
    contoh2: ''
  },
  {
    id: 'm2h5_15',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '平たい',
    furigana: 'ひらたい',
    arti: 'Rata / Pipih',
    penjelasan: 'Keadaan bentuk sesuatu benda yang permukaannya rata, pipih, tidak cembung atau tidak berlekuk. Ia mempunyai maksud yang sama dengan 平らな (taira na).',
    contoh1: '平たい石（＝平らな）。\n(Batu yang permukaannya rata / pipih.)',
    contoh2: ''
  },
  {
    id: 'm2h5_16',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'はかない',
    furigana: 'はかない',
    arti: 'Fana / Sementara / Singkat',
    penjelasan: 'Menggambarkan sesuatu yang sangat rapuh, tidak kekal lama, mudah hilang, atau cepat berakhir seperti nyawa manusia, mimpi, atau harapan.',
    contoh1: 'はかない命。\n(Nyawa yang fana / singkat dan mudah melayang.)',
    contoh2: ''
  },
  {
    id: 'm2h5_17',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'あやふや',
    furigana: 'あやふや',
    arti: 'Kabur / Tidak pasti / Ragu-ragu',
    penjelasan: 'Sikap, ingatan, pendirian, atau maklumat yang tidak jelas, tidak tetap, dan tidak dapat dipastikan kebenarannya. Menunjukkan ketegasan yang kurang.',
    contoh1: 'あやふやな態度をとる。\n(Menunjukkan sikap yang tidak pasti / berteka-teki.)',
    contoh2: ''
  },
  {
    id: 'm2h5_18',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'うつろ',
    furigana: 'うつろ',
    arti: 'Kosong / Hampa',
    penjelasan: 'Keadaan di mana terdapat kekosongan di dalam sesuatu. Paling kerap digunakan untuk pandangan mata yang kelihatan kosong, seolah-olah jiwanya tiada di situ atau hilang fokus/semangat.',
    contoh1: 'うつろな瞳。\n(Pandangan mata yang kosong / hilang fokus.)',
    contoh2: ''
  },
  {
    id: 'm2h5_19',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'こっけい',
    furigana: 'こっけい',
    arti: 'Lucu / Menggelikan / Konyol',
    penjelasan: 'Penampilan, perbuatan, atau kata-kata yang kelihatan kelakar, bodoh, atau tidak munasabah sehingga membuatkan orang yang melihat/mendengarnya tertawa.',
    contoh1: 'こっけいな姿。\n(Penampilan atau gaya yang lucu/menggelikan.)',
    contoh2: 'こっけいな話。\n(Cerita yang lucu atau konyol.)'
  },
  {
    id: 'm2h5_20',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'ちっぽけ',
    furigana: 'ちっぽけ',
    arti: 'Sangat kecil / Remeh / Kerdil',
    penjelasan: 'Sesuatu yang fizikalnya sangat kecil ukurannya, atau sesuatu abstrak (seperti kewujudan, nilai, dan impian) yang dianggap tidak mempunyai nilai atau kepentingan yang besar.',
    contoh1: 'ちっぽけな夢。\n(Impian yang sangat kecil / remeh.)',
    contoh2: ''
  },
  {
    id: 'm2h5_21',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'ぞんざい',
    furigana: 'ぞんざい',
    arti: 'Kasar / Sembarangan / Tidak sopan',
    penjelasan: 'Cara bertutur, bekerja, atau melayan orang/benda dengan kasar, sambil lewa, tidak sopan, dan tidak menunjukkan rasa hormat atau kehati-hatian.',
    contoh1: 'ぞんざいな言葉遣い。\n(Penggunaan kata-kata yang kasar dan tidak sopan.)',
    contoh2: ''
  },
  {
    id: 'm2h5_22',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '不気味',
    furigana: 'ぶきみ',
    arti: 'Menyeramkan / Aneh / Firasat buruk',
    penjelasan: 'Sesuatu suasana, bentuk, atau fenomena yang membuatkan seseorang berasa seram sejuk, takut, atau tidak selesa kerana wujudnya aura yang misteri atau aneh.',
    contoh1: '不気味な生き物。\n(Makhluk yang menyeramkan dan aneh.)',
    contoh2: ''
  },
  {
    id: 'm2h5_23',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '不細工',
    furigana: 'ぶさいく',
    arti: 'Buruk rupa / Jelek / Kekok',
    penjelasan: 'Bentuk wajah, rupa fizikal, atau hasil kerja tangan yang tidak cantik, tidak seimbang (proporsional), atau kelihatan sangat kekok potongannya.',
    contoh1: '不細工な形。\n(Bentuk yang buruk rupa / jelek.)',
    contoh2: ''
  },
  {
    id: 'm2h5_24',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '無茶',
    furigana: 'むちゃ',
    arti: 'Tidak masuk akal / Melulu',
    penjelasan: 'Tindakan, permintaan, atau kata-kata yang tidak bertepatan dengan logik, sangat melampaui batas, atau dilakukan secara semberono tanpa memikirkan kesan akibatnya.',
    contoh1: '無茶なことを言う。\n(Mengatakan sesuatu yang tidak masuk akal / mengarut.)',
    contoh2: ''
  },

  // --- GAMBAR 3: Kata Sifat-na Lanjutan ---
  {
    id: 'm2h5_25',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '雑',
    furigana: 'ざつ',
    arti: 'Cincai / Sambil lewa / Kasar',
    penjelasan: 'Merujuk kepada hasil kerja atau cara kerja yang dilakukan tanpa ketelitian, semberono, selekeh, dan tidak teliti.',
    contoh1: '彼の仕事は雑だ。\n(Hasil kerjanya sangat cincai/sambil lewa.)',
    contoh2: ''
  },
  {
    id: 'm2h5_26',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '露骨',
    furigana: 'ろこつ',
    arti: 'Terang-terangan / Nyata / Terbuka',
    penjelasan: 'Menunjukkan perasaan (biasanya perasaan negatif seperti kebencian atau ketidakpuasan) secara langsung, ketara, dan terbuka tanpa cuba diselindungkan langsung.',
    contoh1: '露骨に嫌がる。\n(Menunjukkan rasa tidak suka secara terang-terangan.)',
    contoh2: ''
  },
  {
    id: 'm2h5_27',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '念入り',
    furigana: 'ねんいり',
    arti: 'Sangat teliti / Berhati-hati',
    penjelasan: 'Melakukan persiapan, perancangan, atau sesuatu kerja dengan memfokuskan perhatian yang sangat mendalam kepada setiap butiran (detail) supaya tiada kesilapan berlaku.',
    contoh1: '念入りな計画。\n(Pelan atau rancangan yang dibuat dengan sangat teliti.)',
    contoh2: ''
  },
  {
    id: 'm2h5_28',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '密か',
    furigana: 'ひそか',
    arti: 'Rahsia / Tersembunyi / Diam-diam',
    penjelasan: 'Tindakan atau perasaan yang dilakukan atau disimpan secara diam-diam supaya tidak disedari atau diketahui oleh orang lain.',
    contoh1: '密かな楽しみ。\n(Keseronokan atau hobi yang dirahsiakan/dilakukan secara diam-diam.)',
    contoh2: ''
  },
  {
    id: 'm2h5_29',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'おろそか',
    furigana: 'おろそか',
    arti: 'Terabai / Lalai',
    penjelasan: 'Keadaan di mana seseorang gagal memberi perhatian atau tidak menguruskan sesuatu yang penting (seperti tugas, pelajaran, atau kesihatan) dengan wajar.',
    contoh1: '勉強がおろそかになる。\n(Pelajaran menjadi terabai.)',
    contoh2: ''
  },
  {
    id: 'm2h5_30',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'まとも',
    furigana: 'まとも',
    arti: 'Wajar & Layak / Secara langsung',
    penjelasan: 'Perkataan ini mempunyai dua makna utama: 1. Sesuatu yang wajar, jujur, mengikut piawaian normal (decent). 2. Berhadapan atau menerima sesuatu dari arah depan secara langsung / tepat.',
    contoh1: 'まともな仕事。\n(Pekerjaan yang wajar / dihormati / layak.)',
    contoh2: '風をまともに受ける。\n(Menerima tiupan angin tepat secara langsung dari arah hadapan.)'
  },
  {
    id: 'm2h5_31',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'ろくな～ない',
    furigana: 'ろくな～ない',
    arti: 'Tidak memuaskan / Tidak senonoh / Tidak sempurna',
    penjelasan: 'Struktur tatabahasa ini selalu dipadankan dengan kata kerja negatif (～ない). Ia digunakan untuk menyatakan bahawa sesuatu itu gagal mencapai tahap minimum kelayakan, tidak berguna, atau tidak dilakukan secara sempurna.',
    contoh1: 'それはろくな仕事ではない。\n(Itu bukanlah pekerjaan yang elok/senonoh.)',
    contoh2: '朝からろくに食べていない。\n(Sejak pagi tadi tidak makan dengan betul/kenyang.)'
  }
];

window.vocabData.push(...kosakata_m2h5);