// Gunakan window.vocabData array agar file JS lain bisa di-push juga nantinya
window.vocabData = window.vocabData || [];

const kosakata_m2h4 = [
  // --- GAMBAR 1 ---
  {
    id: 'm2h4_1',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: 'くすぐったい',
    furigana: 'くすぐったい',
    arti: 'Geli / Segan (dipuji)',
    penjelasan: 'Sensasi rasa geli saat disentuh, atau perasaan malu/segan ketika dipuji secara berlebihan.',
    contoh1: '足の裏がくすぐったい。\n(Telapak kakiku geli.)',
    contoh2: 'ほめられてくすぐったい気分だ。\n(Merasa segan/malu saat dipuji.)'
  },
  {
    id: 'm2h4_2',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '渋い',
    furigana: 'しぶい',
    arti: 'Sepat (rasa) / Keren / Masam',
    penjelasan: 'Rasa seperti teh kental yang sepat, gaya pria dewasa yang keren/klasik, atau wajah yang masam.',
    contoh1: 'このお茶は渋い。\n(Teh ini rasanya sepat.)',
    contoh2: '渋い顔をする。\n(Memasang wajah masam/cemberut.)'
  },
  {
    id: 'm2h4_3',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '華々しい',
    furigana: 'はなばなしい',
    arti: 'Megah / Cemerlang',
    penjelasan: 'Sesuatu yang sangat mencolok, indah, dan sukses besar (seperti prestasi atau kehidupan).',
    contoh1: '華々しい人生。\n(Kehidupan yang cemerlang/megah.)',
    contoh2: '華々しい活躍を見せる。\n(Memperlihatkan pencapaian yang gemilang.)'
  },
  {
    id: 'm2h4_4',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: 'みずみずしい',
    furigana: 'みずみずしい',
    arti: 'Segar / Berair',
    penjelasan: 'Kondisi makanan (sayur/buah) yang masih sangat segar, atau kulit yang terlihat lembap berseri.',
    contoh1: 'みずみずしい野菜。\n(Sayuran yang segar.)',
    contoh2: 'みずみずしい肌。\n(Kulit yang lembap dan segar.)'
  },
  {
    id: 'm2h4_5',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '寝苦しい',
    furigana: 'ねぐるしい',
    arti: 'Susah tidur (karena panas/gerah)',
    penjelasan: 'Kondisi lingkungan (biasanya panas/lembab) yang membuat seseorang sulit untuk tidur nyenyak.',
    contoh1: '暑くて寝苦しい夜。\n(Malam yang susah tidur karena panas.)',
    contoh2: '彼は寝苦しそうにしている。\n(Dia terlihat gelisah/sulit tidur.)'
  },
  {
    id: 'm2h4_6',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '息苦しい',
    furigana: 'いきぐるしい',
    arti: 'Sesak napas / Tertekan (suasana)',
    penjelasan: 'Kondisi fisik sulit bernapas, atau suasana lingkungan yang terasa sangat menekan/tidak bebas.',
    contoh1: '彼は息苦しそうだ。\n(Dia terlihat sulit bernapas/sesak.)',
    contoh2: '会議室の息苦しい雰囲気。\n(Suasana ruang rapat yang menekan/sumpek.)'
  },
  {
    id: 'm2h4_7',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '暑苦しい',
    furigana: 'あつくるしい',
    arti: 'Gerah / Mengganggu karena panas',
    penjelasan: 'Sesuatu yang membuat merasa gerah, sumpek, atau panas hingga terasa tidak nyaman dilihat/dirasakan.',
    contoh1: '暑苦しい部屋。\n(Kamar yang gerah/pengap.)',
    contoh2: '真夏にセーターは暑苦しい。\n(Memakai sweter di pertengahan musim panas itu bikin gerah.)'
  },
  {
    id: 'm2h4_8',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: 'すばしっこい',
    furigana: 'すばしっこい',
    arti: 'Lincah / Gesit',
    penjelasan: 'Gerakan yang sangat cepat, tangkas, lincah, dan sulit ditangkap.',
    contoh1: 'すばしっこい犬。\n(Anjing yang lincah/gesit.)',
    contoh2: '泥棒はすばしっこく逃げた。\n(Pencuri itu melarikan diri dengan gesit.)'
  },
  {
    id: 'm2h4_9',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '素早い',
    furigana: 'すばやい',
    arti: 'Cepat / Tanggap',
    penjelasan: 'Tindakan atau jawaban yang dilakukan dengan segera dan tidak menunda-nunda.',
    contoh1: '質問に素早く答える。\n(Menjawab pertanyaan dengan cepat/tanggap.)',
    contoh2: '素早い行動が求められる。\n(Dibutuhkan tindakan yang cepat.)'
  },
  {
    id: 'm2h4_10',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '速やか',
    furigana: 'すみやか',
    arti: 'Segera / Cepat (Formal)',
    penjelasan: 'Melakukan sesuatu secara formal dan cepat tanpa penundaan.',
    contoh1: '速やかに退去する。\n(Segera pergi/keluar secepatnya.)',
    contoh2: '速やかな対応に感謝します。\n(Terima kasih atas penanganannya yang cepat.)'
  },
  {
    id: 'm2h4_11',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '健全',
    furigana: 'けんぜん',
    arti: 'Sehat / Waras / Wajar',
    penjelasan: 'Kondisi yang benar, baik, dan tidak menyimpang (sering digunakan untuk pikiran atau keuangan).',
    contoh1: '健全な精神を育む。\n(Membina mental/jiwa yang sehat.)',
    contoh2: '会社の健全な財政。\n(Keuangan perusahaan yang sehat/stabil.)'
  },
  {
    id: 'm2h4_12',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '健やか',
    furigana: 'すこやか',
    arti: 'Sehat (Pertumbuhan/Fisik)',
    penjelasan: 'Keadaan yang sehat badannya dan tumbuh dengan baik (biasanya untuk anak-anak).',
    contoh1: '子供が健やかに育つ。\n(Anak tumbuh dengan sehat.)',
    contoh2: '健やかな毎日を送る。\n(Menjalani hari-hari yang sehat/bugar.)'
  },
  {
    id: 'm2h4_13',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '軽快',
    furigana: 'けいかい',
    arti: 'Lincah / Riang / Ringan',
    penjelasan: 'Gerakan badan yang terasa ringan, atau musik yang terdengar menyenangkan dan berirama.',
    contoh1: '軽快なリズムの曲。\n(Lagu dengan ritme yang riang/berirama.)',
    contoh2: '軽快な足取りで歩く。\n(Berjalan dengan langkah yang ringan/gesit.)'
  },
  {
    id: 'm2h4_14',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '好調',
    furigana: 'こうちょう',
    arti: 'Dalam kondisi baik / Lancar',
    penjelasan: 'Situasi yang sedang berjalan dengan lancar, menguntungkan, atau performa yang sedang bagus.',
    contoh1: '商品の好調な売れ行き。\n(Tingkat penjualan produk yang sedang laris/baik.)',
    contoh2: '今日の試合は好調だ。\n(Pertandingan hari ini berjalan lancar/bagus.)'
  },
  {
    id: 'm2h4_15',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '好評',
    furigana: 'こうひょう',
    arti: 'Populer / Reputasi baik',
    penjelasan: 'Mendapat penilaian, ulasan, atau respon yang sangat positif dari banyak orang.',
    contoh1: 'この新メニューは好評だ。\n(Menu baru ini populer/disukai banyak orang.)',
    contoh2: '映画は観客から好評を得た。\n(Film tersebut mendapat ulasan baik dari penonton.)'
  },
  {
    id: 'm2h4_16',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '滑らか',
    furigana: 'なめらか',
    arti: 'Mulus / Licin / Lancar',
    penjelasan: 'Permukaan benda/kulit yang halus tanpa hambatan, atau pembicaraan yang mengalir lancar.',
    contoh1: '赤ちゃんの滑らかな肌。\n(Kulit bayi yang mulus.)',
    contoh2: '滑らかに英語を話す。\n(Berbicara bahasa Inggris dengan lancar.)'
  },
  {
    id: 'm2h4_17',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '細やか',
    furigana: 'こまやか',
    arti: 'Penuh perhatian / Tulus',
    penjelasan: 'Perasaan kasih sayang yang mendalam, atau layanan yang sangat memperhatikan hal-hal detail.',
    contoh1: '細やかな愛情を感じる。\n(Merasakan kasih sayang yang hangat/tulus.)',
    contoh2: 'お客様への細やかなサービス。\n(Pelayanan yang mendetail/penuh perhatian kepada pelanggan.)'
  },
  {
    id: 'm2h4_18',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '鮮やか',
    furigana: 'あざやか',
    arti: 'Cerah (warna) / Brilian',
    penjelasan: 'Warna yang sangat cerah, tajam, dan kontras, atau performa yang memukau.',
    contoh1: '秋の鮮やかな紅葉。\n(Daun musim gugur yang warnanya cerah/tajam.)',
    contoh2: '鮮やかな手品に驚いた。\n(Terkejut melihat trik sulap yang brilian.)'
  },
  {
    id: 'm2h4_19',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '緩やか',
    furigana: 'ゆるやか',
    arti: 'Lambat / Landai / Longgar',
    penjelasan: 'Gerakan yang perlahan, kemiringan yang landai tidak curam, atau aturan yang tidak ketat.',
    contoh1: '川の流れが緩やかだ。\n(Aliran sungai lambat/tenang.)',
    contoh2: '緩やかなカーブを曲がる。\n(Berbelok di tikungan yang landai.)'
  },
  {
    id: 'm2h4_20',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: 'しなやか',
    furigana: 'しなやか',
    arti: 'Lentur / Fleksibel / Luwes',
    penjelasan: 'Tubuh/benda yang elastis dan melengkung dengan indah, atau gerakan yang luwes.',
    contoh1: '猫のしなやかな体。\n(Tubuh kucing yang lentur/fleksibel.)',
    contoh2: 'ダンサーのしなやかな動き。\n(Gerakan penari yang luwes.)'
  },
  {
    id: 'm2h4_21',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '和やか',
    furigana: 'なごやか',
    arti: 'Damai / Hangat / Ramah',
    penjelasan: 'Suasana yang santai, penuh kekeluargaan, dan tidak ada ketegangan sama sekali.',
    contoh1: '家族との和やかな会話。\n(Percakapan yang akrab dan damai dengan keluarga.)',
    contoh2: '会議は和やかな雰囲気で進んだ。\n(Rapat berjalan dengan suasana yang ramah.)'
  },
  {
    id: 'm2h4_22',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: 'のどか',
    furigana: 'のどか',
    arti: 'Tenang / Damai (Pedesaan/Cuaca)',
    penjelasan: 'Suasana tempat atau cuaca yang damai dan tenteram, jauh dari hiruk pikuk.',
    contoh1: '村ののどかな風景。\n(Pemandangan desa yang tenang/damai.)',
    contoh2: 'のどかな春の一日。\n(Satu hari di musim semi yang tenang.)'
  },

  // --- GAMBAR 2 ---
  {
    id: 'm2h4_23',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: 'シック',
    furigana: 'しっく',
    arti: 'Chic / Elegan / Klasik',
    penjelasan: 'Kata serapan dari Prancis. Gaya berpakaian atau dekorasi yang dewasa, sederhana, namun berkelas.',
    contoh1: 'シックなデザインの服。\n(Pakaian dengan desain yang chic/elegan.)',
    contoh2: '部屋をシックにまとめる。\n(Mendekorasi ruangan dengan gaya yang berkelas.)'
  },
  {
    id: 'm2h4_24',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: 'きらびやか',
    furigana: 'きらびやか',
    arti: 'Gemerlap / Mewah / Berkilauan',
    penjelasan: 'Penampilan, pakaian, atau bangunan yang penuh kilau, sangat indah, dan mewah.',
    contoh1: 'きらびやかな宮殿。\n(Istana yang gemerlap/mewah.)',
    contoh2: '彼女はきらびやかなドレスを着ている。\n(Dia memakai gaun yang berkilauan.)'
  },
  {
    id: 'm2h4_25',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: 'つぶら',
    furigana: 'つぶら',
    arti: 'Bulat dan menggemaskan (Mata)',
    penjelasan: 'Hanya digunakan untuk mendeskripsikan bentuk mata yang bulat, kecil, dan lucu.',
    contoh1: '赤ちゃんのつぶらな瞳。\n(Mata bayi yang bulat dan comel.)',
    contoh2: '犬がつぶらな目で見つめる。\n(Anjing menatap dengan mata bulatnya.)'
  },
  {
    id: 'm2h4_26',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '緊急',
    furigana: 'きんきゅう',
    arti: 'Darurat / Mendesak',
    penjelasan: 'Situasi yang perlu segera ditangani secepatnya karena sangat penting atau gawat.',
    contoh1: 'これは緊急な用事です。\n(Ini adalah urusan yang darurat/mendesak.)',
    contoh2: '緊急に会議を開く。\n(Membuka rapat secara darurat.)'
  },
  {
    id: 'm2h4_27',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '巧妙',
    furigana: 'こうみょう',
    arti: 'Cerdik / Licik / Mahir',
    penjelasan: 'Teknik atau strategi yang sangat pintar, namun sering digunakan dalam konteks kejahatan (licik).',
    contoh1: '詐欺師の巧妙な手口。\n(Modus/trik penipu yang sangat cerdik/licik.)',
    contoh2: '巧妙に仕組まれた罠。\n(Perangkap yang dirancang dengan sangat licik.)'
  },
  {
    id: 'm2h4_28',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '巧み',
    furigana: 'たくみ',
    arti: 'Mahir / Piawai',
    penjelasan: 'Tingkat keahlian, seni, atau kemampuan melakukan sesuatu dengan sangat luar biasa baik.',
    contoh1: '俳優の巧みな演技。\n(Akting aktor yang sangat mahir/piawai.)',
    contoh2: '巧みな言葉で人を騙す。\n(Menipu orang dengan kata-kata yang lihai.)'
  },
  {
    id: 'm2h4_29',
    minggu: '2',
    hari: '4',
    kategori: 'kata sifat',
    kanji: '円満',
    furigana: 'えんまん',
    arti: 'Harmonis / Damai',
    penjelasan: 'Hubungan yang baik tanpa perselisihan, atau penyelesaian masalah yang memuaskan semua pihak.',
    contoh1: '彼らは円満な家庭を築いている。\n(Mereka membangun keluarga yang harmonis.)',
    contoh2: 'トラブルを円満に解決する。\n(Menyelesaikan masalah dengan damai/memuaskan semua pihak.)'
  },
  {
    id: 'm2h4_30',
    minggu: '2',
    hari: '4',
    kategori: 'kata kerja',
    kanji: '透き通る',
    furigana: 'すきとおる',
    arti: 'Bening / Tembus pandang',
    penjelasan: 'Sifat benda (seperti kaca, air) yang bening. Sering dipakai dalam bentuk lampau (透き通った) untuk menjelaskan kata benda.',
    contoh1: '透き通ったガラス。\n(Kaca yang jernih/transparan.)',
    contoh2: '川の水が透き通っている。\n(Air sungainya bening/tembus pandang.)'
  }
];

window.vocabData.push(...kosakata_m2h4);