// Gunakan window.vocabData array agar file JS lain bisa di-push juga nantinya
window.vocabData = window.vocabData || [];

const kosakata_m2h5 = [
  // --- GAMBAR 1: Kata Sifat-i & Kata Sifat-na (Bahagian Atas) ---
  {
    id: 'm2h5_1',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '何気ない',
    furigana: 'なにげない',
    arti: 'Tidak disengaja / Biasa saja',
    penjelasan: 'Menggambarkan tindakan, kata-kata, atau sikap yang dilakukan secara spontan tanpa niat atau maksud tertentu. Seringkali hal yang dianggap "biasa saja" ini bisa memberikan kesan mendalam atau tanpa sadar menyinggung perasaan orang lain.',
    contoh1: '何気ない言葉に傷つく。\n(Terluka oleh kata-kata yang tidak disengaja.)',
    contoh2: '彼の何気ない一言が、私を勇気づけた。\n(Satu patah kata darinya yang diucapkan biasa saja, telah memberiku keberanian.)'
  },
  {
    id: 'm2h5_2',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'あっけない',
    furigana: 'あっけない',
    arti: 'Terlalu cepat berakhir / Mengecewakan',
    penjelasan: 'Menggambarkan perasaan hampa, tidak puas, atau kecewa karena sesuatu (seperti pertandingan, acara, atau kehidupan) berakhir dengan sangat cepat atau terlalu mudah di luar dugaan.',
    contoh1: 'あっけない人生。\n(Kehidupan yang berlalu dengan begitu singkat / mengecewakan.)',
    contoh2: '決勝戦はあっけなく終わってしまった。\n(Pertandingan final itu berakhir dengan terlalu cepat dan mengecewakan.)'
  },
  {
    id: 'm2h5_3',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'みすぼらしい',
    furigana: 'みすぼらしい',
    arti: 'Lusuh / Jelek / Tidak terawat',
    penjelasan: 'Digunakan untuk menggambarkan penampilan fisik (seperti pakaian, bangunan, atau penampilan seseorang) yang terlihat sangat usang, kotor, miskin, dan tidak enak dipandang.',
    contoh1: 'みすぼらしい家。\n(Rumah yang lusuh dan tidak terawat.)',
    contoh2: '彼はみすぼらしい服を着ていた。\n(Dia mengenakan pakaian yang lusuh dan jelek.)'
  },
  {
    id: 'm2h5_4',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'みっともない',
    furigana: 'みっともない',
    arti: 'Memalukan / Tidak pantas',
    penjelasan: 'Menunjukkan penampilan, sikap, atau perilaku yang sangat tidak pantas dan memalukan jika dilihat orang lain. Sesuatu yang dapat merusak citra atau harga diri.',
    contoh1: 'みっともない態度。\n(Sikap yang memalukan / tidak pantas untuk dilihat.)',
    contoh2: 'いい年をして人前で泣くなんてみっともない。\n(Menangis di depan umum di usia sedewasa ini sungguh memalukan.)'
  },
  {
    id: 'm2h5_5',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '汚らわしい',
    furigana: 'けがらわしい',
    arti: 'Menjijikkan / Kotor (secara moral)',
    penjelasan: 'Sesuatu yang dianggap sangat kotor, hina, atau tidak bermoral. Kejijikannya berada pada tahap di mana seseorang merasa tidak sudi untuk melihat, mendengar, atau menyentuhnya.',
    contoh1: '汚らわしい行為。\n(Perbuatan yang kotor dan menjijikkan secara moral.)',
    contoh2: 'そんな汚らわしい話は聞きたくない。\n(Aku sama sekali tidak ingin mendengar cerita menjijikkan seperti itu.)'
  },
  {
    id: 'm2h5_6',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '乏しい',
    furigana: 'とぼしい',
    arti: 'Kurang / Terbatas / Miskin (akan sesuatu)',
    penjelasan: 'Menunjukkan keadaan di mana sesuatu yang penting atau dibutuhkan (seperti sumber daya alam, pengalaman, pengetahuan, atau dana) jumlahnya sangat sedikit, kurang, atau tidak mencukupi.',
    contoh1: 'わが国は資源に乏しい。\n(Negara kita kekurangan sumber daya alam.)',
    contoh2: '彼はまだ経験が乏しいが、やる気はある。\n(Dia memang masih kurang pengalaman, tetapi memiliki semangat yang tinggi.)'
  },
  {
    id: 'm2h5_7',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'あくどい',
    furigana: 'あくどい',
    arti: 'Kejam / Licik / Jahat',
    penjelasan: 'Merujuk pada cara, taktik, atau perbuatan yang sangat licik, jahat, dan melampaui batas kewajaran. Sangat sering digunakan untuk menggambarkan penipuan, kejahatan, atau praktik bisnis yang kotor.',
    contoh1: 'あくどい商売。\n(Perniagaan yang menggunakan taktik licik dan kotor.)',
    contoh2: 'あくどい手口で高齢者からお金を騙し取る。\n(Menipu dan merampas uang dari lansia dengan taktik yang sangat licik.)'
  },
  {
    id: 'm2h5_8',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '危うい',
    furigana: 'あやうい',
    arti: 'Berbahaya / Kritis / Terancam',
    penjelasan: 'Keadaan kritis yang berada di ambang bahaya atau kegagalan. Jika dibiarkan atau tidak berhati-hati, sesuatu yang buruk pasti akan terjadi.',
    contoh1: 'このままでは合格が危うい。\n(Jika terus begini, peluang untuk lulus sangat terancam / kritis.)',
    contoh2: '事故で重傷を負い、命が危うい状態だ。\n(Mengalami luka berat akibat kecelakaan, kondisinya sangat kritis/nyawanya terancam.)'
  },
  {
    id: 'm2h5_9',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'ややこしい',
    furigana: 'ややこしい',
    arti: 'Rumit / Membingungkan / Ruwet',
    penjelasan: 'Sesuatu yang sangat kompleks, berbelit-belit, dan sulit diselesaikan karena melibatkan banyak unsur. Sering digunakan untuk hubungan antarmanusia, prosedur, atau penjelasan yang memusingkan.',
    contoh1: 'ややこしい関係。\n(Hubungan yang rumit dan ruwet.)',
    contoh2: '話がややこしくなってきたので、一度整理しよう。\n(Karena pembicaraannya mulai menjadi rumit/berbelit-belit, mari kita susun ulang dulu.)'
  },
  {
    id: 'm2h5_10',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '素っ気ない',
    furigana: 'そっけない',
    arti: 'Dingin / Acuh tak acuh / Cuek',
    penjelasan: 'Sikap, perilaku, atau cara menjawab yang singkat, dingin, dan sama sekali tidak menunjukkan keramahan, kepedulian, atau minat terhadap lawan bicaranya.',
    contoh1: '素っ気ない返事。\n(Jawaban yang singkat, dingin, dan acuh tak acuh.)',
    contoh2: '彼女は素っ気ない態度で私を無視した。\n(Dia mengabaikanku dengan sikap yang dingin dan cuek.)'
  },
  {
    id: 'm2h5_11',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'もろい',
    furigana: 'もろい',
    arti: 'Rapuh / Mudah hancur',
    penjelasan: 'Merujuk pada struktur objek fisik yang sangat mudah pecah, runtuh, atau hancur. Bisa juga digunakan secara metafora untuk menggambarkan hati, tekad, atau mental yang mudah goyah.',
    contoh1: 'もろく壊れやすいワイングラス。\n(Gelas wine yang rapuh dan sangat mudah pecah.)',
    contoh2: '彼は自信満々に見えるが、実は精神的にもろいところがある。\n(Dia terlihat sangat percaya diri, namun sebenarnya memiliki sisi mental yang rapuh.)'
  },
  {
    id: 'm2h5_12',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '紛らわしい',
    furigana: 'まぎらわしい',
    arti: 'Membingungkan (karena mirip)',
    penjelasan: 'Keadaan di mana dua hal atau lebih terlihat/terdengar sangat mirip secara bentuk, bunyi, atau makna, sehingga sangat mudah membuat orang salah sangka, keliru, atau tertukar.',
    contoh1: '紛らわしい言葉。\n(Perkataan yang membingungkan karena bentuk atau bunyinya mirip.)',
    contoh2: '本物と偽物のパッケージが非常に紛らわしい。\n(Kemasan barang asli dan palsunya sangat membingungkan karena persis sama.)'
  },
  {
    id: 'm2h5_13',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '久しい',
    furigana: 'ひさしい',
    arti: 'Sudah lama (waktu berlalu)',
    penjelasan: 'Menunjukkan bahwa jangka waktu yang cukup panjang telah berlalu sejak suatu kejadian terakhir kali terjadi. Sering digunakan untuk mengungkapkan durasi yang lama, baik dalam kalimat positif maupun negatif.',
    contoh1: '彼に久しく会っていない。\n(Saya sudah sangat lama tidak berjumpa dengannya.)',
    contoh2: '故郷を離れて久しい。\n(Sudah lama sekali waktu berlalu sejak aku meninggalkan kampung halaman.)'
  },
  {
    id: 'm2h5_14',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'たやすい',
    furigana: 'たやすい',
    arti: 'Mudah / Gampang',
    penjelasan: 'Sesuatu yang bisa dicapai, diselesaikan, atau dilakukan dengan sangat mudah tanpa memerlukan banyak tenaga, usaha, atau pemikiran yang mendalam. Bersinonim dengan "簡単" (kantan).',
    contoh1: 'たやすく引き受ける。\n(Menerima atau menyanggupi sesuatu dengan sangat mudah tanpa berpikir panjang.)',
    contoh2: 'その問題はたやすく解決できた。\n(Masalah tersebut bisa diselesaikan dengan mudah.)'
  },
  {
    id: 'm2h5_15',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '平たい',
    furigana: 'ひらたい',
    arti: 'Rata / Pipih / Sederhana (kiasan)',
    penjelasan: 'Bentuk fisik suatu benda yang permukaannya rata, pipih, dan tidak cembung. Bisa juga digunakan dalam kiasan "平たい言葉" yang berarti bahasa yang sederhana dan mudah dipahami oleh orang awam.',
    contoh1: '平たい石。\n(Batu yang permukaannya rata / pipih.)',
    contoh2: '専門用語を使わず、平たい言葉で説明してください。\n(Tolong jelaskan menggunakan bahasa yang sederhana/awam tanpa menggunakan istilah teknis.)'
  },
  {
    id: 'm2h5_16',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'はかない',
    furigana: 'はかない',
    arti: 'Fana / Sementara / Singkat',
    penjelasan: 'Menggambarkan sesuatu yang sangat rapuh, tidak kekal, mudah hilang, atau cepat berakhir. Biasanya digunakan secara puitis untuk nyawa manusia, mimpi, harapan, atau cinta.',
    contoh1: 'はかない命。\n(Nyawa yang fana / singkat dan mudah melayang.)',
    contoh2: '私の初恋は、はかなく散ってしまった。\n(Cinta pertamaku telah hancur dan berlalu dengan begitu singkat/fana.)'
  },
  {
    id: 'm2h5_17',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'あやふや',
    furigana: 'あやふや',
    arti: 'Kabur / Tidak pasti / Ambigu',
    penjelasan: 'Menggambarkan ingatan, informasi, pendirian, atau sikap yang tidak jelas, tidak pasti, dan ambigu. Sering dipakai ketika seseorang sengaja tidak memberikan jawaban yang tegas.',
    contoh1: 'あやふやな態度をとる。\n(Menunjukkan sikap yang ambigu / tidak pasti.)',
    contoh2: '記憶があやふやで、昨日のことをよく思い出せない。\n(Ingatanku kabur/tidak pasti, aku tidak bisa mengingat kejadian kemarin dengan baik.)'
  },
  {
    id: 'm2h5_18',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'うつろ',
    furigana: 'うつろ',
    arti: 'Kosong / Hampa',
    penjelasan: 'Keadaan kosong atau hampa di dalam sesuatu. Paling sering digunakan untuk menggambarkan tatapan mata atau ekspresi wajah yang tampak kosong, kehilangan fokus, atau seolah kehilangan semangat hidup.',
    contoh1: 'うつろな瞳。\n(Pandangan mata yang kosong / hilang fokus.)',
    contoh2: 'ショックのあまり、彼はうつろな顔をして座っていた。\n(Karena terlalu syok, dia duduk dengan ekspresi wajah yang kosong/hampa.)'
  },
  {
    id: 'm2h5_19',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'こっけい',
    furigana: 'こっけい',
    arti: 'Lucu / Konyol / Menggelikan',
    penjelasan: 'Penampilan, tingkah laku, atau kata-kata yang terlihat sangat konyol, aneh, atau tidak masuk akal sehingga membuat orang yang melihat atau mendengarnya tertawa (terkadang bernada ejekan).',
    contoh1: 'こっけいな姿。\n(Penampilan atau gaya yang konyol/menggelikan.)',
    contoh2: '彼の言い訳はあまりにもこっけいで、笑ってしまった。\n(Alasannya terlalu konyol/menggelikan, sehingga aku tak sengaja tertawa.)'
  },
  {
    id: 'm2h5_20',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'ちっぽけ',
    furigana: 'ちっぽけ',
    arti: 'Sangat kecil / Remeh / Kerdil',
    penjelasan: 'Merujuk pada sesuatu yang ukurannya sangat kecil, atau sesuatu yang abstrak (seperti masalah, keberadaan, kebanggaan) yang dianggap sama sekali tidak penting, remeh, dan tidak bernilai besar.',
    contoh1: 'ちっぽけな夢。\n(Impian yang dianggap sangat kecil / remeh.)',
    contoh2: '宇宙の大きさに比べれば、人間の悩みなどちっぽけなものだ。\n(Dibandingkan dengan luasnya alam semesta, masalah manusia adalah hal yang sangat remeh/kerdil.)'
  },
  {
    id: 'm2h5_21',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'ぞんざい',
    furigana: 'ぞんざい',
    arti: 'Kasar / Sembarangan / Ceroboh',
    penjelasan: 'Cara berbicara, bekerja, atau memperlakukan orang/barang secara kasar, asal-asalan, tidak sopan, dan tidak menunjukkan rasa hormat atau kehati-hatian sama sekali.',
    contoh1: 'ぞんざいな言葉遣い。\n(Penggunaan kata-kata yang kasar dan tidak sopan.)',
    contoh2: '借りた本をぞんざいに扱ってはいけない。\n(Tidak boleh memperlakukan buku pinjaman secara sembarangan/kasar.)'
  },
  {
    id: 'm2h5_22',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '不気味',
    furigana: 'ぶきみ',
    arti: 'Menyeramkan / Aneh / Firasat buruk',
    penjelasan: 'Sesuatu (seperti suasana, pemandangan, atau suara) yang membuat seseorang merasa merinding, takut, atau tidak nyaman karena adanya aura misterius atau firasat bahwa hal buruk akan terjadi.',
    contoh1: '不気味な生き物。\n(Makhluk yang bentuknya menyeramkan dan aneh.)',
    contoh2: '誰もいない夜の学校は、静まり返っていて不気味だった。\n(Sekolah di malam hari yang tidak ada siapa-siapa itu sunyi senyap dan terasa menyeramkan.)'
  },
  {
    id: 'm2h5_23',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '不細工',
    furigana: 'ぶさいく',
    arti: 'Jelek / Buruk rupa / Bentuknya canggung',
    penjelasan: 'Bentuk fisik, wajah, atau hasil karya tangan yang tidak proporsional, potongannya kasar, atau terlihat jelek. (Hati-hati, kata ini sangat menyinggung jika ditujukan untuk wajah seseorang).',
    contoh1: '不細工な形。\n(Bentuk yang buruk rupa / potongannya tidak proporsional.)',
    contoh2: '初めて作ったケーキは不細工だったが、味は良かった。\n(Kue yang pertama kali kubuat bentuknya jelek, tetapi rasanya enak.)'
  },
  {
    id: 'm2h5_24',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '無茶',
    furigana: 'むちゃ',
    arti: 'Tidak masuk akal / Melulu / Gegabah',
    penjelasan: 'Tindakan, tuntutan, atau pernyataan yang sama sekali tidak logis, melampaui batas kewajaran, atau dilakukan dengan gegabah tanpa memikirkan konsekuensinya.',
    contoh1: '無茶なことを言う。\n(Mengatakan sesuatu yang tidak masuk akal / sembarangan.)',
    contoh2: '初心者がいきなり雪山に登るなんて無茶だ。\n(Pemula tiba-tiba mendaki gunung salju adalah tindakan yang gegabah/tidak masuk akal.)'
  },

  // --- GAMBAR 3: Kata Sifat-na Lanjutan ---
  {
    id: 'm2h5_25',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '雑',
    furigana: 'ざつ',
    arti: 'Asal-asalan / Kasar / Tidak teliti',
    penjelasan: 'Merujuk pada hasil kerja, pembuatan, atau penanganan sesuatu yang dilakukan secara semberono, tidak rapi, dan kurang ketelitian.',
    contoh1: '彼の仕事は雑だ。\n(Hasil kerjanya sangat asal-asalan/kurang teliti.)',
    contoh2: '雑な扱いをしたせいで、カメラが壊れてしまった。\n(Kameranya rusak karena diperlakukan secara kasar/asal-asalan.)'
  },
  {
    id: 'm2h5_26',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '露骨',
    furigana: 'ろこつ',
    arti: 'Terang-terangan / Nyata / Terbuka',
    penjelasan: 'Menunjukkan perasaan (terutama yang negatif seperti kebencian atau rasa tidak nyaman) atau maksud tertentu secara langsung, terbuka, dan jelas tanpa ada usaha untuk menutup-nutupinya.',
    contoh1: '露骨に嫌がる。\n(Menunjukkan rasa tidak suka secara terang-terangan.)',
    contoh2: '彼女は私の提案に対して、露骨に不快な顔をした。\n(Dia menunjukkan wajah tidak senang secara terang-terangan terhadap usulanku.)'
  },
  {
    id: 'm2h5_27',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '念入り',
    furigana: 'ねんいり',
    arti: 'Sangat teliti / Berhati-hati / Ekstra cermat',
    penjelasan: 'Melakukan persiapan, perancangan, atau pemeriksaan dengan sangat cermat dan memperhatikan setiap detail yang paling kecil sekalipun untuk memastikan tidak ada kesalahan.',
    contoh1: '念入りな計画。\n(Rencana yang disusun dengan sangat teliti dan hati-hati.)',
    contoh2: '外出する前に、念入りに戸締まりをチェックした。\n(Sebelum pergi keluar, saya memeriksa kunci pintu dengan sangat teliti.)'
  },
  {
    id: 'm2h5_28',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: '密か',
    furigana: 'ひそか',
    arti: 'Rahasia / Tersembunyi / Diam-diam',
    penjelasan: 'Tindakan, rencana, atau perasaan yang dilakukan atau disimpan secara diam-diam dan sembunyi-sembunyi agar tidak diketahui atau disadari oleh orang lain.',
    contoh1: '密かな楽しみ。\n(Kesenangan/hobi yang dirahasiakan dan dilakukan secara diam-diam.)',
    contoh2: '彼は密かにライバルの会社に転職する準備を進めている。\n(Dia sedang mempersiapkan kepindahan kerja ke perusahaan saingan secara diam-diam.)'
  },
  {
    id: 'm2h5_29',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'おろそか',
    furigana: 'おろそか',
    arti: 'Terabai / Lalai / Tidak diurus',
    penjelasan: 'Keadaan di mana seseorang mengabaikan, menelantarkan, atau gagal memberikan perhatian yang cukup pada sesuatu yang seharusnya penting dan diprioritaskan (seperti tugas, pelajaran, atau kesehatan).',
    contoh1: '勉強がおろそかになる。\n(Pelajaran menjadi terabai.)',
    contoh2: 'バイトに夢中で、健康管理がおろそかになっている。\n(Karena terlalu asyik kerja sambilan, manajemen kesehatanku jadi terabai.)'
  },
  {
    id: 'm2h5_30',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'まとも',
    furigana: 'まとも',
    arti: 'Wajar & Layak / Normal / Secara langsung',
    penjelasan: 'Perkataan ini memiliki dua makna utama: 1. Sesuatu yang wajar, layak, sesuai norma masyarakat (decent). 2. Menerima sesuatu secara langsung atau berhadapan tepat dari arah depan.',
    contoh1: 'まともな仕事。\n(Pekerjaan yang wajar / layak / dihormati.)',
    contoh2: '怒った彼とは、まともに話ができない。\n(Aku tidak bisa berbicara secara normal/wajar dengannya yang sedang marah.)'
  },
  {
    id: 'm2h5_31',
    minggu: '2',
    hari: '5',
    kategori: 'kata sifat',
    kanji: 'ろくな～ない',
    furigana: 'ろくな～ない',
    arti: 'Tidak memuaskan / Tidak layak / Tidak beres',
    penjelasan: 'Pola tata bahasa ini selalu diikuti bentuk kata kerja negatif (～ない). Digunakan untuk menyatakan dengan nada keluhan bahwa sesuatu itu tidak beres, tidak berguna, tidak layak, atau tidak dilakukan dengan sempurna sebagaimana mestinya.',
    contoh1: 'それはろくな仕事ではない。\n(Itu bukanlah pekerjaan yang layak/beres.)',
    contoh2: 'あいつと関わると、ろくなことにならない。\n(Jika berurusan dengannya, tidak akan pernah terjadi hal yang beres/baik.)'
  }
];

window.vocabData.push(...kosakata_m2h5);