// Gunakan window.vocabData array agar file JS lain bisa di-push juga nantinya
window.vocabData = window.vocabData || [];

const kosakata_m2h1 = [
  // --- BAGIAN 1: Sikap & Perilaku Seseorang ---
  {
    id: 'm2h1_1',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: '強がる',
    furigana: 'つよがる',
    arti: 'Berpura-pura tegar / Berlagak kuat',
    penjelasan: 'Menunjukkan sikap kuat atau berani padahal sebenarnya lemah, sedih, atau takut. Sering digunakan untuk menggambarkan orang yang gengsi menyembunyikan kelemahannya.',
    contoh1: '「大丈夫」と強がる。\n(Berpura-pura tegar dengan berkata "Tidak apa-apa".)',
    contoh2: '彼は強がっているが、本当は泣きたいのだろう。\n(Dia memang berlagak kuat, tapi sebenarnya pasti ingin menangis.)'
  },
  {
    id: 'm2h1_2',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: 'くたびれる',
    furigana: 'くたびれる',
    arti: 'Sangat lelah / Usang',
    penjelasan: 'Kata kerja intransitif. Merujuk pada rasa lelah secara fisik setelah melakukan aktivitas. Bisa juga dipakai untuk benda (seperti pakaian) yang sudah lusuh atau usang karena lama dipakai.',
    contoh1: '歩き回ってくたびれた。\n(Sangat lelah karena berjalan keliling.)',
    contoh2: 'このコートはずいぶんくたびれている。\n(Mantel ini sudah sangat lusuh/usang.)'
  },
  {
    id: 'm2h1_3',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: 'ばてる',
    furigana: 'ばてる',
    arti: 'Habis tenaga / Kelelahan ekstrim',
    penjelasan: 'Lebih parah dari くたびれる. Artinya tenaga benar-benar terkuras habis sampai tidak bisa berbuat apa-apa lagi. Sering dikaitkan dengan kelelahan karena cuaca panas (夏ばて - natsubate) atau kerja keras.',
    contoh1: '残業続きでばてている。\n(Kelelahan parah karena lembur terus-menerus.)',
    contoh2: '暑さですっかりばててしまった。\n(Tenagaku benar-benar habis karena cuaca panas.)'
  },
  {
    id: 'm2h1_4',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: 'とぼける',
    furigana: 'とぼける',
    arti: 'Berpura-pura tidak tahu / Berlagak bodoh',
    penjelasan: 'Tindakan yang disengaja (sadar). Seseorang tahu kebenarannya, tapi berpura-pura bodoh atau mengalihkan pembicaraan untuk menghindari tanggung jawab.',
    contoh1: '「知らない」ととぼける。\n(Berpura-pura bodoh dengan berkata "Tidak tahu".)',
    contoh2: 'とぼけた顔をする。\n(Memasang wajah tak berdosa/pura-pura tidak tahu.)'
  },
  {
    id: 'm2h1_5',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: 'ぼける',
    furigana: 'ぼける',
    arti: 'Pikun / Buram / Tidak fokus',
    penjelasan: 'Bisa merujuk pada menurunnya daya ingat manusia (pikun karena usia). Jika merujuk pada benda/gambar, artinya buram atau fokusnya tidak jelas (blur).',
    contoh1: '年とともにぼけてくる。\n(Menjadi pikun seiring bertambahnya usia.)',
    contoh2: 'ピントがぼけた写真。\n(Foto yang blur/tidak fokus.)'
  },
  {
    id: 'm2h1_6',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: 'どもる',
    furigana: 'どもる',
    arti: 'Gagap / Terbata-bata',
    penjelasan: 'Kesulitan berbicara dengan lancar, biasanya karena gugup, terkejut, atau cemas.',
    contoh1: 'スピーチでどもる。\n(Gagap dalam berpidato.)',
    contoh2: '緊張して、ついどもってしまった。\n(Karena tegang, tanpa sadar aku bicara terbata-bata.)'
  },
  {
    id: 'm2h1_7',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: 'しくじる',
    furigana: 'しくじる',
    arti: 'Gagal / Melakukan kesalahan besar',
    penjelasan: 'Melakukan blunder atau kegagalan yang fatal dalam suatu tugas, ujian, atau pekerjaan.',
    contoh1: '入試でしくじる。\n(Gagal dalam ujian masuk.)',
    contoh2: '面接でしくじってしまった。\n(Saya mengacau/gagal saat wawancara.)'
  },
  {
    id: 'm2h1_8',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: '察する',
    furigana: 'さっする',
    arti: 'Merasakan / Menduga / Memaklumi',
    penjelasan: 'Mampu membaca situasi atau merasakan sesuatu yang tidak dikatakan secara langsung (seperti menebak perasaan orang atau merasakan firasat bahaya).',
    contoh1: '危険を察する。\n(Merasakan adanya bahaya.)',
    contoh2: '彼の気持ちを察して、何も言わなかった。\n(Memaklumi perasaannya, aku pun tidak mengatakan apa-apa.)'
  },
  {
    id: 'm2h1_9',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: 'ささげる',
    furigana: 'ささげる',
    arti: 'Mengabdi / Mempersembahkan',
    penjelasan: 'Memberikan sesuatu yang sangat berharga (seperti hidup, waktu, atau doa) untuk tujuan yang mulia atau untuk orang lain.',
    contoh1: '研究に一生をささげる。\n(Mempersembahkan seluruh hidup untuk penelitian.)',
    contoh2: '神に祈りをささげる。\n(Mempersembahkan doa kepada Tuhan.)'
  },
  {
    id: 'm2h1_10',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: 'おびえる',
    furigana: 'おびえる',
    arti: 'Ketakutan',
    penjelasan: 'Merasa sangat takut atau gemetar, biasanya karena ada ancaman, suara keras, atau sesuatu yang menyeramkan.',
    contoh1: '物音におびえる。\n(Ketakutan pada suara.)',
    contoh2: '犬は雷の音におびえていた。\n(Anjing itu ketakutan mendengar suara petir.)'
  },
  {
    id: 'm2h1_11',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: 'こみあげる',
    furigana: 'こみあげる',
    arti: 'Meluap / Berlinang',
    penjelasan: 'Perasaan (seperti sedih, marah, atau bahagia) yang tiba-tiba muncul dari dalam dada hingga tidak bisa ditahan, atau air mata yang tiba-tiba berlinang.',
    contoh1: '涙がこみあげる。\n(Air mata berlinang/meluap.)',
    contoh2: '怒りがこみあげてきた。\n(Rasa marah meluap-luap dari dalam diri.)'
  },
  {
    id: 'm2h1_12',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: 'うぬぼれる',
    furigana: 'うぬぼれる',
    arti: 'Besar kepala / Terlalu membanggakan diri',
    penjelasan: 'Sikap narsis atau terlalu percaya diri secara berlebihan atas kemampuan atau penampilannya sendiri.',
    contoh1: '彼女は自分が美人だとうぬぼれている。\n(Dia besar kepala menganggap dirinya cantik.)',
    contoh2: '才能があるからといって、うぬぼれてはいけない。\n(Mentang-mentang punya bakat, tidak boleh besar kepala.)'
  },
  {
    id: 'm2h1_13',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: 'ぼうぜんとする',
    furigana: 'ぼうぜんとする',
    arti: 'Terperangah / Bengong',
    penjelasan: 'Kondisi kaget luar biasa hingga kehilangan kata-kata, tercengang, atau terpaku diam (blank).',
    contoh1: '驚いてぼうぜんとする。\n(Tercengang karena kaget.)',
    contoh2: '事故のショックで、ぼうぜんとしていた。\n(Dia bengong/terperangah karena syok atas kecelakaan itu.)'
  },
  {
    id: 'm2h1_14',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: '赤らめる',
    furigana: 'あからめる',
    arti: 'Memerah (wajah/pipi)',
    penjelasan: 'Biasanya digunakan untuk mendeskripsikan wajah atau pipi yang berubah merah karena merasa malu atau marah.',
    contoh1: '顔を赤らめる。\n(Wajah memerah.)',
    contoh2: '彼女は恥ずかしそうに頬を赤らめた。\n(Dia meronakan pipinya dengan tersipu malu.)'
  },
  // --- BAGIAN 2: Ketertarikan & Kesalahan ---
  {
    id: 'm2h1_15',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: '凝る',
    furigana: 'こる',
    arti: 'Terobsesi / Sangat menggemari / Kaku (otot)',
    penjelasan: 'Memiliki dua makna utama: 1) Sangat mendalami atau menggemari suatu hobi. 2) Otot (terutama pundak) yang terasa kaku atau pegal.',
    contoh1: '釣りに凝る。\n(Sangat menggemari/terobsesi dengan memancing.)',
    contoh2: '肩が凝る。\n(Pundak terasa kaku/pegal.)'
  },
  {
    id: 'm2h1_16',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: '懲りる',
    furigana: 'こりる',
    arti: 'Kapok / Belajar dari kesalahan',
    penjelasan: 'Hati-hati dengan kanjinya yang mirip 凝る. 懲りる artinya kapok karena pernah mengalami hal buruk atau kegagalan, sehingga tidak ingin mengulanginya lagi.',
    contoh1: '失敗に懲りる。\n(Kapok karena kegagalan.)',
    contoh2: '一度ひどい目に遭って懲りた。\n(Saya kapok setelah sekali mengalami kejadian buruk.)'
  },
  {
    id: 'm2h1_17',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: 'こだわる',
    furigana: 'こだわる',
    arti: 'Sangat peduli / Terikat / Perfeksionis',
    penjelasan: 'Memiliki standar khusus atau sangat mementingkan detail terhadap suatu hal. Bisa bermakna positif (dedikasi) atau negatif (terlalu kaku/keras kepala).',
    contoh1: '物事にこだわる。\n(Terlalu memikirkan/terikat pada sesuatu.)',
    contoh2: '素材にこだわった料理。\n(Masakan yang sangat mementingkan/memilih kualitas bahan.)'
  },
  {
    id: 'm2h1_18',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: '戸惑う',
    furigana: 'とまどう',
    arti: 'Bingung / Ragu',
    penjelasan: 'Bingung karena menghadapi situasi baru yang belum pernah dialami atau hal yang tidak terduga, sehingga tidak tahu harus berbuat apa.',
    contoh1: '慣れない仕事に戸惑う。\n(Bingung dengan pekerjaan yang belum terbiasa.)',
    contoh2: '突然の質問に戸惑った。\n(Saya ragu/bingung menghadapi pertanyaan yang tiba-tiba.)'
  },
  {
    id: 'm2h1_19',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: '嘆く',
    furigana: 'なげく',
    arti: 'Meratapi / Bersedih',
    penjelasan: 'Mengeluhkan atau meratapi nasib buruk, kemalangan, atau kegagalan dengan perasaan sedih yang mendalam.',
    contoh1: '失敗を嘆く。\n(Meratapi kegagalan.)',
    contoh2: '不運を嘆いても仕方がない。\n(Tidak ada gunanya meratapi ketidakberuntungan.)'
  },
  {
    id: 'm2h1_20',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: 'ぼやく',
    furigana: 'ぼやく',
    arti: 'Mengeluh / Menggerutu',
    penjelasan: 'Mengutarakan ketidakpuasan atau keluhan secara pelan (ngomel/ngedumel) mengenai hal-hal sepele atau nasib.',
    contoh1: '「給料が安い」とぼやく。\n(Mengeluh sambil bergumam "Gajinya kecil".)',
    contoh2: '彼はいつも仕事の文句をぼやいている。\n(Dia selalu menggerutu tentang pekerjaannya.)'
  },
  {
    id: 'm2h1_21',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: 'まごつく',
    furigana: 'まごつく',
    arti: 'Kebingungan (tidak tahu harus berbuat apa)',
    penjelasan: 'Kebingungan dalam bertindak atau kebingungan mencari arah, biasanya karena panik atau tidak terbiasa.',
    contoh1: 'やり方がわからなくてまごつく。\n(Kebingungan karena tidak tahu cara melakukannya.)',
    contoh2: '道に迷ってまごついた。\n(Kebingungan karena tersesat di jalan.)'
  },
  {
    id: 'm2h1_22',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: '任す',
    furigana: 'まかす',
    arti: 'Mempercayakan / Menyerahkan',
    penjelasan: 'Menyerahkan tugas, pekerjaan, atau tanggung jawab kepada orang lain. Bentuk lainnya adalah 任せる (makaseru).',
    contoh1: '仕事を任される。\n(Dipercayakan sebuah pekerjaan - bentuk pasif.)',
    contoh2: 'あとは君に任すよ。\n(Sisanya aku serahkan padamu ya.)'
  },
  {
    id: 'm2h1_23',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: '和む',
    furigana: 'なごむ',
    arti: 'Menjadi tenang / Damai / Cair',
    penjelasan: 'Kondisi di mana ketegangan berkurang; suasana menjadi lebih ramah, rileks, hangat, dan damai.',
    contoh1: '心が和む。\n(Hati menjadi tenang/rileks.)',
    contoh2: '和やかな雰囲気。\n(Suasana yang damai dan hangat.)'
  },
  // --- BAGIAN 3: Keadaan Benda & Waktu ---
  {
    id: 'm2h1_24',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: 'こもる',
    furigana: 'こもる',
    arti: 'Mengurung diri / Tertahan di dalam',
    penjelasan: 'Memiliki arti sesuatu yang tertutup atau tidak keluar. Jika untuk manusia = mengurung diri (hikikomori). Jika untuk gas/suhu/perasaan = tertahan atau terkumpul di dalam.',
    contoh1: '家にこもる。\n(Mengurung diri di rumah.)',
    contoh2: '体に熱がこもる。\n(Panas tertahan di dalam tubuh / demam.)'
  },
  {
    id: 'm2h1_25',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: 'ごまかす',
    furigana: 'ごまかす',
    arti: 'Mengalihkan (pembicaraan) / Memanipulasi',
    penjelasan: 'Berbohong atau memanipulasi informasi untuk menutupi kesalahan, atau menipu demi keuntungan (seperti korupsi/memanipulasi harga).',
    contoh1: '笑って話をごまかす。\n(Mengalihkan pembicaraan dengan tertawa.)',
    contoh2: '値段をごまかす。\n(Memanipulasi/mencurangi harga.)'
  },
  {
    id: 'm2h1_26',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: 'さえる',
    furigana: 'さえる',
    arti: 'Terjaga / Jernih / Tajam',
    penjelasan: 'Kondisi yang cerah, tajam, atau bebas kabut. Mata yang さえる berarti terjaga (susah tidur). Otak yang さえる berarti pikiran sedang sangat jernih/fokus.',
    contoh1: 'コーヒーを飲んだら目がさえた。\n(Setelah minum kopi, mataku terjaga/tidak mengantuk.)',
    contoh2: '今日は頭がさえている。\n(Hari ini otakku sangat jernih.)'
  },
  {
    id: 'm2h1_27',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: 'かなう',
    furigana: 'かなう',
    arti: 'Terkabul / Menandingi',
    penjelasan: 'Punya dua arti di N1: 1) Harapan yang menjadi kenyataan. 2) Mampu seimbang/menandingi kekuatan lawan (biasanya dalam bentuk negatif = tidak ada yang bisa menandingi).',
    contoh1: '願いがかなう。\n(Keinginan/doa terkabul.)',
    contoh2: '水泳では、彼にかなう者はいない。\n(Dalam olahraga renang, tidak ada yang bisa menandinginya.)'
  },
  {
    id: 'm2h1_28',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: 'かなえる',
    furigana: 'かなえる',
    arti: 'Mengabulkan / Mewujudkan',
    penjelasan: 'Ini adalah bentuk Transitif (membutuhkan objek) dari かなう. Artinya subjek melakukan usaha untuk mewujudkan sesuatu.',
    contoh1: '夢をかなえるために努力する。\n(Berusaha keras demi mewujudkan/mengabulkan mimpi.)',
    contoh2: '要求をかなえる。\n(Memenuhi/mengabulkan tuntutan.)'
  },
  {
    id: 'm2h1_29',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: '意気込む',
    furigana: 'いきごむ',
    arti: 'Bersemangat / Bertekad kuat',
    penjelasan: 'Memiliki semangat dan motivasi yang sangat tinggi untuk melakukan sesuatu dengan sukses.',
    contoh1: '「今度こそ勝つぞ！」と意気込む。\n(Bertekad bulat, "Kali ini pasti menang!".)',
    contoh2: '意気込んで仕事に取り掛かる。\n(Mulai mengerjakan tugas dengan penuh semangat.)'
  },
  {
    id: 'm2h1_30',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: '老ける',
    furigana: 'ふける',
    arti: 'Terlihat tua (penampilan)',
    penjelasan: 'Awas tertukar! 老ける (ふける) fokus pada PENAMPILAN luar. Orang yang usianya masih muda tapi wajah atau gayanya terlihat tua/boros muka.',
    contoh1: '彼は年のわりには老けて見える。\n(Dia terlihat tua dibandingkan umurnya.)',
    contoh2: '最近、少し老けたね。\n(Akhir-akhir ini, kamu kelihatan agak tua ya.)'
  },
  {
    id: 'm2h1_31',
    minggu: '2',
    hari: '1',
    kategori: 'kata kerja',
    kanji: '老いる',
    furigana: 'おいる',
    arti: 'Menua (secara usia/fisik)',
    penjelasan: 'Berbeda dengan 老ける. 老いる (おいる) merujuk pada proses biologis bertambahnya usia, di mana manusia memang menjadi lansia secara harfiah.',
    contoh1: '老いることは自然なことだ。\n(Menua adalah hal yang alami.)',
    contoh2: '老いてなお盛んだ。\n(Meski sudah tua renta, masih tetap energik.)'
  }
];

// Menambahkan kosakata dari file ini ke data master (array utama di HTML/sistem kamu)
window.vocabData.push(...kosakata_m2h1);