// Gunakan window.vocabData array agar file JS lain bisa di-push juga nantinya
window.vocabData = window.vocabData || [];

const kosakata_m6h2 = [
  // ==========================================
  // KELOMPOK 1: 通る (とおる) - Melewati / Tembus / Lulus
  // ==========================================
  {
    id: 'm6h2_1',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '高速道路が通る',
    furigana: 'こうそくどうろがとおる',
    arti: 'Jalan tol melintas / dibangun',
    penjelasan: 'Kata kerja 通る (とおる) di sini bermakna "dibangunnya sebuah jalur yang menghubungkan suatu tempat" atau "bisa dilewati". Penggunaan ini umum untuk infrastruktur seperti jalan raya, rel kereta, atau jalan tol yang membentang melewati suatu wilayah kota atau desa.',
    contoh1: '町に高速道路が通る。\n(Sebuah jalan tol akan dibangun melintasi kota ini.)',
    contoh2: '新しい鉄道が通って、とても便利になった。\n(Jalur kereta api baru telah beroperasi, sehingga menjadi sangat praktis.)',
    contoh3: 'この村にはバスが通っていない。\n(Bus tidak melintasi/beroperasi di desa ini.)'
  },
  {
    id: 'm6h2_2',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '名が通る',
    furigana: 'ながとおる',
    arti: 'Terkenal / Namanya dikenal luas',
    penjelasan: 'Ungkapan idiomatis "名が通る" (na ga tooru) secara harfiah berarti "namanya lewat", namun makna sebenarnya adalah "sangat terkenal" atau "bereputasi baik" di bidangnya sehingga namanya dikenal di mana-mana. Sering digunakan dalam bentuk lampau (名の通った) untuk menyifati kata benda.',
    contoh1: '彼は名の通った医師だ。\n(Dia adalah seorang dokter yang terkenal/bernama besar.)',
    contoh2: 'これは世界中に名が通っているブランドです。\n(Ini adalah merek yang namanya dikenal di seluruh dunia.)',
    contoh3: '業界で名が通るようになるには時間がかかる。\n(Butuh waktu untuk menjadi terkenal di industri ini.)'
  },
  {
    id: 'm6h2_3',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '声が通る',
    furigana: 'こえがとおる',
    arti: 'Suaranya lantang / Jelas terdengar',
    penjelasan: 'Frasa ini digunakan untuk menggambarkan jenis suara yang resonansinya bagus, lantang, dan mudah menembus kebisingan atau jarak, sehingga terdengar sangat jelas oleh orang lain. Sangat cocok untuk penyanyi, penyiar, atau guru.',
    contoh1: '彼の声はよく通る。\n(Suaranya sangat lantang dan jelas terdengar.)',
    contoh2: '彼女はよく通る声でスピーチを始めた。\n(Dia memulai pidatonya dengan suara yang lantang dan jelas.)',
    contoh3: '騒音の中でも通る声を出さなければならない。\n(Harus mengeluarkan suara yang bisa terdengar jelas bahkan di tengah kebisingan.)'
  },
  {
    id: 'm6h2_4',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '風が通る',
    furigana: 'かぜがとおる',
    arti: 'Angin masuk / Ventilasi baik',
    penjelasan: 'Secara harfiah berarti "angin lewat". Frasa ini merujuk pada sirkulasi udara atau ventilasi di sebuah ruangan atau rumah. Jika "風がよく通る", berarti rumah tersebut sejuk dan memiliki sirkulasi udara yang lancar.',
    contoh1: 'この部屋は風がよく通る家だ。\n(Kamar ini ada di rumah yang ventilasi udaranya sangat baik / anginnya masuk dengan baik.)',
    contoh2: '窓を開けると、涼しい風が通った。\n(Saat membuka jendela, angin yang sejuk masuk berhembus.)',
    contoh3: '風が通らない部屋は夏になるととても暑い。\n(Ruangan yang tidak ada sirkulasi udaranya akan sangat panas di musim panas.)'
  },
  {
    id: 'm6h2_5',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '鼻が通る',
    furigana: 'はながとおる',
    arti: 'Hidung lega (tidak tersumbat)',
    penjelasan: 'Merujuk pada kondisi fisik saat sedang flu. "通る" di sini berarti jalan pernapasan di hidung yang sebelumnya tersumbat atau buntu, kini telah terbuka atau tembus sehingga bisa bernapas dengan lega kembali.',
    contoh1: '薬を飲んだら、詰まっていた鼻が通るようになった。\n(Setelah minum obat, hidung yang tersumbat menjadi lega/plong.)',
    contoh2: '温かいお茶を飲むと鼻が通る。\n(Minum teh hangat membuat hidung terasa lega.)',
    contoh3: '鼻が通らなくて、息苦しい。\n(Hidungku tersumbat, rasanya sesak napas.)'
  },
  {
    id: 'm6h2_6',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: 'のどを通らない',
    furigana: 'のどをとおらない',
    arti: 'Tidak bisa tertelan / Tidak nafsu makan',
    penjelasan: 'Ungkapan metaforis yang artinya "makanan tidak bisa melewati tenggorokan". Ini bukan karena sakit tenggorokan, melainkan karena rasa sedih, cemas, atau tertekan yang mendalam sehingga seseorang sama sekali kehilangan selera atau kemampuan untuk menelan makanan.',
    contoh1: 'ショックで食べ物がのどを通らない。\n(Karena sangat terkejut, makanan tidak bisa tertelan / tidak nafsu makan.)',
    contoh2: '心配事があって、水すらのどを通らなかった。\n(Karena ada hal yang dicemaskan, jangankan makanan, air pun rasanya tidak bisa tertelan.)',
    contoh3: '悲しみで喉を通らない日々が続いた。\n(Hari-hari di mana tidak bisa makan karena kesedihan terus berlanjut.)'
  },
  {
    id: 'm6h2_7',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '議案が通る',
    furigana: 'ぎあんがとおる',
    arti: 'Usulan / RUU disetujui',
    penjelasan: 'Dalam konteks pemerintahan, rapat, atau parlemen, kata "通る" bermakna bahwa sebuah usulan (議案 - gian), rancangan undang-undang, atau rencana telah lulus evaluasi dan resmi disetujui atau disahkan.',
    contoh1: 'その議案が国会を通った。\n(Rancangan undang-undang tersebut telah disetujui oleh parlemen.)',
    contoh2: '私の企画案が会議で通った。\n(Rencana proyek saya telah disetujui di dalam rapat.)',
    contoh3: '予算案が無事に通って安心した。\n(Saya lega karena rancangan anggaran telah disetujui tanpa masalah.)'
  },
  {
    id: 'm6h2_8',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '火が通る',
    furigana: 'ひがとおる',
    arti: 'Matang (untuk masakan)',
    penjelasan: 'Secara harfiah "apinya tembus", yang artinya panas dari api telah menembus hingga ke bagian dalam bahan makanan. Frasa ini digunakan untuk memastikan apakah suatu bahan makanan (seperti daging) sudah matang sempurna sampai ke dalam atau belum.',
    contoh1: 'この肉は火がよく通っていない。\n(Daging ini belum matang sempurna / bagian dalamnya masih mentah.)',
    contoh2: '中までしっかり火が通っているか確認してください。\n(Tolong pastikan apakah sudah benar-benar matang sampai ke dalam.)',
    contoh3: '鶏肉は完全に火を通す必要がある。\n(Daging ayam perlu dimasak sampai benar-benar matang.)'
  },
  {
    id: 'm6h2_9',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '筋が通る',
    furigana: 'すじがとおる',
    arti: 'Masuk akal / Logis / Konsisten',
    penjelasan: 'Kata 筋 (suji) berarti urat atau alur. "筋が通る" berarti alur pikirannya nyambung, logis, tidak kontradiktif, dan masuk akal. Biasa digunakan untuk memuji argumen, cerita, atau perkataan seseorang yang konsisten.',
    contoh1: '彼の言うことは筋が通っている。\n(Apa yang dia katakan itu masuk akal dan konsisten.)',
    contoh2: '筋が通らない説明では誰も納得しない。\n(Tidak ada yang akan percaya dengan penjelasan yang tidak logis/tidak masuk akal.)',
    contoh3: 'ストーリーの筋が通っていて面白い映画だ。\n(Film itu menarik karena alur ceritanya masuk akal dan konsisten.)'
  },

  // ==========================================
  // KELOMPOK 2: 引く (ひく) - Menarik / Berkurang / Mundur
  // ==========================================
  {
    id: 'm6h2_10',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '綱を引く',
    furigana: 'つなをひく',
    arti: 'Menarik tali / jala',
    penjelasan: 'Ini adalah makna paling dasar dan harfiah dari 引く (hiku), yaitu menggunakan tenaga fisik untuk menarik suatu benda ke arah diri sendiri, seperti menarik tali (綱 - tsuna), jala nelayan, atau pintu.',
    contoh1: '漁師たちがみんなで網を引く。\n(Para nelayan bersama-sama menarik jala penangkap ikan.)',
    contoh2: '力いっぱい綱を引いてください。\n(Tolong tarik talinya dengan sekuat tenaga.)',
    contoh3: '綱引きの試合で綱を引く。\n(Menarik tambang dalam pertandingan tarik tambang.)'
  },
  {
    id: 'm6h2_11',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '潮が引く',
    furigana: 'しおがひく',
    arti: 'Air laut surut',
    penjelasan: 'Digunakan untuk fenomena alam. 潮 (shio) berarti air laut atau pasang surut. Ketika air laut bergerak menjauhi pantai (surut), orang Jepang menggunakan kata kerja 引く (menarik diri/mundur).',
    contoh1: '夕方になると潮が引く。\n(Menjelang sore hari, air laut akan surut.)',
    contoh2: '潮が引いた海辺でカニを探す。\n(Mencari kepiting di pinggir pantai saat air laut sedang surut.)',
    contoh3: '満ちていた潮が徐々に引いていった。\n(Air laut yang tadi pasang perlahan-lahan mulai surut.)'
  },
  {
    id: 'm6h2_12',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '手を引く (子供の)',
    furigana: 'てをひく',
    arti: 'Menuntun (dengan memegang tangan)',
    penjelasan: 'Jika objeknya adalah anak kecil atau orang tua yang lemah, "手を引く" bermakna menggandeng atau menuntun tangan mereka untuk membantu mereka berjalan secara fisik.',
    contoh1: '迷子にならないように、子どもの手を引く。\n(Saya menuntun tangan anak saya agar tidak tersesat.)',
    contoh2: 'おばあさんの手を引いて道を渡った。\n(Saya menuntun tangan nenek itu untuk menyeberang jalan.)',
    contoh3: '母親に手を引かれて歩く。\n(Berjalan sambil dituntun oleh sang ibu.)'
  },
  {
    id: 'm6h2_13',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '値段を引く',
    furigana: 'ねだんをひく',
    arti: 'Memberi diskon / Potongan harga',
    penjelasan: 'Dalam konteks matematika atau jual beli, 引く berarti "mengurangi" atau "mengurangkan". Jadi, "値段を引く" berarti mengurangi harga asli barang tersebut (memberikan diskon kepada pembeli).',
    contoh1: 'この商品は値段を引いて売られている。\n(Produk ini dijual dengan potongan harga/diskon.)',
    contoh2: '少し値段を引いてもらえませんか。\n(Bisakah Anda memberikan sedikit diskon/potongan harga?)',
    contoh3: '定価から20パーセント引きます。\n(Kami memotong harganya 20 persen dari harga normal.)'
  },
  {
    id: 'm6h2_14',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '水道を引く',
    furigana: 'すいどうをひく',
    arti: 'Memasang saluran air / Pipa air',
    penjelasan: 'Konsepnya adalah "menarik saluran pipa dari sumber air utama ke area pemukiman". Oleh karena itu, kata 引く digunakan untuk kegiatan instalasi jalur infrastruktur seperti pipa air, kabel telepon, atau jalur listrik.',
    contoh1: 'この地域に新しい水道を引く工事が始まる。\n(Pekerjaan memasang saluran pipa air yang baru di wilayah ini akan dimulai.)',
    contoh2: '山奥の家に電気と水道を引いた。\n(Kami telah memasang jalur listrik dan air ke rumah di pelosok gunung.)',
    contoh3: 'インターネットの回線を引く。\n(Memasang/menarik jaringan kabel internet.)'
  },
  {
    id: 'm6h2_15',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: 'おみくじを引く',
    furigana: 'おみくじをひく',
    arti: 'Mengambil / Menarik undian nasib',
    penjelasan: 'Untuk tindakan mengambil kartu, undian, atau kertas ramalan dari sebuah kotak secara acak, bahasa Jepang menggunakan kata 引く (menarik). Termasuk di dalamnya mengambil O-mikuji (kertas ramalan nasib di kuil Shinto).',
    contoh1: 'お正月には神社でおみくじを引く。\n(Pada perayaan Tahun Baru, saya mengambil undian ramalan nasib di kuil.)',
    contoh2: 'くじを引いて当たりが出た。\n(Saya menarik undian dan mendapatkan hadiah utama.)',
    contoh3: 'トランプのカードを一枚引いてください。\n(Tolong ambil/tarik satu kartu remi.)'
  },
  {
    id: 'm6h2_16',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '油を引く',
    furigana: 'あぶらをひく',
    arti: 'Mengoleskan / Menuangkan minyak',
    penjelasan: 'Dalam konteks memasak, 油を引く berarti mengoleskan atau meratakan lapisan minyak tipis di atas permukaan wajan (フライパン) sebelum mulai memasak agar makanan tidak lengket.',
    contoh1: 'フライパンに油を引いて、卵を焼く。\n(Mengoleskan/menuangkan minyak ke wajan, lalu menggoreng telur.)',
    contoh2: '鉄板に薄く油を引いてください。\n(Tolong oleskan minyak tipis-tipis di atas pelat besi panggang.)',
    contoh3: '油を引かずに肉を炒める。\n(Menumis daging tanpa menuangkan minyak.)'
  },
  {
    id: 'm6h2_17',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '熱が引く',
    furigana: 'ねつがひく',
    arti: 'Demam turun / Mereda',
    penjelasan: 'Sama seperti air laut yang surut (mundur), gejala penyakit seperti panas tubuh (demam), bengkak, atau rasa sakit yang mulai "mundur", "berkurang" atau "mereda" diekspresikan dengan kata 引く.',
    contoh1: '薬を飲んだら、熱が引いて平熱になった。\n(Setelah minum obat, demam saya turun dan kembali ke suhu tubuh normal.)',
    contoh2: '足の腫れがなかなか引かない。\n(Bengkak di kaki saya tidak kunjung mereda/kempes.)',
    contoh3: '痛みが引くまで安静にしてください。\n(Tolong istirahatlah sampai rasa sakitnya mereda.)'
  },
  {
    id: 'm6h2_18',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '注意を引く',
    furigana: 'ちゅういをひく',
    arti: 'Menarik perhatian',
    penjelasan: 'Secara psikologis, ini berarti menarik (memancing) ketertarikan, perhatian, atau simpati orang lain agar berpusat pada diri kita atau suatu benda.',
    contoh1: '注意を引くために大声を出す。\n(Mengeluarkan suara yang keras untuk menarik perhatian orang-orang.)',
    contoh2: '彼の派手な服装はみんなの目を引く。\n(Pakaiannya yang mencolok menarik pandangan semua orang.)',
    contoh3: '人々の関心を引くような記事を書く。\n(Menulis artikel yang dapat menarik ketertarikan masyarakat.)'
  },
  {
    id: 'm6h2_19',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '身を引く',
    furigana: 'みをひく',
    arti: 'Mundur / Mengundurkan diri',
    penjelasan: 'Frasa kiasan yang berarti menarik diri (tubuh) secara kiasan dari suatu posisi, perlombaan, pekerjaan, atau hubungan. Maknanya adalah mengundurkan diri, pensiun, atau menyerahkan posisi kepada orang lain.',
    contoh1: '彼は政治の世界から身を引く決心をした。\n(Dia telah mengambil keputusan untuk mengundurkan diri / pensiun dari dunia politik.)',
    contoh2: '若い人にチャンスを譲るために身を引く。\n(Menarik diri untuk memberikan kesempatan kepada orang yang lebih muda.)',
    contoh3: '彼らの恋愛の邪魔にならないよう、私は身を引いた。\n(Saya mundur agar tidak mengganggu hubungan asmara mereka.)'
  },
  {
    id: 'm6h2_20',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '血を引く',
    furigana: 'ちをひく',
    arti: 'Mewarisi darah / keturunan',
    penjelasan: 'Makna harfiahnya "menarik darah". Di sini bermakna mewarisi gen, keturunan, atau garis keturunan dari nenek moyang atau ras tertentu.',
    contoh1: '彼はイギリス人の血を引いている。\n(Dia mewarisi darah / keturunan dari orang Inggris.)',
    contoh2: '彼女は王族の血を引く人物だそうだ。\n(Katanya, dia adalah seseorang yang mewarisi garis keturunan keluarga kerajaan.)',
    contoh3: '音楽家の血を引いているので、ピアノが上手だ。\n(Karena mewarisi darah musisi, dia sangat pandai bermain piano.)'
  },

  // ==========================================
  // KELOMPOK 3: 乗る (のる) - Naik / Mengikuti / Terbawa
  // ==========================================
  {
    id: 'm6h2_21',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: 'リズムに乗る',
    furigana: 'りずむにのる',
    arti: 'Mengikuti irama',
    penjelasan: 'Kata 乗る (noru) di sini tidak berarti menaiki kendaraan, melainkan menyesuaikan gerakan tubuh atau perasaan agar sejalan dengan tempo/irama musik secara natural.',
    contoh1: '彼女は軽快なリズムに乗って踊った。\n(Dia menari mengikuti irama yang lincah dan ceria.)',
    contoh2: '音楽に乗って体を動かすのは楽しい。\n(Sangat menyenangkan menggerakkan tubuh mengikuti musik.)',
    contoh3: 'リズムに乗れないとダンスが不自然になる。\n(Jika tidak bisa mengikuti irama, tariannya akan terlihat tidak alami.)'
  },
  {
    id: 'm6h2_22',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '相談に乗る',
    furigana: 'そうだんにのる',
    arti: 'Mendengarkan curhat / Memberi saran',
    penjelasan: 'Frasa yang sangat umum digunakan! Jika seseorang "soudan ni noru", berarti ia bersedia mendengarkan permasalahan orang lain, merespons, dan berusaha memberikan nasehat atau solusi yang baik.',
    contoh1: 'いつでも友人の相談に乗るつもりだ。\n(Saya bermaksud untuk selalu bersedia mendengarkan curhat / memberi saran kepada teman kapan saja.)',
    contoh2: '先輩が進路の相談に乗ってくれた。\n(Senior bersedia mendengarkan dan memberi saran mengenai rencana karier masa depan saya.)',
    contoh3: '悩んでいるなら、いつでも相談に乗るよ。\n(Kalau kamu sedang bingung/ada masalah, aku selalu siap mendengarkan kok.)'
  },
  {
    id: 'm6h2_23',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '誘いに乗る',
    furigana: 'さそいにのる',
    arti: 'Menerima ajakan',
    penjelasan: 'Berarti Anda setuju untuk "naik" ke dalam rencana atau tawaran yang diajukan orang lain. Ini adalah cara natural untuk mengatakan bahwa Anda menerima undangan atau ajakan seseorang untuk melakukan sesuatu.',
    contoh1: '友人の誘いに乗って、一緒に旅行に行くことにした。\n(Saya menerima ajakan teman, dan memutuskan untuk pergi liburan bersamanya.)',
    contoh2: '彼の儲け話の誘いには乗らないほうがいい。\n(Sebaiknya kamu jangan menerima ajakan bisnis manisnya itu.)',
    contoh3: 'せっかくの誘いに乗ることにした。\n(Mumpung sudah diajak, saya memutuskan untuk ikut/menerima tawarannya.)'
  },
  {
    id: 'm6h2_24',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '手に乗る',
    furigana: 'てにのる',
    arti: 'Termakan tipuan / Masuk perangkap',
    penjelasan: 'Idiom yang bermakna tertipu atau terperangkap dalam jebakan atau taktik (手 - te) orang lain. Sangat sering diucapkan dalam bentuk negatif (その手には乗らない) yang artinya "Aku tidak akan tertipu oleh taktik itu!".',
    contoh1: 'その手には乗らないよ！\n(Aku tidak akan termakan oleh tipuan murahan itu!)',
    contoh2: 'うまい言葉に騙されて、相手の手に乗ってしまった。\n(Saya terpedaya oleh kata-kata manisnya, dan akhirnya masuk ke dalam permainannya/jebakannya.)',
    contoh3: '敵の手には絶対に乗るな。\n(Jangan pernah masuk ke dalam perangkap musuh.)'
  },
  {
    id: 'm6h2_25',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '調子に乗る',
    furigana: 'ちょうしにのる',
    arti: 'Terbawa suasana / Besar kepala',
    penjelasan: 'Bisa bermakna positif (pekerjaan berjalan makin lancar seiring berjalannya waktu), namun umumnya dipakai secara negatif untuk orang yang menjadi sombong, besar kepala, lengah, atau terbawa suasana setelah dipuji sedikit.',
    contoh1: '調子に乗っていると、いつか大きな失敗をするよ。\n(Kalau kamu terus-terusan besar kepala/sombong, suatu saat nanti kamu akan gagal fatal lho.)',
    contoh2: '褒められてすぐに調子に乗るのが彼の悪い癖だ。\n(Kebiasaan buruknya adalah dia langsung terbawa suasana/besar kepala ketika dipuji.)',
    contoh3: 'プロジェクトが調子に乗ってきた。\n(Proyeknya sudah mulai berjalan lancar/masuk ritme yang pas. -> Makna positif)'
  },
  {
    id: 'm6h2_26',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '風に乗る',
    furigana: 'かぜにのる',
    arti: 'Terbawa angin',
    penjelasan: 'Benda-benda ringan (seperti debu, serbuk sari, burung, atau balon) yang "naik" ke atas aliran angin dan terbawa terbang jarak jauh.',
    contoh1: '春になると、花粉が風に乗って運ばれる。\n(Saat musim semi tiba, serbuk sari terbang terbawa oleh angin.)',
    contoh2: '風に乗って、どこからか花の香りがしてきた。\n(Terbawa oleh angin, tercium aroma bunga entah dari mana.)',
    contoh3: '鳥たちが風に乗って気持ちよさそうに飛んでいる。\n(Burung-burung terbang dengan nyaman seolah sedang menaiki aliran angin.)'
  },
  {
    id: 'm6h2_27',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '気分が乗らない',
    furigana: 'きぶんがのらない',
    arti: 'Tidak mood / Tidak bersemangat',
    penjelasan: 'Kondisi di mana perasaan (気分) seseorang sedang tidak "naik" atau tidak ada semangat untuk melakukan suatu aktivitas yang diajukan.',
    contoh1: 'パーティーに誘われたが、気分が乗らないから断った。\n(Saya diundang ke pesta, tapi karena sedang tidak mood, saya menolaknya.)',
    contoh2: '今日はどうも勉強する気分が乗らない。\n(Hari ini entah kenapa saya sama sekali tidak ada mood untuk belajar.)',
    contoh3: '気分が乗るまで、しばらく休ませてください。\n(Tolong biarkan saya beristirahat sejenak sampai mood saya kembali membaik.)'
  },

  // ==========================================
  // KELOMPOK 4: 回す (まわす) - Memutar / Mengoper / Menunda
  // ==========================================
  {
    id: 'm6h2_28',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: 'ふたを回す',
    furigana: 'ふたをまわす',
    arti: 'Memutar tutup (botol dll)',
    penjelasan: 'Makna paling dasar dari kata kerja 回す (mawasu) adalah memutar suatu benda secara fisik, dalam hal ini seperti memutar tutup botol, kenop pintu, atau keran air.',
    contoh1: 'びんのふたを左に回すと開きます。\n(Jika Anda memutar tutup botolnya ke kiri, botol itu akan terbuka.)',
    contoh2: 'ドアの取っ手を右に回す。\n(Memutar gagang pintu ke sebelah kanan.)',
    contoh3: 'ネジを回してしっかりと固定する。\n(Memutar sekrup untuk mengencangkannya dengan kuat.)'
  },
  {
    id: 'm6h2_29',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '回覧板を回す',
    furigana: 'かいらんばんをまわす',
    arti: 'Mengedarkan (papan pengumuman)',
    penjelasan: 'Bermakna mengoperkan atau meneruskan suatu barang dari satu orang ke orang lain secara bergiliran dalam suatu kelompok. Sering dipakai untuk dokumen, mic karaoke, atau "kairanban" (papan pengumuman sirkuler khas perumahan Jepang).',
    contoh1: '町内の情報が書かれた回覧板を隣の家に回す。\n(Mengedarkan papan pengumuman yang berisi info lingkungan ke rumah tetangga sebelah.)',
    contoh2: '読んだら、その資料を次の人に回してください。\n(Setelah selesai dibaca, tolong oper dokumen tersebut ke orang berikutnya.)',
    contoh3: 'カラオケでマイクを回す。\n(Mengoper mic ke orang lain secara bergiliran saat berkaraoke.)'
  },
  {
    id: 'm6h2_30',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '手を回す (肩に)',
    furigana: 'てをまわす',
    arti: 'Melingkarkan / Merangkulkan tangan',
    penjelasan: 'Menempatkan tangan di sekitar tubuh orang lain dengan gerakan memutar melingkari bahu atau pinggang (seperti orang merangkul atau memeluk dari belakang/samping).',
    contoh1: '彼は優しく彼女の肩に手を回した。\n(Dia dengan lembut melingkarkan tangannya/merangkul bahu wanita itu.)',
    contoh2: '後ろから子供の腰に手を回して抱きしめる。\n(Melingkarkan tangan ke pinggang anak dari belakang lalu memeluknya.)',
    contoh3: '首にタオルを回す。\n(Melingkarkan handuk di leher.)'
  },
  {
    id: 'm6h2_31',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '敵に回す',
    furigana: 'てきにまわす',
    arti: 'Menjadikan sebagai musuh',
    penjelasan: 'Sebuah ungkapan yang berarti tindakan kita menyebabkan seseorang berbalik arah 180 derajat menjadi pihak oposisi atau musuh kita (biasanya merujuk pada orang yang seharusnya jadi teman malah kita buat jadi musuh).',
    contoh1: '彼の不用意な発言が、旧友を敵に回すことになった。\n(Ucapannya yang sembrono membuat teman lamanya berbalik menjadi musuhnya.)',
    contoh2: '消費者を敵に回すようなビジネスは長続きしない。\n(Bisnis yang menjadikan konsumennya sebagai musuh tidak akan bertahan lama.)',
    contoh3: '世界中を敵に回しても、君を守る。\n(Meskipun harus menjadikan seluruh dunia sebagai musuh, aku akan melindungimu.)'
  },
  {
    id: 'm6h2_32',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '洗濯機を回す',
    furigana: 'せんたくきをまわす',
    arti: 'Menyalakan / Memutar mesin cuci',
    penjelasan: 'Dalam bahasa Jepang sehari-hari, alih-alih menggunakan kata "menyalakan", mereka mengatakan "memutar mesin cuci". Ini berasal dari fakta bahwa bagian dalam mesin cuci berputar untuk mencuci baju.',
    contoh1: '朝起きたら、まず洗濯機を回すのが私の日課です。\n(Setelah bangun pagi, menyalakan mesin cuci adalah rutinitas pertama saya.)',
    contoh2: '洗濯機を回している間に、掃除を済ませよう。\n(Sembari mesin cucinya memutar cucian, mari kita selesaikan bersih-bersih rumah.)',
    contoh3: '夜遅くに洗濯機を回すと近所迷惑になる。\n(Menyalakan mesin cuci larut malam akan mengganggu tetangga.)'
  },
  {
    id: 'm6h2_33',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '事前に手を回す',
    furigana: 'じぜんてをまわす',
    arti: 'Mengatur sesuatu secara rahasia / di balik layar',
    penjelasan: 'Idiom "手を回す" (tanpa merujuk pada bagian tubuh fisik) berarti melakukan negosiasi rahasia, menyiapkan, atau mengatur segala sesuatunya di belakang layar terlebih dahulu agar rencana berjalan lancar atau menguntungkan pihak tertentu.',
    contoh1: 'トラブルにならないように、事前に手を回して準備しておく。\n(Agar tidak menjadi masalah, kami telah mengatur strategi/persiapan di balik layar secara diam-diam sebelumnya.)',
    contoh2: '彼がこっそり手を回したおかげで、契約が取れた。\n(Berkat dirinya yang diam-diam melakukan lobi/mengatur di balik layar, kami bisa mendapatkan kontrak itu.)',
    contoh3: '警察に手を回して事件をもみ消す。\n(Menyuap/Melakukan lobi rahasia ke polisi untuk menutupi kasus tersebut.)'
  },
  {
    id: 'm6h2_34',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '仕事を明日に回す',
    furigana: 'しごとをあしたにまわす',
    arti: 'Menunda pekerjaan (hingga besok)',
    penjelasan: 'Dalam urusan jadwal atau prioritas, 回す berarti "menggeser ke belakang" atau menunda. Artinya, Anda memindahkan alokasi waktu pekerjaan yang seharusnya sekarang menjadi nanti atau hari berikutnya.',
    contoh1: '今日は疲れたから、残りの仕事は明日に回すことにした。\n(Karena hari ini sudah capek, sisa pekerjaan ini saya putuskan untuk ditunda ke besok saja.)',
    contoh2: '面倒な用事を後回しにする癖がある。\n(Saya punya kebiasaan buruk menunda-nunda urusan yang merepotkan ke lain waktu.)',
    contoh3: 'その議論は次回の会議に回しましょう。\n(Mari kita tunda/pindahkan perdebatan tersebut ke rapat berikutnya.)'
  },
  {
    id: 'm6h2_35',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '連れ回す',
    furigana: 'つれまわす',
    arti: 'Membawa keliling / Kian kemari',
    penjelasan: 'Berasal dari kata 連れる (membawa seseorang) + 回す (memutar). Artinya adalah membawa seseorang ikut pergi berkeliling ke berbagai tempat tanpa tujuan yang terfokus, kadang memberi nuansa melelahkan bagi orang yang dibawa.',
    contoh1: '買い物で一日中子どもを連れ回すのは可哀想だ。\n(Kasihan anak itu seharian dibawa berkeliling kian-kemari untuk berbelanja.)',
    contoh2: '夜遅くまで客を連れ回して接待した。\n(Menjamu tamu dengan membawanya berkeliling dari satu tempat ke tempat lain hingga larut malam.)',
    contoh3: '彼に色々な観光地を連れ回された。\n(Saya dibawa berkeliling kian kemari ke berbagai tempat wisata olehnya.)'
  },
  {
    id: 'm6h2_36',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '電話を回す',
    furigana: 'でんわをまわす',
    arti: 'Menyambungkan telepon / Meneruskan',
    penjelasan: 'Bermakna mentransfer atau menyambungkan panggilan telepon masuk (ekstensi) kepada orang yang dituju. Sangat umum digunakan oleh resepsionis atau staf kantor.',
    contoh1: '少々お待ちください。すぐに社長室に電話を回します。\n(Mohon tunggu sebentar. Saya akan segera menyambungkan telepon ini ke ruang direktur.)',
    contoh2: '担当の部署へ電話を回していただけますか。\n(Bisakah Anda menyambungkan/mentransfer telepon ini ke departemen yang bersangkutan?)',
    contoh3: '内線を回す。\n(Menyambungkan jaringan telepon internal/ekstensi.)'
  },
  {
    id: 'm6h2_37',
    minggu: '6',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '患者を外科に回す',
    furigana: 'かんじゃをげかにまわす',
    arti: 'Merujuk / Mengirimkan (pasien)',
    penjelasan: 'Mengirimkan atau memindahkan penanganan seseorang/barang (dalam hal ini pasien di rumah sakit) ke bagian atau spesialis lain yang lebih tepat untuk mengurusnya (misalnya ke poli bedah/外科).',
    contoh1: '検査の結果、患者を外科に回すことになった。\n(Berdasarkan hasil pemeriksaan, diputuskan untuk merujuk pasien tersebut ke bagian bedah.)',
    contoh2: 'この案件は法務部に回したほうがいい。\n(Kasus/Proyek ini lebih baik dialihkan/dikirim penanganannya ke departemen hukum.)',
    contoh3: '重傷者を大きな病院へ回す。\n(Merujuk orang yang luka parah ke rumah sakit yang lebih besar.)'
  }
];

window.vocabData.push(...kosakata_m6h2);