// Gunakan window.vocabData array agar file JS lain bisa di-push juga nantinya
window.vocabData = window.vocabData || [];

const kosakata_m8h2 = [
  // --- KOSAKATA KANJI "一" ---
  {
    id: 'm8h2_1',
    minggu: '8',
    hari: '2',
    kategori: 'kata benda',
    kanji: '一同',
    furigana: 'いちどう',
    arti: 'Semua yang hadir / Seluruh anggota',
    penjelasan: 'Merujuk pada semua orang yang berkumpul atau semua anggota dalam suatu kelompok secara kolektif tanpa terkecuali.',
    contoh1: '家族一同を代表してご挨拶申し上げます。\n(Mewakili seluruh anggota keluarga, saya ingin menyampaikan salam.)',
    contoh2: '出席者一同、彼の話に感動した。\n(Seluruh hadirin, semuanya merasa terharu mendengar ceritanya.)'
  },
  {
    id: 'm8h2_2',
    minggu: '8',
    hari: '2',
    kategori: 'kata benda',
    kanji: '一面',
    furigana: 'いちめん',
    arti: 'Satu sisi / Seluruh permukaan / Halaman depan',
    penjelasan: 'Memiliki beberapa arti: satu aspek dari suatu hal, seluruh permukaan dari suatu tempat/benda, atau halaman utama/depan dari sebuah surat kabar.',
    contoh1: '物事の一面しか見ていない。\n(Hanya melihat satu aspek/sisi dari suatu hal.)',
    contoh2: '空一面に星が輝いている。\n(Bintang-bintang bersinar penuh di seluruh penjuru langit.)'
  },
  {
    id: 'm8h2_3',
    minggu: '8',
    hari: '2',
    kategori: 'kata benda',
    kanji: '一連',
    furigana: 'いちれん',
    arti: 'Serangkaian / Rentetan',
    penjelasan: 'Merujuk pada kejadian, peristiwa, atau tindakan yang terjadi secara berurutan dan saling berkaitan satu sama lain dalam satu kesatuan.',
    contoh1: '一連の事件が解決した。\n(Serangkaian/rentetan insiden tersebut akhirnya telah diselesaikan.)',
    contoh2: '一連のプロセスを確認する。\n(Memeriksa serangkaian tahapan proses yang saling terkait.)'
  },
  {
    id: 'm8h2_4',
    minggu: '8',
    hari: '2',
    kategori: 'kata benda',
    kanji: '一目',
    furigana: 'いちもく',
    arti: 'Sekilas pandang / Diakui kehebatannya',
    penjelasan: 'Berarti melihat secara sekilas. Frasa "一目置く" secara khusus digunakan ketika kita mengakui, segan, atau menghormati kemampuan seseorang yang lebih unggul.',
    contoh1: 'その違いは一目瞭然だ。\n(Perbedaan tersebut sangat jelas terlihat hanya dengan sekilas pandang.)',
    contoh2: '彼の才能には誰もが一目置いている。\n(Semua orang mengakui dengan segan bakatnya yang luar biasa.)'
  },
  {
    id: 'm8h2_5',
    minggu: '8',
    hari: '2',
    kategori: 'kata keterangan',
    kanji: '一律(に)',
    furigana: 'いちりつ(に)',
    arti: 'Merata / Sama rata',
    penjelasan: 'Tindakan memperlakukan segala sesuatunya dengan standar, jumlah, atau cara yang sama persis untuk semua orang, tanpa adanya pengecualian.',
    contoh1: 'ボーナスが一律１万円支給される。\n(Bonus akan dibayarkan secara merata sebesar 10.000 yen untuk semua pegawai.)',
    contoh2: '給料を一律に上げるのは難しい。\n(Sulit rasanya untuk menaikkan gaji secara sama rata ke semua orang.)'
  },
  {
    id: 'm8h2_6',
    minggu: '8',
    hari: '2',
    kategori: 'kata sifat',
    kanji: '一様(に)',
    furigana: 'いちよう(に)',
    arti: 'Seragam / Sama',
    penjelasan: 'Menunjukkan bahwa sikap, reaksi, raut wajah, atau keadaan sekumpulan orang atau benda semuanya tampak sama persis, tidak ada yang berbeda.',
    contoh1: '参加者は一様に驚きの声をあげた。\n(Para peserta memberikan reaksi suara terkejut yang seragam/sama.)',
    contoh2: '全員が一様な反応を示した。\n(Semua orang menunjukkan reaksi yang serupa/seragam.)'
  },
  {
    id: 'm8h2_7',
    minggu: '8',
    hari: '2',
    kategori: 'kata keterangan',
    kanji: '一瞬',
    furigana: 'いっしゅん',
    arti: 'Sesaat / Dalam sekejap',
    penjelasan: 'Waktu yang berlalu dengan sangat cepat, seolah hanya terjadi dalam sekejap mata atau satu kedipan saja.',
    contoh1: '一瞬、ためらった。\n(Saya ragu-ragu sejenak/sesaat.)',
    contoh2: 'それは一瞬の出来事だった。\n(Itu adalah kejadian yang berlangsung hanya dalam sekejap.)'
  },
  {
    id: 'm8h2_8',
    minggu: '8',
    hari: '2',
    kategori: 'kata benda',
    kanji: '一帯',
    furigana: 'いったい',
    arti: 'Seluruh kawasan / Daerah sekitar',
    penjelasan: 'Merujuk pada suatu wilayah tertentu secara keseluruhan, atau daerah luas yang ada di sekitar suatu lokasi.',
    contoh1: '警察は付近一帯を捜索した。\n(Polisi melakukan pencarian menyeluruh di seluruh kawasan sekitar.)',
    contoh2: 'この一帯は昔、海だった。\n(Seluruh daerah kawasan ini dulunya adalah lautan.)'
  },
  {
    id: 'm8h2_9',
    minggu: '8',
    hari: '2',
    kategori: 'kata keterangan',
    kanji: '一斉(に)',
    furigana: 'いっせい(に)',
    arti: 'Serentak / Bersamaan',
    penjelasan: 'Melakukan suatu tindakan atau gerakan secara bersama-sama pada waktu yang sama persis oleh orang atau benda dalam jumlah banyak.',
    contoh1: 'ランナーが一斉にスタートする。\n(Para pelari mulai berlari/start secara serentak bersamaan.)',
    contoh2: '鳥が一斉に飛び立った。\n(Burung-burung terbang ke udara secara serentak.)'
  },
  {
    id: 'm8h2_10',
    minggu: '8',
    hari: '2',
    kategori: 'kata keterangan',
    kanji: '一心(に)',
    furigana: 'いっしん(に)',
    arti: 'Sepenuh hati / Dengan sungguh-sungguh',
    penjelasan: 'Memusatkan seluruh pikiran, perasaan, dan perhatian dengan tulus hanya pada satu hal, tanpa teralihkan oleh hal yang lain.',
    contoh1: '彼女の無事を一心に祈る。\n(Berdoa dengan sepenuh hati demi keselamatannya.)',
    contoh2: '一心に本を読んでいる。\n(Sedang membaca buku dengan sungguh-sungguh dan penuh konsentrasi.)'
  },
  {
    id: 'm8h2_11',
    minggu: '8',
    hari: '2',
    kategori: 'kata keterangan',
    kanji: '一挙(に)',
    furigana: 'いっきょ(に)',
    arti: 'Sekaligus / Dalam satu tindakan',
    penjelasan: 'Melakukan atau menyelesaikan suatu hal yang besar secara langsung dan menyeluruh dalam satu waktu atau satu kesempatan saja.',
    contoh1: '問題が一挙に解決する。\n(Masalahnya dapat terselesaikan sekaligus dalam satu waktu.)',
    contoh2: '遅れを一挙に取り戻す。\n(Mengejar/memulihkan ketertinggalan secara sekaligus.)'
  },
  {
    id: 'm8h2_12',
    minggu: '8',
    hari: '2',
    kategori: 'kata keterangan',
    kanji: '一見(する)',
    furigana: 'いっけん(する)',
    arti: 'Sekilas / Tampaknya / Layak dilihat',
    penjelasan: 'Melihat sesuatu hanya sebentar/sekilas (seperti tampak asli, namun aslinya tidak). Bisa juga diartikan sesuatu itu sangat berharga untuk disaksikan (一見の価値がある).',
    contoh1: '一見本物のようだが、実は偽物だ。\n(Sekilas tampaknya seperti barang asli, tapi nyatanya palsu.)',
    contoh2: 'あの絵は一見の価値がある。\n(Lukisan itu sangat layak/berharga untuk dilihat sekali.)'
  },
  {
    id: 'm8h2_13',
    minggu: '8',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '一新(する)',
    furigana: 'いっしん(する)',
    arti: 'Memperbarui total / Menyegarkan',
    penjelasan: 'Mengubah, merombak, atau memperbarui keadaan, suasana, atau sistem secara menyeluruh sehingga hal tersebut terasa benar-benar segar dan baru.',
    contoh1: '気分を一新する。\n(Menyegarkan perasaan/suasana hati secara total.)',
    contoh2: '会社の体制が一新された。\n(Sistem dan struktur perusahaan telah diperbarui secara total.)'
  },
  {
    id: 'm8h2_14',
    minggu: '8',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '一掃(する)',
    furigana: 'いっそう(する)',
    arti: 'Menyapu bersih / Membasmi',
    penjelasan: 'Menghilangkan, membuang, atau menyingkirkan hal-hal buruk (seperti kejahatan, kecemasan, atau musuh) sampai benar-benar bersih tak tersisa.',
    contoh1: '社会から暴力を一掃する。\n(Menyapu bersih/membasmi kekerasan dari lingkungan masyarakat.)',
    contoh2: '不安を一掃するような知らせだった。\n(Itu adalah kabar yang berhasil menyapu bersih rasa cemas saya.)'
  },
  {
    id: 'm8h2_15',
    minggu: '8',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '一変(する)',
    furigana: 'いっぺん(する)',
    arti: 'Berubah total / Berubah drastis',
    penjelasan: 'Menggambarkan keadaan, situasi, kondisi alam, atau sikap seseorang yang berubah seratus delapan puluh derajat dari keadaan sebelumnya.',
    contoh1: '彼の態度は一変した。\n(Sikapnya telah berubah secara drastis/total.)',
    contoh2: '事件で街の様子が一変した。\n(Suasana kota berubah seratus delapan puluh derajat akibat insiden itu.)'
  },
  {
    id: 'm8h2_16',
    minggu: '8',
    hari: '2',
    kategori: 'kata benda',
    kanji: '一息',
    furigana: 'ひといき',
    arti: 'Ambil napas / Istirahat sejenak / Sedikit lagi',
    penjelasan: 'Bisa merujuk pada berhenti sebentar untuk tarik napas/beristirahat. Sering juga bermakna "sedikit lagi usaha akan membuahkan hasil" (あと一息).',
    contoh1: 'お茶を飲んで一息入れる。\n(Minum teh untuk mengambil napas/beristirahat sejenak.)',
    contoh2: 'あと一息で頂上だ。\n(Tinggal sedikit lagi kita akan sampai di puncak gunung.)'
  },
  {
    id: 'm8h2_17',
    minggu: '8',
    hari: '2',
    kategori: 'kata keterangan',
    kanji: '一頃',
    furigana: 'ひところ',
    arti: 'Suatu masa / Pernah suatu ketika',
    penjelasan: 'Menunjukkan suatu rentang waktu atau periode di masa lampau di mana sesuatu sempat sering terjadi atau sangat populer.',
    contoh1: 'その歌は一頃はやった歌だ。\n(Lagu tersebut adalah lagu yang pernah ngetren/populer pada suatu masa.)',
    contoh2: '一頃はよくこの公園で遊んだものだ。\n(Dulu, pernah suatu masa saya sering bermain di taman ini.)'
  },
  {
    id: 'm8h2_18',
    minggu: '8',
    hari: '2',
    kategori: 'kata benda',
    kanji: '一筋',
    furigana: 'ひとすじ',
    arti: 'Sepenuhnya dedikasi / Satu garis lurus',
    penjelasan: 'Fokus kuat yang mendedikasikan seluruh hidup, waktu, atau tenaga hanya untuk satu jalan, satu bidang, atau satu orang saja secara teguh.',
    contoh1: '田中さんは仕事一筋の人間だ。\n(Sdr. Tanaka adalah orang yang mendedikasikan hidupnya hanya semata untuk pekerjaan.)',
    contoh2: '学問一筋に生きる。\n(Hidup dengan jalan dedikasi sepenuhnya pada ilmu pengetahuan.)'
  },
  {
    id: 'm8h2_19',
    minggu: '8',
    hari: '2',
    kategori: 'kata benda',
    kanji: '一苦労',
    furigana: 'ひとくろう',
    arti: 'Sangat kerepotan / Susah payah',
    penjelasan: 'Situasi yang membutuhkan tenaga ekstra, usaha keras, atau cukup menyulitkan dan merepotkan untuk diselesaikan.',
    contoh1: 'レポートを仕上げるのは一苦労だった。\n(Menyelesaikan laporan tertulis ini adalah sebuah usaha yang bersusah payah.)',
    contoh2: '子供を寝かせるのは一苦労だ。\n(Menidurkan anak-anak adalah suatu kerepotan/kesulitan tersendiri.)'
  },
  {
    id: 'm8h2_20',
    minggu: '8',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '一休み(する)',
    furigana: 'ひとやすみ(する)',
    arti: 'Istirahat sebentar',
    penjelasan: 'Menghentikan aktivitas secara sementara dalam waktu singkat untuk memulihkan tenaga sebelum mulai beraktivitas kembali.',
    contoh1: 'この辺で、一休みしよう。\n(Mari kita beristirahat sebentar di sekitar sini.)',
    contoh2: '一休みしてから作業を再開する。\n(Saya akan melanjutkan pekerjaan lagi setelah istirahat sejenak.)'
  },
  {
    id: 'm8h2_21',
    minggu: '8',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '一眠り(する)',
    furigana: 'ひとねむり(する)',
    arti: 'Tidur sebentar / Tidur sejenak',
    penjelasan: 'Tidur dalam rentang waktu yang cukup singkat (seperti tidur siang) sekadar untuk menghilangkan kantuk dan menyegarkan tubuh.',
    contoh1: '一眠りしてから、また仕事をしよう。\n(Mari kita mulai bekerja kembali setelah tidur sejenak.)',
    contoh2: '疲れたので、一眠りしたい。\n(Karena capek, saya ingin rebahan/tidur sebentar.)'
  },

  // --- KOSAKATA KANJI "見" ---
  {
    id: 'm8h2_22',
    minggu: '8',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '見逃す',
    furigana: 'みのがす',
    arti: 'Melewatkan / Membiarkan (kesalahan)',
    penjelasan: 'Tidak memanfaatkan/mengambil suatu kesempatan baik, atau tindakan sengaja pura-pura tidak melihat dan memaafkan kesalahan seseorang.',
    contoh1: 'チャンスを見逃す。\n(Melewatkan begitu saja kesempatan yang ada.)',
    contoh2: '今回だけはミスを見逃してあげよう。\n(Hanya untuk kali ini saja, aku akan membiarkan/memaafkan kesalahanmu.)'
  },
  {
    id: 'm8h2_23',
    minggu: '8',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '見落とす',
    furigana: 'みおとす',
    arti: 'Terlewatkan / Tidak menyadari',
    penjelasan: 'Ketidaksengajaan saat melihat, sehingga ada hal penting, detail kecil, atau kesalahan yang gagal disadari dan luput dari perhatian.',
    contoh1: '書類の間違いを見落とす。\n(Terlewatkan/tidak menyadari adanya kesalahan ketik pada dokumen.)',
    contoh2: '重要な注意書きを見落としていた。\n(Saya tidak sengaja melewatkan teks catatan peringatan yang penting itu.)'
  },
  {
    id: 'm8h2_24',
    minggu: '8',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '見失う',
    furigana: 'みうしなう',
    arti: 'Kehilangan jejak / Kehilangan arah',
    penjelasan: 'Tidak bisa melihat lagi objek yang sedang diikuti secara fisik. Secara psikologis bermakna kehilangan motivasi, tujuan, atau pedoman hidup.',
    contoh1: '森の中で道を見失う。\n(Kehilangan arah jalan/tersesat saat berada di dalam hutan.)',
    contoh2: '人生の目標を見失ってしまった。\n(Saya telah kehilangan tujuan/arah hidup saya.)'
  },
  {
    id: 'm8h2_25',
    minggu: '8',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '見積もる',
    furigana: 'みつもり',
    arti: 'Mengestimasi / Menaksir',
    penjelasan: 'Menghitung, memperkirakan, atau mengkalkulasi secara kasar besaran biaya, anggaran, waktu, maupun kemampuan pihak lain.',
    contoh1: '工事の費用を見積もる。\n(Mengestimasi/menaksir besaran biaya konstruksi.)',
    contoh2: '相手の力を安く見積もる。\n(Meremehkan atau menaksir terlampau rendah akan kemampuan lawan.)'
  },
  {
    id: 'm8h2_26',
    minggu: '8',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '見計らう',
    furigana: 'みはからう',
    arti: 'Memperkirakan waktu yang tepat',
    penjelasan: 'Menganalisis situasi dan memperhitungkan dengan cermat momen atau waktu yang paling tepat untuk melakukan suatu tindakan.',
    contoh1: 'ラッシュの終わるころを見計らって出かける。\n(Memilih pergi keluar dengan memperkirakan waktu saat jam sibuk kemacetan selesai.)',
    contoh2: 'タイミングを見計らって話しかける。\n(Mengajak berbicara dengan mencari/menunggu momen yang pas.)'
  },
  {
    id: 'm8h2_27',
    minggu: '8',
    hari: '2',
    kategori: 'kata kerja',
    kanji: '見違える',
    furigana: 'みちがえる',
    arti: 'Pangling / Sulit dikenali (karena membaik)',
    penjelasan: 'Kondisi di mana seseorang atau benda mengalami perubahan drastis menjadi jauh lebih baik/cantik, sampai-sampai kita hampir tidak mengenalinya lagi.',
    contoh1: '父は見違えるように元気になった。\n(Ayah sudah menjadi sangat sehat, sampai-sampai bikin pangling.)',
    contoh2: 'リフォームで家が見違えるほど綺麗になった。\n(Berkat renovasi, kondisi rumah ini menjadi cantik sampai bikin kita pangling/sulit dikenali.)'
  },
  {
    id: 'm8h2_28',
    minggu: '8',
    hari: '2',
    kategori: 'kata benda',
    kanji: '見晴らし',
    furigana: 'みはらし',
    arti: 'Pemandangan (luas dari atas)',
    penjelasan: 'Pemandangan alam yang membentang sangat luas sejauh mata memandang tanpa ada penghalang, yang biasanya disaksikan dari titik lokasi yang tinggi.',
    contoh1: '見晴らしがいい部屋。\n(Kamar dengan pemandangan luar yang membentang luas dan bagus.)',
    contoh2: '山頂からの見晴らしは最高だ。\n(Pemandangan membentang yang dilihat dari puncak gunung adalah yang terbaik.)'
  }
];

window.vocabData.push(...kosakata_m8h2);