// Gunakan window.vocabData array agar file JS lain bisa di-push juga nantinya
window.vocabData = window.vocabData || [];

const kosakata_m7h6 = [
  // --- GAMBAR 1 ---
  {
    id: 'm7h6_1',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '差し出す',
    furigana: 'さしだす',
    arti: 'Mengulurkan / Menyerahkan',
    penjelasan: 'Mengulurkan tangan atau menyodorkan sesuatu (seperti kartu nama atau barang) ke orang lain.',
    contoh1: '名刺を差し出す。\n(Mengulurkan atau menyerahkan kartu nama.)',
    contoh2: '窓から顔を差し出す。\n(Mengeluarkan/mengulurkan wajah dari jendela.)'
  },
  {
    id: 'm7h6_2',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '差し引く',
    furigana: 'さしひく',
    arti: 'Memotong / Mengurangi',
    penjelasan: 'Memotong atau mengurangi nominal tertentu dari total keseluruhan (seperti potongan gaji atau pajak).',
    contoh1: '給料から税金を差し引く。\n(Memotong pajak dari gaji bulanan.)',
    contoh2: '点数を差し引く。\n(Mengurangi poin atau nilai ujian.)'
  },
  {
    id: 'm7h6_3',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '差し支える',
    furigana: 'さしつかえる',
    arti: 'Mengganggu / Menghambat',
    penjelasan: 'Sesuatu yang berdampak buruk atau mengganggu kelancaran aktivitas lain (seperti begadang mengganggu kerja).',
    contoh1: '夜更かしは翌日の仕事に差し支える。\n(Begadang akan mengganggu pekerjaan di keesokan harinya.)',
    contoh2: '体調が悪いと勉強に差し支える。\n(Kondisi badan yang buruk akan menghambat aktivitas belajar.)'
  },
  {
    id: 'm7h6_4',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '寄りかかる',
    furigana: 'よりかかる',
    arti: 'Bersandar / Bergantung',
    penjelasan: 'Menyandarkan badan ke dinding/tiang, atau bergantung pada bantuan orang lain secara berlebihan.',
    contoh1: '壁に寄りかかる。\n(Menyandarkan tubuh di dinding.)',
    contoh2: '親に寄りかかって生活する。\n(Hidup dengan bergantung pada orang tua.)'
  },
  {
    id: 'm7h6_5',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '寄り添う',
    furigana: 'よりそう',
    arti: 'Mendekat / Mendampingi',
    penjelasan: 'Duduk atau berada dekat di samping seseorang, atau mendampingi dan memberi dukungan emosional kepada orang yang bersedih.',
    contoh1: '寄り添って座る。\n(Duduk saling berdampingan dan merapat.)',
    contoh2: '悲しむ友人に寄り添う。\n(Mendampingi secara batin teman yang sedang bersedih.)'
  },
  {
    id: 'm7h6_6',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '寄せ集める',
    furigana: 'よせあつめる',
    arti: 'Mengumpulkan / Menghimpun',
    penjelasan: 'Mengumpulkan berbagai benda, barang, atau sisa-sisa yang tersebar menjadi satu tempat.',
    contoh1: 'ごみを寄せ集める。\n(Mengumpulkan sampah-sampah yang berserakan.)',
    contoh2: '残り物を寄せ集めて夕食を作る。\n(Membuat makan malam dengan mengumpulkan sisa-sisa bahan makanan.)'
  },
  {
    id: 'm7h6_7',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '押し切る',
    furigana: 'おしきる',
    arti: 'Bersikeras / Menerobos Penolakan',
    penjelasan: 'Tetap nekat memaksakan kehendak meski mendapat penolakan atau tentangan keras dari orang lain.',
    contoh1: '反対を押し切る。\n(Bersikeras dan menerobos penolakan / menolak peduli pada rintangan.)',
    contoh2: '親の猛反対を押し切って留学した。\n(Menerobos penolakan keras orang tua dan tetap pergi sekolah ke luar negeri.)'
  },
  {
    id: 'm7h6_8',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '押し込む',
    furigana: 'おしこむ',
    arti: 'Mendorong Masuk / Memaksa Masuk',
    penjelasan: 'Mendorong atau memjejal barang/orang masuk secara paksa ke dalam ruangan atau wadah yang sempit.',
    contoh1: '乗客を電車に押し込む。\n(Mendorong dan memaksa masuk penumpang ke dalam kereta api yang padat.)',
    contoh2: '荷物を無理やりカバンに押し込む。\n(Memasukkan barang bawaan ke dalam tas dengan paksa.)'
  },
  {
    id: 'm7h6_9',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '押し寄せる',
    furigana: 'おしよせる',
    arti: 'Menerjang / Membanjiri',
    penjelasan: 'Datang dan menyerbu/menerjang dalam jumlah besar sekaligus (seperti ombak atau kerumunan fans).',
    contoh1: '波が押し寄せる。\n(Gelombang ombak menerjang dan mengalir deras ke tepian.)',
    contoh2: 'ファンが会場に押し寄せた。\n(Para penggemar berbondong-bondong membanjiri dan mendatangi arena.)'
  },
  {
    id: 'm7h6_10',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '成り立つ',
    furigana: 'なりたつ',
    arti: 'Terwujud / Terdiri dari / Berjalan',
    penjelasan: 'Terwujudnya kesepakatan, terbentuk dari elemen tertentu (terdiri dari), atau berjalannya suatu bisnis/kehidupan.',
    contoh1: '交渉が成り立つ。\n(Negosiasi telah berhasil mencapai kesepakatan / terwujud.)',
    contoh2: 'この会は30人のメンバーから成り立っている。\n(Kelompok/perkumpulan ini terdiri dari 30 orang anggota.)'
  },
  {
    id: 'm7h6_11',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '出直す',
    furigana: 'でなおす',
    arti: 'Datang Lagi / Mulai dari Awal',
    penjelasan: 'Datang kembali ke suatu tempat di lain waktu, atau mengulang/memulai suatu rencana dari nol.',
    contoh1: 'また出直して参ります。\n(Saya akan datang berkunjung kembali di lain waktu.)',
    contoh2: '一から出直す。\n(Memulai kembali segala usaha dan rencana dari awal/nol.)'
  },
  {
    id: 'm7h6_12',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '使いこなす',
    furigana: 'つかいこなす',
    arti: 'Mahir Menggunakan / Menguasai',
    penjelasan: 'Sangat lancar dan mahir menggunakan sesuatu yang rumit, seperti bahasa asing atau teknologi canggih.',
    contoh1: '3ヵ国語を使いこなす。\n(Mahir menguasai dan menggunakan 3 bahasa asing dengan fasih.)',
    contoh2: '最新のパソコンを使いこなす。\n(Mahir dan ahli menggunakan komputer model terbaru beserta fitur-fiturnya.)'
  },
  {
    id: 'm7h6_13',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: 'たどり着く',
    furigana: 'たどりつく',
    arti: 'Akhirnya Sampai / Tiba',
    penjelasan: 'Berhasil tiba di tempat tujuan atau menemukan solusi setelah melewati proses panjang dan bersusah payah.',
    contoh1: '頂上にたどり着く。\n(Berhasil tiba di puncak gunung setelah bersusah payah mendaki.)',
    contoh2: '苦労の末、やっと解決策にたどり着いた。\n(Setelah melalui berbagai rintangan, akhirnya sampai pada solusi yang dicari.)'
  },
  {
    id: 'm7h6_14',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '結び付く',
    furigana: 'むすびつく',
    arti: 'Terhubung / Membuahkan Hasil',
    penjelasan: 'Saling berkaitan erat satu sama lain hingga membuahkan hasil atau dampak tertentu.',
    contoh1: '努力が成功に結び付く。\n(Usaha keras terhubung dan membuahkan kesuksesan yang diidamkan.)',
    contoh2: 'その事件は二人の関係に結びついている。\n(Kejadian tersebut berkaitan erat dengan hubungan mereka berdua.)'
  },
  {
    id: 'm7h6_15',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '着飾る',
    furigana: 'きかざる',
    arti: 'Berdandan / Berpakaian Mewah',
    penjelasan: 'Memakai pakaian yang bagus/mewah dan merias diri secara elegan untuk pergi ke pesta atau acara khusus.',
    contoh1: '着飾ってパーティーに行く。\n(Berdandan dan mengenakan pakaian terbaik untuk pergi ke acara pesta.)',
    contoh2: '彼女は美しく着飾っていた。\n(Dia berdandan dan berpakaian dengan sangat cantik nan elegan.)'
  },
  {
    id: 'm7h6_16',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '乗っ取る',
    furigana: 'のっとる',
    arti: 'Mengambil Alih / Membajak',
    penjelasan: 'Menguasai milik orang lain secara paksa, seperti merebut kekuasaan perusahaan atau membajak pesawat.',
    contoh1: '会社を乗っ取る。\n(Mengambil alih kekuasaan perusahaan milik orang lain secara paksa atau licik.)',
    contoh2: '飛行機を乗っ取る。\n(Membajak sebuah pesawat terbang penumpang.)'
  },
  {
    id: 'm7h6_17',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '消し去る',
    furigana: 'けしさる',
    arti: 'Menghapus Total / Menghilangkan',
    penjelasan: 'Menghapus atau membuang ingatan, noda, atau kenangan masa lalu secara total tanpa sisa.',
    contoh1: '過去を消し去る。\n(Menghapus jejak atau memori masa lalu sepenuhnya.)',
    contoh2: '嫌な記憶を頭から消し去りたい。\n(Saya ingin menghilangkan memori kejadian buruk tersebut dari dalam pikiran saya.)'
  },
  {
    id: 'm7h6_18',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '言い張る',
    furigana: 'いいはる',
    arti: 'Bersikeras / Ngotot',
    penjelasan: 'Keras kepala dan ngotot mempertahankan pendapat sendiri walau mungkin sebenarnya salah.',
    contoh1: '知らないと言い張る。\n(Terus bersikeras dan ngotot mengatakan bahwa dirinya tidak tahu menahu soal itu.)',
    contoh2: '自分が正しいと言い張る。\n(Terus mempertahankan argumen dengan ngotot bahwa pendiriannya yang paling benar.)'
  },

  // --- GAMBAR 2 ---
  {
    id: 'm7h6_19',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '待ち望む',
    furigana: 'まちのぞむ',
    arti: 'Sangat Menantikan / Mendambakan',
    penjelasan: 'Menunggu atau mengharapkan kedatangan seseorang/sesuatu dengan penuh antusias dan harapan besar.',
    contoh1: '再会の日を待ち望む。\n(Sangat menantikan dan mendambakan hari di mana kita bisa berjumpa kembali.)',
    contoh2: '待ち望んでいた子供が生まれた。\n(Anak yang selama ini sangat didamba-dambakan akhirnya lahir ke dunia.)'
  },
  {
    id: 'm7h6_20',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '触れ合う',
    furigana: 'ふれあう',
    arti: 'Saling Bersentuhan / Berinteraksi',
    penjelasan: 'Bersentuhan fisik secara langsung, atau berinteraksi secara emosional sehingga timbul ikatan batin.',
    contoh1: '心が触れ合う。\n(Hati dan perasaan saling bersentuhan, memunculkan komunikasi batin yang kuat.)',
    contoh2: '動物と触れ合う。\n(Berinteraksi dan saling bersentuhan secara langsung dengan hewan-hewan.)'
  },
  {
    id: 'm7h6_21',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '切り替える',
    furigana: 'きりかえる',
    arti: 'Beralih / Mengubah Mindset',
    penjelasan: 'Memindah mode/saklar, atau mengubah fokus pikiran (mindset) dari kegagalan ke hal berikutnya.',
    contoh1: 'スイッチを切り替える。\n(Mengganti atau menekan saklar ke posisi yang berbeda.)',
    contoh2: '頭を切り替えて次の試験に臨む。\n(Beralih pikiran dari kegagalan sebelumnya dan fokus untuk menghadapi ujian berikutnya.)'
  },
  {
    id: 'm7h6_22',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: 'やり遂げる',
    furigana: 'やりとげる',
    arti: 'Menyelesaikan Sampai Tuntas',
    penjelasan: 'Berhasil menuntaskan tugas atau rencana yang sulit dari awal sampai selesai dengan sempurna.',
    contoh1: '計画をやり遂げる。\n(Menyelesaikan dan mengeksekusi rencana tersebut sampai tuntas seratus persen.)',
    contoh2: '困難な仕事を最後までやり遂げた。\n(Telah berhasil menyelesaikan pekerjaan yang rumit dan penuh tantangan hingga akhir.)'
  },
  {
    id: 'm7h6_23',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '備え付ける',
    furigana: 'そなえつける',
    arti: 'Memasang / Melengkapi Fasilitas',
    penjelasan: 'Memasang perabotan atau peralatan (seperti AC atau TV) secara permanen di dalam ruangan.',
    contoh1: '教室にテレビを備え付ける。\n(Memasang serta melengkapi fasilitas televisi di dalam ruang kelas.)',
    contoh2: '各部屋にエアコンが備え付けられている。\n(Mesin pendingin ruangan/AC telah terpasang dan melengkapi setiap kamar.)'
  },
  {
    id: 'm7h6_24',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '呼び止める',
    furigana: 'よびとめる',
    arti: 'Mencegat / Memanggil Berhenti',
    penjelasan: 'Memanggil atau mencegat orang yang sedang lewat/berjalan agar ia berhenti sejenak.',
    contoh1: '見知らぬ人に呼び止められる。\n(Dicegat atau dipanggil paksa untuk berhenti oleh orang yang sama sekali tidak dikenal.)',
    contoh2: '警察に呼び止められた。\n(Diberhentikan atau dicegat oleh petugas polisi di jalan.)'
  },
  {
    id: 'm7h6_25',
    minggu: '7',
    hari: '6',
    kategori: 'kata kerja',
    kanji: '盛り上がる',
    furigana: 'もりあがる',
    arti: 'Menonjol / Menjadi Meriah',
    penjelasan: 'Bagian fisik (seperti otot) membesar/menonjol, atau suasana acara/pesta yang berubah jadi sangat meriah.',
    contoh1: '腕の筋肉が盛り上がる。\n(Otot bicep di lengan membesar dan menonjol terlihat jelas.)',
    contoh2: '宴会が盛り上がる。\n(Suasana pesta perayaan memuncak dan menjadi sangat meriah.)'
  }
];

window.vocabData.push(...kosakata_m7h6);