// Gunakan window.vocabData array agar file JS lain bisa di-push juga nantinya
window.vocabData = window.vocabData || [];

const kosakata_m3h5 = [
  {
    id: 'm3h5_1',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: '至って',
    furigana: 'いたって',
    arti: 'Sangat / Amat',
    penjelasan: 'Digunakan untuk menyatakan sesuatu keadaan yang mencapai tahap atau darjah yang sangat tinggi. Perkataan ini biasanya digunakan dalam konteks yang positif atau untuk menerangkan keadaan normal yang melebihi kebiasaan.',
    contoh1: '母は、至って元気です。\n(Ibu saya amat sihat/berada dalam keadaan yang sangat baik.)',
    contoh2: '彼は至ってまじめな青年だ。\n(Dia adalah seorang pemuda yang sangat serius dan jujur.)'
  },
  {
    id: 'm3h5_2',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'いかにも',
    furigana: 'いかにも',
    arti: 'Memang / Benar-benar / Tipikal',
    penjelasan: 'Digunakan untuk menekankan bahawa sesuatu itu sangat menepati ciri-ciri tertentu atau kelihatan jelas menyerupai sesuatu keadaan. Ia memberi nuansa "sepertimana yang dijangkakan" atau "sangat tipikal".',
    contoh1: '社長の考えはいかにも日本的だ。\n(Cara pemikiran presiden memang sangat tipikal gaya Jepun.)',
    contoh2: '彼はいかにも学者らしい服装をしている。\n(Pakaiannya benar-benar menampakkan ciri khas seorang cendekiawan.)'
  },
  {
    id: 'm3h5_3',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'いかに',
    furigana: 'いかに',
    arti: 'Walau betapa (sekalipun) / Bagaimana',
    penjelasan: 'Biasanya digunakan bersama dengan bentuk "~ても" (walaupun) untuk menunjukkan kesia-siaan suatu usaha tanpa mengira betapa kuatnya tindakan tersebut dilakukan. Membawa maksud yang sama dengan "どれほど" (sejauh mana/betapa banyak).',
    contoh1: 'いかに（＝どれほど）努力してもできないだろう。\n(Walau betapa kuat saya berusaha sekalipun, saya mungkin tidak akan berjaya.)',
    contoh2: 'いかに困難な状況でも諦めない。\n(Walau betapa sukarnya keadaan sekalipun, saya tidak akan berputus asa.)'
  },
  {
    id: 'm3h5_4',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'いやに',
    furigana: 'いやに',
    arti: 'Sangat (secara aneh) / Terlalu',
    penjelasan: 'Menggambarkan keadaan yang berbeza secara ketara daripada kebiasaan, sehingga dirasakan agak aneh, pelik, atau luar biasa oleh penutur.',
    contoh1: '今日はいやに暑い。\n(Hari ini sangat panas secara luar biasa berbanding biasa.)',
    contoh2: '子どもたちがいやにおとなしい。\n(Kanak-kanak itu sangat pendiam, sungguh pelik/aneh.)'
  },
  {
    id: 'm3h5_5',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'さも',
    furigana: 'さも',
    arti: 'Seolah-olah / Benar-benar',
    penjelasan: 'Digunakan untuk menggambarkan perbuatan atau ekspresi seseorang yang jelas menunjukkan sesuatu emosi atau keadaan yang sangat nyata (mirip dengan いかにも). Kerap kali diekspresikan dengan kata "～そうに". Boleh juga bermaksud ungkapan "benar juga" (さもありなん).',
    contoh1: '彼はさも（＝いかにも）うれしそうに笑った。\n(Dia tersenyum gembira, seolah-olah benar-benar rasa sangat puas hati.)',
    contoh2: 'さも知っているかのように話す。\n(Dia bercakap seolah-olah dia benar-benar mengetahui semua tentang hal itu.)'
  },
  {
    id: 'm3h5_6',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: '何より',
    furigana: 'なにより',
    arti: 'Lebih daripada segalanya / Paling',
    penjelasan: 'Satu frasa yang digunakan untuk menyatakan bahawa sesuatu perkara itu adalah yang terbaik, paling penting, atau paling menggembirakan tanpa tandingan berbanding dengan perkara-perkara lain.',
    contoh1: '合格して何よりうれしい。\n(Saya paling gembira kerana lulus, lebih daripada perkara yang lain.)',
    contoh2: 'あなたが無事で何よりです。\n(Keselamatan awak adalah yang paling penting lebih daripada segalanya.)'
  },
  {
    id: 'm3h5_7',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'とりわけ',
    furigana: 'とりわけ',
    arti: 'Terutamanya / Khususnya',
    penjelasan: 'Perkataan ini memberikan penekanan kepada satu perkara tertentu yang sangat menonjol jika dibandingkan di antara banyak perkara lain dalam kategori yang sama. Maknanya bersinonim dengan "特に" (tokuni).',
    contoh1: 'とりわけ（＝特に）ビールが好きだ。\n(Saya suka minuman keras, tetapi saya terutamanya sangat suka bir.)',
    contoh2: '今年の夏はとりわけ暑い。\n(Musim panas tahun ini terutamanya sangat panas berbanding tahun-tahun lepas.)'
  },
  {
    id: 'm3h5_8',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'ことに',
    furigana: 'ことに',
    arti: 'Terutama sekali / Khususnya',
    penjelasan: 'Digunakan untuk menunjukkan bahawa sesuatu hal adalah sangat luar biasa dan berada pada tahap yang paling ketara di antara yang lain. Mempunyai maksud penekanan yang serupa dengan "特に" atau "とりわけ".',
    contoh1: 'この小説はことに（＝特に、とりわけ）面白い。\n(Novel ini terutama sekali sangat menarik jalan ceritanya.)',
    contoh2: '彼女はことに語学に優れている。\n(Dia sangat cemerlang terutama sekali di dalam bidang bahasa.)'
  },
  {
    id: 'm3h5_9',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'さぞ / さぞかし',
    furigana: 'さぞ / さぞかし',
    arti: 'Pastinya / Tentu sekali',
    penjelasan: 'Keterangan yang digunakan untuk membuat kesimpulan, tekaan, atau untuk bersimpati dengan situasi dan perasaan seseorang dengan keyakinan yang tinggi. Pada kebiasaannya diletakkan bersama imbuhan tekaan di hujung ayat seperti "～だろう" atau "～でしょう".',
    contoh1: 'ご両親はさぞ（かし）お喜びでしょう。\n(Ibu bapa kamu pastinya akan sangat bergembira mendengarnya.)',
    contoh2: '長い旅で、さぞお疲れになったことでしょう。\n(Perjalanan yang jauh, anda tentu sekali berasa sangat penat.)'
  },
  {
    id: 'm3h5_10',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'よほど / よっぽど',
    furigana: 'よほど / よっぽど',
    arti: 'Sangat (ketara) / Hampir-hampir',
    penjelasan: 'Membawa dua peranan: yang pertama menunjukkan kualiti/keadaan yang sangat tinggi hingga melebihi tahap biasa. Yang kedua menyatakan bahawa niat seseorang hampir sahaja diterjemahkan ke dalam bentuk perbuatan ekstrem ("hampir-hampir sahaja"). "よっぽど" adalah varian percakapan santai.',
    contoh1: 'あの荷物はよほど重いようだ。\n(Bungkusan/bagasi itu kelihatan sangat berat sekali.)',
    contoh2: 'よっぽど国に帰ろうかと思った。\n(Saya hampir-hampir terfikir untuk berkemas dan pulang ke negara asal.)'
  },
  {
    id: 'm3h5_11',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'なおさら',
    furigana: 'なおさら',
    arti: 'Lebih-lebih lagi / Semakin',
    penjelasan: 'Digunakan untuk menunjukkan keadaan sesuatu hal yang sudah sedia wujud kini bertambah kuat, menjadi lebih ketara, atau semakin parah dengan wujudnya situasi yang menyokong pertambahan itu. Mirip dengan "ますます".',
    contoh1: 'だめだと言われると、なおさら（＝ますます）やりたくなる。\n(Apabila diberitahu ianya tidak dibenarkan, saya jadi lebih-lebih lagi ingin melakukannya.)',
    contoh2: '夜になって雨が降り、道はなおさら悪くなった。\n(Hujan turun menjelang malam, dan laluan tersebut menjadi bertambah teruk/semakin berbahaya.)'
  },
  {
    id: 'm3h5_12',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'まさしく',
    furigana: 'まさしく',
    arti: 'Tepat sekali / Sememangnya',
    penjelasan: 'Dipakai semasa penutur mempunyai tahap keyakinan mutlak bahawa fakta tersebut adalah benar, asli dan mustahil untuk disangkal oleh mana-mana pihak.',
    contoh1: 'これはまさしく本物のダイヤです。\n(Ini sememangnya adalah permata berlian yang asli tanpa keraguan.)',
    contoh2: 'その時の状況は、まさしく地獄のようだった。\n(Keadaan pada masa kejadian itu, tepat sekali kelihatan seperti suasana di neraka.)'
  },
  {
    id: 'm3h5_13',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'まして',
    furigana: 'まして',
    arti: 'Apatah lagi / Apalagi',
    penjelasan: 'Struktur logik yang digunakan untuk menekankan bahawa sekiranya suatu situasi A (yang lebih ringan/mudah) pun tidak mungkin berlaku, maka apatah lagi situasi B (yang jauh lebih sukar atau lebih luar biasa).',
    contoh1: '大人でもできないのだから、まして子どもには無理だ。\n(Golongan dewasa pun tidak berupaya menyelesaikannya, apatah lagi kanak-kanak, sudah pasti mustahil bagi mereka.)',
    contoh2: '英語も話せないのに、ましてフランス語などわかるはずがない。\n(Bahasa Inggeris pun saya tidak fasih, apatah lagi bahasa Perancis, sudah tentu saya tidak faham langsung.)'
  },
  {
    id: 'm3h5_14',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'やけに / やたらに / やたらと',
    furigana: 'やけに / やたらに / やたらと',
    arti: 'Terlalu sangat / Keterlaluan / Tanpa had',
    penjelasan: 'Merujuk kepada sesuatu tindakan, tahap perasaan, atau kuantiti yang melampaui batas kewarasan dan berlaku secara berlebihan tanpa ada sebarang sekatan. Selalunya ia melambangkan rasa kurang selesa penutur.',
    contoh1: '今日はやけにのどが渇くなあ。\n(Entah mengapa saya berasa sangat haus dengan keterlaluan hari ini.)',
    contoh2: '最近、やたらに（やたらと）寝汗をかく。\n(Mutakhir ini, saya selalu berpeluh tanpa kawalan semasa sedang tidur lelap.)'
  },
  {
    id: 'm3h5_15',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: '誠に',
    furigana: 'まことに',
    arti: 'Sesungguhnya / Amat sangat',
    penjelasan: 'Kosa kata peringkat sangat formal dan hormat yang selalunya digunakan untuk memohon maaf secara tulus, menyatakan rasa penghargaan yang mendalam, atau menegaskan fakta. Amat lazim dalam surat-menyurat perniagaan dan ucapan rasmi.',
    contoh1: 'ご迷惑をおかけして、誠に申し訳ありません。\n(Saya sesungguhnya memohon jutaan kemaafan atas segala kesulitan yang timbul.)',
    contoh2: '本日はご来場いただき、誠にありがとうございます。\n(Terima kasih yang amat sangat kerana sudi hadir pada hari ini.)'
  },
  {
    id: 'm3h5_16',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'もっぱら',
    furigana: 'もっぱら',
    arti: 'Sepenuhnya / Hanya tertumpu kepada',
    penjelasan: 'Digunakan untuk menunjukkan tindakan menumpukan sepenuh dedikasi, minat, masa, atau tenaga hanya ke arah satu tujuan atau perkara sahaja tanpa mempedulikan pelbagai hal yang lain.',
    contoh1: '休日はもっぱらゴルフをしている。\n(Pada hari cuti rasmi, saya menghabiskan keseluruhan masa tertumpu hanya dengan bermain golf sahaja.)',
    contoh2: '彼はもっぱら研究に打ち込んでいる。\n(Lelaki tersebut kini mendedikasikan sepenuh masanya hanya untuk melaksanakan kajian penyelidikannya.)'
  },
  {
    id: 'm3h5_17',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'ひたすら',
    furigana: 'ひたすら',
    arti: 'Dengan tekun / Semata-mata secara berterusan',
    penjelasan: 'Menggambarkan tumpuan atau dedikasi yang utuh dengan melakukan perbuatan tersebut secara berterusan, tidak putus-putus, dan bersungguh-sungguh walaupun perlu mengabaikan kehendak lain.',
    contoh1: 'ゴールを目指してひたすら走り続ける。\n(Saya terus-menerus berlari dengan tekun menuju terus ke arah garisan penamat.)',
    contoh2: '妻の回復をひたすら祈った。\n(Saya mendoakan kesembuhan isteri saya secara semata-mata dengan penuh pengharapan yang berterusan.)'
  },
  {
    id: 'm3h5_18',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'もろに',
    furigana: 'もろに',
    arti: 'Secara langsung / Tepat mengena',
    penjelasan: 'Membawa makna sebarang jenis tindakan atau impak yang menimpa sasaran dengan secara berdepan, secara langsung dan sepenuhnya tanpa dapat dielakkan atau ditapis. Kerap digunakan bila melibatkan kerosakan dan hentakan fizikal.',
    contoh1: 'もろに地震の被害を受けた。\n(Pihak kami telah terjejas dengan skala penuh secara langsung akibat kerosakan struktur dari gempa bumi tersebut.)',
    contoh2: 'ボールがもろに顔に当たった。\n(Bola liar itu telah mengena dan menghentam wajahnya tepat secara langsung.)'
  },
  {
    id: 'm3h5_19',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'たかが',
    furigana: 'たかが',
    arti: 'Hanya sekadar / Takat itu sahaja',
    penjelasan: 'Diletakkan sebelum sesuatu nilai untuk memperkecilkan atau merendahkannya supaya pendengar tidak perlu mengendahkannya dengan sangat serius. Membawa maksud nilai atau tahap perbuatan itu tidak seberapa dan langsung tidak penting.',
    contoh1: 'たかが一度の失敗で、あきらめるな。\n(Janganlah engkau berputus asa hanya sekadar disebabkan oleh satu kegagalan sahaja.)',
    contoh2: 'たかが子どもの言うことだ、気にしないで。\n(Itu hanyalah sekadar luahan anak kecil takat itu sahaja, jangan ambil peduli akan hal itu.)'
  },
  {
    id: 'm3h5_20',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'てんで',
    furigana: 'てんで',
    arti: 'Sama sekali tidak',
    penjelasan: 'Menyatakan penafian secara keras dan mutlak bermaksud "tidak wujud langsung". Penutur wajib memasangkan perkataan ini dengan unsur dan kata-kata ekspresi negatif di dalam sambungan ayat. Semaksud dengan "全く～ない".',
    contoh1: 'その話はてんで面白くない。\n(Pengkisahan cerita tersebut adalah sama sekali tidak menarik minat orang.)',
    contoh2: '相手のチームは強すぎて、てんで勝負にならない。\n(Pasukan pesaing terlampau kuat, ia sama sekali tidak akan mendatangkan perlawanan yang adil buat kita.)'
  },
  {
    id: 'm3h5_21',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'むろん',
    furigana: 'むろん',
    arti: 'Sudah tentu / Sememangnya',
    penjelasan: 'Mengekspresikan persetujuan atau menyampaikan suatu fakta ketetapan yang sudah sangat jelas sehingga rasanya tidak perlu dikupas mahupun didebatkan secara logik. Bunyinya sangat rasmi, dan ia bersinonim secara langsung dengan "もちろん" atau "言うまでもなく".',
    contoh1: 'むろん（＝もちろん、言うまでもなく）賛成だ。\n(Sudah tentulah saya akan menyatakan persetujuan secara penuh akan hal itu.)',
    contoh2: 'むろん、私に異議はありません。\n(Sememangnya sudah pasti, saya tidak mempunyai apa-apa bentuk pertikaian untuk dibangkitkan.)'
  },
  {
    id: 'm3h5_22',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'なんと / なんて',
    furigana: 'なんと / なんて',
    arti: 'Betapa / Alangkah',
    penjelasan: 'Berperanan penting sebagai penanda emosi tatkala menzahirkan rasa kekaguman, keluhan mengejut, atau kehairanan terhadap intensiti dan tahap sesuatu keadaan. Biasanya merangkaikan dirinya bersama-sama dengan kata adjektif atau kata seru.',
    contoh1: 'なんときれいな人だろう。\n(Wah, alangkah menawan dan cantiknya keperibadian orang ini di mata saya.)',
    contoh2: 'なんてひどい天気だ。\n(Aduhai, betapa teruk dan buruknya iklim cuaca di luar sana ketika ini.)'
  },
  {
    id: 'm3h5_23',
    minggu: '3',
    hari: '5',
    kategori: 'kata keterangan',
    kanji: '残らず',
    furigana: 'のこらず',
    arti: 'Tanpa berbaki / Kesemuanya sekali',
    penjelasan: 'Menunjuk isyarat perbuatan menyudahkan sesuatu keadaan ataupun hal objek secara keseluruhan 100 peratus dan rata hingga ke dasar, tanpa pernah meninggalkan walau cebisan kecil atau sisa sedikit pun yang berbaki.',
    contoh1: '知っていることを残らず話す。\n(Saya akan menyalurkan dan menceritakan kesemuanya apa yang saya ketahui tanpa berbaki sedikit pun.)',
    contoh2: 'お皿の料理を残らず食べた。\n(Dia menyantap kesemua hidangan makanan di atas pinggannya itu licin tanpa berbaki langsung.)'
  }
];

window.vocabData.push(...kosakata_m3h5);