// Gunakan window.vocabData array agar file JS lain bisa di-push juga nantinya
window.vocabData = window.vocabData || [];

const kosakata_m3h5 = [
  {
    id: 'm3h5_1',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: '至って',
    furigana: 'いたって',
    arti: 'Sangat / Amat',
    penjelasan: 'Dipakai untuk menunjukkan kondisi yang sangat tinggi atau melebihi batas normal (biasanya untuk hal yang positif).',
    contoh1: '母は、至って元気です。\n(Ibu saya amat sihat.)',
    contoh2: '彼は至ってまじめな青年だ。\n(Dia adalah pemuda yang sangat serius.)'
  },
  {
    id: 'm3h5_2',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'いかにも',
    furigana: 'いかにも',
    arti: 'Memang / Benar-benar / Khas',
    penjelasan: 'Dipakai untuk menunjukkan sesuatu yang sangat cocok, pas, atau sesuai dengan ciri-ciri aslinya (seperti yang dibayangkan).',
    contoh1: '社長の考えはいかにも日本的だ。\n(Cara pemikiran bos benar-benar gaya orang Jepang.)',
    contoh2: '彼はいかにも学者らしい服装をしている。\n(Pakaiannya benar-benar mirip seorang ilmuwan.)'
  },
  {
    id: 'm3h5_3',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'いかに',
    furigana: 'いかに',
    arti: 'Walau betapa pun / Bagaimana',
    penjelasan: 'Biasanya dipakai bersama bentuk "~ても" (walaupun) untuk menyatakan "meskipun sudah berusaha sekuat tenaga, hasilnya tetap sama".',
    contoh1: 'いかに努力してもできないだろう。\n(Walau betapa pun saya berusaha, mungkin tidak akan bisa.)',
    contoh2: 'いかに困難な状況でも諦めない。\n(Walau sesulit apa pun situasinya, saya tidak akan menyerah.)'
  },
  {
    id: 'm3h5_4',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'いやに',
    furigana: 'いやに',
    arti: 'Terlalu / Sangat (terasa aneh)',
    penjelasan: 'Dipakai saat sesuatu hal terasa sangat berlebihan dari biasanya, sehingga membuat kita merasa agak aneh atau heran.',
    contoh1: '今日はいやに暑い。\n(Hari ini panasnya terasa aneh/tidak seperti biasanya.)',
    contoh2: '子どもたちがいやにおとなしい。\n(Anak-anak sangat pendiam, tumben sekali.)'
  },
  {
    id: 'm3h5_5',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'さも',
    furigana: 'さも',
    arti: 'Seolah-olah / Seakan-akan',
    penjelasan: 'Dipakai untuk menunjukkan sikap atau ekspresi seseorang yang kelihatan sangat menjiwai sesuatu hal (biasanya diikuti pola "~そうに").',
    contoh1: '彼はさもうれしそうに笑った。\n(Dia tersenyum gembira seolah-olah sangat puas.)',
    contoh2: 'さも知っているかのように話す。\n(Dia berbicara seakan-akan dia tahu segalanya.)'
  },
  {
    id: 'm3h5_6',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: '何より',
    furigana: 'なにより',
    arti: 'Paling utama / Lebih dari segalanya',
    penjelasan: 'Menyatakan bahwa sesuatu hal adalah yang paling penting, paling membahagiakan, atau paling utama dibanding yang lain.',
    contoh1: '合格して何よりうれしい。\n(Lulus adalah hal yang paling membuatku senang.)',
    contoh2: 'あなたが無事で何よりです。\n(Kamu selamat adalah hal yang paling penting.)'
  },
  {
    id: 'm3h5_7',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'とりわけ',
    furigana: 'とりわけ',
    arti: 'Terutama / Khususnya',
    penjelasan: 'Dipakai untuk memilih satu hal yang paling menonjol atau paling penting di antara banyak hal lainnya.',
    contoh1: 'とりわけビールが好きだ。\n(Saya suka minuman, tapi terutama paling suka bir.)',
    contoh2: '今年の夏はとりわけ暑い。\n(Musim panas tahun ini terasa sangat panas dibanding biasanya.)'
  },
  {
    id: 'm3h5_8',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'ことに',
    furigana: 'ことに',
    arti: 'Terutama sekali / Khususnya',
    penjelasan: 'Hampir sama dengan "とりわけ" atau "特に", dipakai untuk menekankan kondisi yang paling mencolok.',
    contoh1: 'この小説はことに面白い。\n(Novel ini terutama sekali sangat menarik.)',
    contoh2: '彼女はことに語学に優れている。\n(Dia sangat unggul, terutama dalam bidang bahasa.)'
  },
  {
    id: 'm3h5_9',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'さぞ / さぞかし',
    furigana: 'さぞ / さぞかし',
    arti: 'Pasti / Tentu saja',
    penjelasan: 'Dipakai untuk menebak atau membayangkan perasaan orang lain dengan tingkat keyakinan yang tinggi (biasanya diakhiri "~だろう").',
    contoh1: 'ご両親はさぞお喜びでしょう。\n(Orang tuamu pasti akan sangat gembira.)',
    contoh2: '長い旅で、さぞお疲れになったことでしょう。\n(Perjalanan jauh, kamu pasti sangat lelah ya.)'
  },
  {
    id: 'm3h5_10',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'よほど / よっぽど',
    furigana: 'よほど / よっぽど',
    arti: 'Sangat sekali / Hampir saja',
    penjelasan: 'Menyatakan tingkat kondisi yang sangat kuat, atau bermaksud "hampir saja melakukan sesuatu". "よっぽど" bentuk santainya.',
    contoh1: 'あの荷物はよほど重いようだ。\n(Barang itu kelihatannya berat sekali.)',
    contoh2: 'よっぽど国に帰ろうかと思った。\n(Saya tadi hampir-hampir berpikir mau pulang kampung saja.)'
  },
  {
    id: 'm3h5_11',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'なおさら',
    furigana: 'なおさら',
    arti: 'Semakin / Lebih-lebih lagi',
    penjelasan: 'Dipakai saat suatu keadaan sudah parah/bagus, lalu ditambah situasi lain yang membuat kondisinya menjadi semakin kuat.',
    contoh1: 'だめだと言われると、なおさらやりたくなる。\n(Kalau dibilang jangan, malah jadi semakin ingin melakukannya.)',
    contoh2: '雨が降り、道はなおさら悪くなった。\n(Hujan turun, jalannya jadi semakin bertambah parah.)'
  },
  {
    id: 'm3h5_12',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'まさしく',
    furigana: 'まさしく',
    arti: 'Benar-benar / Tepat sekali',
    penjelasan: 'Dipakai saat kita merasa 100% yakin bahwa suatu hal adalah fakta yang asli dan tidak bisa dibantah.',
    contoh1: 'これはまさしく本物のダイヤです。\n(Ini benar-benar berlian asli.)',
    contoh2: 'その時の状況は、まさしく地獄のようだった。\n(Situasi waktu itu benar-benar seperti di neraka.)'
  },
  {
    id: 'm3h5_13',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'まして',
    furigana: 'まして',
    arti: 'Apatah lagi / Apalagi',
    penjelasan: 'Rumus logika: Kalau hal yang mudah saja tidak bisa, "apalagi" hal yang jauh lebih susah, sudah pasti tidak bisa.',
    contoh1: '大人でもできないのだから、まして子どもには無理だ。\n(Orang dewasa saja tidak bisa, apalagi anak-anak, pasti tidak mampu.)',
    contoh2: '英語も話せないのに、ましてフランス語などわかるはずがない。\n(Bahasa Inggris saja tidak bisa, apalagi bahasa Prancis.)'
  },
  {
    id: 'm3h5_14',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'やけに / やたらに / やたらと',
    furigana: 'やけに / やたらに / やたらと',
    arti: 'Terlalu berlebihan / Sembarangan',
    penjelasan: 'Menunjukkan sesuatu yang terjadi secara berlebihan, kelewatan batas, atau tidak wajar (biasanya bernada negatif).',
    contoh1: '今日はやけにのどが渇く。\n(Hari ini tenggorokan terasa haus sekali secara tidak wajar.)',
    contoh2: '最近、やたらに寝汗をかく。\n(Akhir-akhir ini saya sering keluar keringat dingin saat tidur.)'
  },
  {
    id: 'm3h5_15',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: '誠に',
    furigana: 'まことを / まことに',
    arti: 'Sesungguhnya / Benar-benar (Sopan)',
    penjelasan: 'Bentuk sangat sopan untuk meminta maaf, berterima kasih, atau menegaskan fakta. Sering dipakai dalam dunia kerja.',
    contoh1: 'ご迷惑をおかけして、誠に申し訳ありません。\n(Saya benar-benar memohon maaf atas kerepotan ini.)',
    contoh2: '本日はご来場いただき、誠にありがとうございます。\n(Terima kasih banyak atas kedatangan Anda hari ini.)'
  },
  {
    id: 'm3h5_16',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'もっぱら',
    furigana: 'もっぱら',
    arti: 'Sepenuhnya / Hanya berfokus pada',
    penjelasan: 'Dipakai saat seseorang mendedikasikan seluruh waktu atau usahanya hanya untuk satu hal tertentu saja.',
    contoh1: '休日はもっぱらゴルフをしている。\n(Hari libur saya habiskan sepenuhnya untuk main golf.)',
    contoh2: '彼はもっぱら研究に打ち込んでいる。\n(Dia fokus sepenuhnya menekuni penelitian.)'
  },
  {
    id: 'm3h5_17',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'ひたすら',
    furigana: 'ひたすら',
    arti: 'Dengan tekun / Terus-menerus',
    penjelasan: 'Melakukan sesuatu secara fokus, terus-menerus, dan bersungguh-sungguh tanpa memikirkan hal lain.',
    contoh1: 'ゴールを目指してひたすら走り続ける。\n(Terus berlari dengan tekun menuju garis akhir.)',
    contoh2: '妻の回復をひたすら祈った。\n(Saya terus-menerus mendoakan kesembuhan istri saya.)'
  },
  {
    id: 'm3h5_18',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'もろに',
    furigana: 'もろに',
    arti: 'Secara langsung / Telak',
    penjelasan: 'Dipakai saat suatu hantaman, dampak, atau masalah mengenai sasaran secara langsung tanpa ada halang rintang.',
    contoh1: 'もろに地震の被害を受けた。\n(Kami terkena dampak gempa bumi secara langsung.)',
    contoh2: 'ボールがもろに顔に当たった。\n(Bola itu mengenai wajahnya secara telak.)'
  },
  {
    id: 'm3h5_19',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'たかが',
    furigana: 'たかが',
    arti: 'Hanya sekadar / Tidak seberapa',
    penjelasan: 'Dipakai untuk meremehkan atau mengecilkan suatu masalah agar orang lain tidak perlu terlalu serius menanggapinya.',
    contoh1: 'たかが一度の失敗で、あきらめるな。\n(Jangan menyerah hanya karena satu kegagalan kecil.)',
    contoh2: 'たかが子どもの言うことだ、気にしないで。\n(Itu cuma omongan anak kecil, jangan dipikirkan.)'
  },
  {
    id: 'm3h5_20',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'てんで',
    furigana: 'てんで',
    arti: 'Sama sekali tidak',
    penjelasan: 'Menyatakan penolakan atau hal negatif secara mutlak. Harus selalu dipasangkan dengan bentuk negatif di ujung kalimat.',
    contoh1: 'その話はてんで面白くない。\n(Cerita itu sama sekali tidak menarik.)',
    contoh2: '相手のチームは強すぎて、てんで勝負にならない。\n(Lawannya terlalu kuat, sama sekali tidak bisa dilawan.)'
  },
  {
    id: 'm3h5_21',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'むろん',
    furigana: 'むろん',
    arti: 'Tentu saja / Sudah pasti',
    penjelasan: 'Menyatakan hal yang sudah sangat jelas kebenarannya sehingga tidak perlu diperdebatkan lagi (sama seperti "もちろん").',
    contoh1: 'むろん賛成だ。\n(Tentu saja saya setuju.)',
    contoh2: 'むろん、私に異議はありません。\n(Tentu saja, saya tidak punya keberatan.)'
  },
  {
    id: 'm3h5_22',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: 'なんと / なんて',
    furigana: 'なんと / なんて',
    arti: 'Betapa / Alangkah',
    penjelasan: 'Kata seru untuk mengungkapkan rasa kagum, kaget, atau takjub terhadap suatu kondisi.',
    contoh1: 'なんときれいな人だろう。\n(Betapa cantiknya orang ini.)',
    contoh2: 'なんてひどい天気だ。\n(Alangkah buruknya cuaca ini.)'
  },
  {
    id: 'm3h5_23',
    minggu: '3',
    hari: '5',
    kategori: 'Kata Keterangan',
    kanji: '残らず',
    furigana: 'のこらず',
    arti: 'Tanpa sisa / Semuanya',
    penjelasan: 'Menyatakan bahwa suatu hal dihabiskan atau diambil 100% tanpa ada yang tersisa sedikit pun.',
    contoh1: '知っていることを残らず話す。\n(Saya akan ceritakan semua yang saya tahu tanpa ada yang disembunyikan.)',
    contoh2: 'お皿の料理を残らず食べた。\n(Dia makan semua makanan di piring sampai habis tak bersisa.)'
  }
];

window.vocabData.push(...kosakata_m3h5);