// Gunakan window.vocabData array agar file JS lain bisa di-push juga nantinya
window.vocabData = window.vocabData || [];

const kosakata_m3h6 = [
  {
    id: 'm3h6_1',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'あいにく',
    furigana: 'あいにく',
    arti: 'Sayangnya / Kebetulan tidak tepat',
    penjelasan: 'Dipakai saat ada situasi buruk atau waktu tidak pas yang membuat rencana atau harapan tidak terwujud.',
    contoh1: 'あいにく留守にしています。\n(Sayangnya dia sedang tidak ada di rumah.)',
    contoh2: 'その日はあいにく予定が入っております。\n(Sayang sekali, pada hari itu saya sudah ada jadwal lain.)'
  },
  {
    id: 'm3h6_2',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '案の定',
    furigana: 'あんのじょう',
    arti: 'Sesuai dugaan / Seperti perkiraan',
    penjelasan: 'Menunjukkan kejadian yang benar-benar persis seperti tebakan atau firasat sebelumnya (biasanya untuk hal negatif).',
    contoh1: 'ダメだと思っていたら、案の定不合格だった。\n(Kira bakal gagal, dan sesuai dugaan ternyata tidak lulus.)',
    contoh2: '空が暗くなり、案の定雨が降ってきた。\n(Langit mendung, dan benar saja hujan turun.)'
  },
  {
    id: 'm3h6_3',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '敢えて',
    furigana: 'あえて',
    arti: 'Sengaja / Memberanikan diri',
    penjelasan: 'Melakukan sesuatu secara sengaja meskipun tahu berisiko atau sulit, demi mencapai tujuan tertentu.',
    contoh1: '負けるとわかっているが、敢えて挑戦した。\n(Meski tahu akan kalah, saya sengaja mencobanya.)',
    contoh2: 'みんなのために、敢えて厳しいことを言う。\n(Demi kebaikan bersama, saya sengaja bicara tegas.)'
  },
  {
    id: 'm3h6_4',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '強いて',
    furigana: 'しいて',
    arti: 'Jika dipaksa / Kalau terpaksa',
    penjelasan: 'Dipakai saat seseorang harus memilih atau melakukan sesuatu dalam kondisi terpaksa atau didesak.',
    contoh1: '強いてそれを変更しろとは言わない。\n(Saya tidak memaksa untuk mengubah hal itu.)',
    contoh2: '強いて言えば、こっちのほうがましだ。\n(Kalau terpaksa harus memilih, yang ini sedikit lebih baik.)'
  },
  {
    id: 'm3h6_5',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '自ずから / 自ずと',
    furigana: 'おのずから / おのずと',
    arti: 'Dengan sendirinya / Secara alami',
    penjelasan: 'Menandakan suatu hal yang terjadi atau terselesaikan secara alami seiring waktu berjalan tanpa dipaksa.',
    contoh1: '努力すれば自ずから道は開ける。\n(Jika terus berusaha, jalan akan terbuka dengan sendirinya.)',
    contoh2: '大人になれば自ずとわかるよ。\n(Kalau sudah dewasa nanti, kamu akan mengerti sendiri.)'
  },
  {
    id: 'm3h6_6',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '自ら',
    furigana: 'みずから',
    arti: 'Sendiri / Atas inisiatif sendiri',
    penjelasan: 'Tindakan yang dilakukan secara langsung oleh diri sendiri tanpa disuruh atau dipaksa orang lain.',
    contoh1: '自ら進んで勉強する。\n(Belajar atas inisiatif sendiri secara proaktif.)',
    contoh2: '社長が自ら現場を視察する。\n(Direktur turun langsung meninjau lapangan secara pribadi.)'
  },
  {
    id: 'm3h6_7',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'とかく',
    furigana: 'とかく',
    arti: 'Cenderung / Sering kali',
    penjelasan: 'Menunjukkan kecenderungan kuat bahwa suatu hal yang kurang baik sering terjadi.',
    contoh1: '寒くなると、とかく遅刻者が多くなる。\n(Saat cuaca dingin, orang cenderung sering terlambat.)',
    contoh2: '人はとかく他人の欠点に気づきやすい。\n(Manusia sering kali lebih mudah melihat kekurangan orang lain.)'
  },
  {
    id: 'm3h6_8',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'なるたけ',
    furigana: 'なるたけ',
    arti: 'Sebisa mungkin / Sedapat mungkin',
    penjelasan: 'Bentuk santai yang sama artinya dengan "なるべく" (mengusahakan semaksimal mungkin).',
    contoh1: 'なるたけ早く来てください。\n(Tolong datang sebisa mungkin lebih awal.)',
    contoh2: 'なるたけお金を使わないようにしている。\n(Saya berusaha sebisa mungkin tidak boros.)'
  },
  {
    id: 'm3h6_9',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '努めて',
    furigana: 'つとめて',
    arti: 'Berusaha keras (untuk bersikap) / Sebisa mungkin',
    penjelasan: 'Sengaja berusaha sekuat tenaga mengontrol diri atau emosi agar terlihat wajar.',
    contoh1: '努めて冷静にする。\n(Berusaha keras untuk tetap tenang.)',
    contoh2: '悲しかったが、努めて明るく振る舞った。\n(Meskipun sedih, saya berusaha bersikap ceria.)'
  },
  {
    id: 'm3h6_10',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'ひいては',
    furigana: 'ひいては',
    arti: 'Yang pada gilirannya / Berimbas pada',
    penjelasan: 'Menunjukkan bahwa efek dari suatu hal tidak berhenti di situ saja, tapi meluas ke hal yang lebih besar.',
    contoh1: '自分のため、ひいては家族全体の力になる。\n(Untuk diri sendiri, yang pada akhirnya membantu seluruh keluarga.)',
    contoh2: 'この研究は、ひいては人類の未来を救うだろう。\n(Penelitian ini pada akhirnya akan menyelamatkan masa depan manusia.)'
  },
  {
    id: 'm3h6_11',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'もはや～ない',
    furigana: 'もはや～ない',
    arti: 'Sudah tidak (lagi)',
    penjelasan: 'Menegaskan dengan nada pasrah bahwa situasi atau harapan sudah tertutup total.',
    contoh1: 'もはや彼の回復は望めない。\n(Sudah tidak ada harapan lagi untuk kesembuhannya.)',
    contoh2: 'もはや後戻りすることはできない。\n(Sudah tidak bisa lagi untuk mundur atau kembali.)'
  },
  {
    id: 'm3h6_12',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'かえって',
    furigana: 'かえって',
    arti: 'Malah / Sebaliknya',
    penjelasan: 'Situasi ironis di mana niat awal ingin berbuat baik tapi hasilnya malah memperburuk keadaan.',
    contoh1: '近道したら、かえって時間がかかった。\n(Sengaja lewat jalan pintas, tapi nyatanya malah makan waktu lebih lama.)',
    contoh2: '薬を飲んだら、かえって気分が悪くなった。\n(Minum obat, tapi kondisi tubuh malah makin tidak enak.)'
  },
  {
    id: 'm3h6_13',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '取りあえず',
    furigana: 'とりあえず',
    arti: 'Untuk sementara / Terlebih dahulu',
    penjelasan: 'Mengambil langkah awal yang paling mendesak atau paling mudah dilakukan saat ini.',
    contoh1: '取りあえず何か食べよう。\n(Untuk sementara, mari kita makan sesuatu dulu.)',
    contoh2: '取りあえず問題はないだろう。\n(Untuk saat ini sepertinya tidak ada masalah.)'
  },
  {
    id: 'm3h6_14',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'かろうじて',
    furigana: 'かろうじて',
    arti: 'Dengan susah payah / Nyaris / Pas-pasan',
    penjelasan: 'Berhasil melewati situasi kritis atau nyaris gagal dengan batas waktu/kondisi yang sangat tipis.',
    contoh1: 'かろうじて最終電車に間に合った。\n(Nyaris terlambat, tapi akhirnya sempat mengejar kereta terakhir.)',
    contoh2: 'かろうじて試験に合格した。\n(Berhasil lulus ujian dengan nilai pas-pasan.)'
  },
  {
    id: 'm3h6_15',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'ことごとく',
    furigana: 'ことごとく',
    arti: 'Semuanya / Sama sekali (tanpa sisa)',
    penjelasan: 'Menyatakan bahwa seluruh aspek atau percobaan gagal atau terkena dampak tanpa terkecuali.',
    contoh1: '私の案はことごとく却下された。\n(Ide-ide saya semuanya ditolak mentah-mentah.)',
    contoh2: '予想がことごとく外れた。\n(Tebakan saya meleset semuanya.)'
  },
  {
    id: 'm3h6_16',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'ふんだんに',
    furigana: 'ふんだんに',
    arti: 'Secara melimpah / Sangat banyak',
    penjelasan: 'Ketersediaan atau penggunaan sesuatu dalam jumlah yang sangat berlimpah dan tidak pelit.',
    contoh1: 'イチゴをふんだんに使ったケーキ\n(Kue yang memakai banyak buah stroberi secara melimpah.)',
    contoh2: '自然をふんだんに取り入れた家。\n(Rumah dengan unsur alam yang sangat banyak/asri.)'
  },
  {
    id: 'm3h6_17',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '幸い（に）',
    furigana: 'さいわい（に）',
    arti: 'Untungnya / Syukurlah',
    penjelasan: 'Mengekspresikan rasa lega karena beruntung terhindar dari nasib buruk, atau dipakai untuk memohon kebaikan.',
    contoh1: '事故にあったが、幸いけがはなかった。\n(Kecelakaan terjadi, tapi syukurlah tidak ada yang terluka.)',
    contoh2: 'お返事をいただければ幸いです。\n(Saya akan sangat bersyukur jika Anda sudi membalas.)'
  },
  {
    id: 'm3h6_18',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '現に',
    furigana: 'げんに',
    arti: 'Kenyataannya / Pada kenyataannya',
    penjelasan: 'Membuktikan sesuatu dengan menunjuk langsung pada fakta atau bukti nyata di depan mata.',
    contoh1: '現に、私はそれを見た。\n(Kenyataannya, saya melihatnya dengan mata kepala sendiri.)',
    contoh2: '誰も信じないが、現にその事件は起きた。\n(Mungkin tak ada yang percaya, tapi nyatanya itu terjadi.)'
  },
  {
    id: 'm3h6_19',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'いずれも / いずれにしても',
    furigana: 'いずれも / いずれにしても',
    arti: 'Bagaimanapun juga / Apapun pilihannya',
    penjelasan: 'Menyimpulkan bahwa dari beberapa pilihan yang ada, hasil akhirnya tetap sama saja.',
    contoh1: 'いずれにしても、高くて買えない。\n(Bagaimanapun juga, harganya terlalu mahal dan tidak terbeli.)',
    contoh2: 'いずれまた来ます。\n(Suatu saat nanti saya pasti akan datang lagi.)'
  },
  {
    id: 'm3h6_20',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '仮に',
    furigana: 'かりに',
    arti: 'Seandainya / Misalkan',
    penjelasan: 'Dipakai di awal kalimat untuk membuat pengandaian atau hipotesis tentang sesuatu.',
    contoh1: '仮に試験に落ちたら、どうしますか。\n(Seandainya kamu gagal ujian, apa yang akan dilakukan?)',
    contoh2: '仮にそれが事実だとしても、諦めない。\n(Kalaupun itu benar faktanya, saya tidak akan menyerah.)'
  },
  {
    id: 'm3h6_21',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'ひょっとすると / ひょっとして',
    furigana: 'ひょっとすると / ひょっとして',
    arti: 'Mungkin saja / Jangan-jangan',
    penjelasan: 'Menyadari suatu kemungkinan kecil yang tidak disangka-sangka (sering dipasangkan dengan "かもしれない").',
    contoh1: 'ひょっとすると彼の話はうそかもしれない。\n(Jangan-jangan ceritanya itu cuma kebohongan.)',
    contoh2: 'ひょっとして、あの人は山田さんですか。\n(Jangan-jangan, orang itu adalah Pak Yamada?)'
  },
  {
    id: 'm3h6_22',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'もしかして / もしかすると',
    furigana: 'もしかして / もしかすると',
    arti: 'Mungkinkah / Jangan-jangan',
    penjelasan: 'Sama seperti "hyottoshite", dipakai untuk menebak atau meminta konfirmasi atas suatu kecurigaan.',
    contoh1: 'もしかして、あなたは、田中さん？\n(Mungkinkah, Anda ini Pak Tanaka?)',
    contoh2: 'もしかすると、明日は雪が降るかもしれない。\n(Mungkin saja besok akan turun salju.)'
  },
  {
    id: 'm3h6_23',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'どうにか',
    furigana: 'どうにか',
    arti: 'Entah bagaimana / Bagaimanapun caranya',
    penjelasan: 'Tekad untuk mengusahakan sesuatu sampai berhasil, atau rasa lega karena masalah berhasil dilewati.',
    contoh1: 'どうにかあの会社に就職したい。\n(Bagaimanapun caranya, saya ingin bekerja di perusahaan itu.)',
    contoh2: 'どうにか大学は卒業した。\n(Entah bagaimana caranya, akhirnya saya lulus kuliah juga.)'
  },
  {
    id: 'm3h6_24',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'どうやら',
    furigana: 'どうやら',
    arti: 'Sepertinya / Agaknya',
    penjelasan: 'Menarik kesimpulan atau tebakan kuat berdasarkan tanda-tanda yang terlihat di sekitar.',
    contoh1: 'どうやら彼が優勝しそうだ。\n(Sepertinya dialah yang akan jadi juaranya.)',
    contoh2: 'どうやら間に合った。\n(Syukurlah akhirnya sempat juga datang tepat waktu.)'
  }
];

window.vocabData.push(...kosakata_m3h6);