// Gunakan window.vocabData array agar file JS lain bisa di-push juga nantinya
window.vocabData = window.vocabData || [];

const kosakata_m3h6 = [
  {
    id: 'm3h6_1',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'あいにく',
    furigana: 'あいにく',
    arti: 'Sayangnya / Kebetulan yang buruk',
    penjelasan: 'Digunakan ketika ada situasi yang tidak menguntungkan atau waktu yang tidak tepat yang membuat suatu harapan atau rencana tidak dapat terwujud. Sering digunakan saat harus menolak atau meminta maaf dengan sopan.',
    contoh1: 'あいにく留守にしています。\n(Sayangnya/kebetulan sekali dia sedang tidak ada di rumah.)',
    contoh2: 'その日はあいにく予定が入っております。\n(Sayang sekali, pada hari itu saya sudah ada janji lain.)'
  },
  {
    id: 'm3h6_2',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '案の定',
    furigana: 'あんのじょう',
    arti: 'Sesuai dugaan / Seperti yang diperkirakan',
    penjelasan: 'Menggambarkan situasi di mana hal yang terjadi benar-benar persis sesuai dengan tebakan atau firasat sebelumnya. Sering kali digunakan untuk merujuk pada hasil yang negatif atau kurang baik, walau kadang bisa digunakan untuk hal netral.',
    contoh1: 'ダメだと思っていたら、案の定不合格だった。\n(Sudah mengira akan gagal, dan sesuai dugaan ternyata benar-benar tidak lulus.)',
    contoh2: '空が暗くなり、案の定雨が降ってきた。\n(Langit mendung, dan sesuai perkiraan hujan pun turun.)'
  },
  {
    id: 'm3h6_3',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '敢えて',
    furigana: 'あえて',
    arti: 'Sengaja / Memberanikan diri',
    penjelasan: 'Menunjukkan tindakan melakukan sesuatu secara sengaja meskipun tahu bahwa hal tersebut berisiko, menantang, menyulitkan diri sendiri, atau sebenarnya tidak harus dilakukan demi mencapai suatu tujuan atau kebaikan.',
    contoh1: '負けるとわかっているが、敢えて挑戦した。\n(Meskipun tahu kemungkinan akan kalah, saya memberanikan diri / sengaja untuk mencoba.)',
    contoh2: 'みんなのために、敢えて厳しいことを言う。\n(Demi kebaikan semuanya, saya sengaja melontarkan kritikan yang keras.)'
  },
  {
    id: 'm3h6_4',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '強いて',
    furigana: 'しいて',
    arti: 'Jika dipaksa / Kalau terpaksa',
    penjelasan: 'Digunakan dalam situasi di mana seseorang didesak, dipaksa untuk melakukan, atau memilih sesuatu yang sebenarnya enggan, sulit untuk diputuskan, atau tidak terlalu menonjol perbedaannya.',
    contoh1: '強いてそれを変更しろとは言わない。\n(Saya tidak akan bersikeras / memaksa untuk menyuruhmu mengubah hal tersebut.)',
    contoh2: '強いて言えば、こっちのほうがましだ。\n(Kalau terpaksa harus memilih, yang ini rasanya sedikit lebih baik.)'
  },
  {
    id: 'm3h6_5',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '自ずから / 自ずと',
    furigana: 'おのずから / おのずと',
    arti: 'Dengan sendirinya / Secara alami',
    penjelasan: 'Menandakan bahwa suatu hal terjadi atau terselesaikan secara alami dengan sendirinya seiring berjalannya waktu, usaha, atau sebagai hasil dari suatu proses, tanpa campur tangan yang dipaksakan.',
    contoh1: '努力すれば自ずから道は開ける。\n(Jika terus berusaha, jalan kesuksesan akan terbuka dengan sendirinya.)',
    contoh2: '大人になれば自ずとわかるよ。\n(Kalau sudah dewasa nanti, kamu akan mengerti secara alami dengan sendirinya.)'
  },
  {
    id: 'm3h6_6',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '自ら',
    furigana: 'みずから',
    arti: 'Sendiri / Atas inisiatif sendiri',
    penjelasan: 'Menunjukkan sebuah tindakan yang dilakukan secara langsung oleh diri sendiri, atas inisiatif, kesadaran, atau kehendak pribadi tanpa disuruh, dipaksa, atau melibatkan orang lain.',
    contoh1: '自ら進んで勉強する。\n(Maju belajar dengan inisiatif sendiri / secara proaktif.)',
    contoh2: '社長が自ら現場を視察する。\n(Presiden direktur turun langsung meninjau lapangan secara pribadi.)'
  },
  {
    id: 'm3h6_7',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'とかく',
    furigana: 'とかく',
    arti: 'Cenderung / Sering kali',
    penjelasan: 'Menunjukkan adanya kecenderungan yang kuat bahwa suatu hal atau kejadian tertentu sering terjadi atau mudah terpengaruh ke arah tertentu. Biasanya digunakan untuk mendeskripsikan kebiasaan yang bernuansa sedikit negatif.',
    contoh1: '寒くなると、とかく遅刻者が多くなる。\n(Saat cuaca menjadi dingin, cenderung menjadi lebih banyak orang yang datang terlambat.)',
    contoh2: '人はとかく他人の欠点に気づきやすい。\n(Manusia sering kali / cenderung lebih mudah menyadari kekurangan orang lain.)'
  },
  {
    id: 'm3h6_8',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'なるたけ',
    furigana: 'なるたけ',
    arti: 'Sebisa mungkin / Sedapat mungkin',
    penjelasan: 'Kata ini adalah variasi percakapan yang bermakna persis sama dengan kata "なるべく" (narubeku). Artinya yaitu mengusahakan suatu tindakan ke batas yang paling maksimal sesuai kemampuan.',
    contoh1: 'なるたけ早く来てください。\n(Tolong datang secepat yang kamu bisa / sebisa mungkin lebih awal.)',
    contoh2: 'なるたけお金を使わないようにしている。\n(Saya berusaha sebisa mungkin untuk tidak menghamburkan uang.)'
  },
  {
    id: 'm3h6_9',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '努めて',
    furigana: 'つとめて',
    arti: 'Berusaha keras (untuk bersikap) / Sebisa mungkin',
    penjelasan: 'Menggambarkan suatu tindakan di mana seseorang secara sadar dan sengaja berusaha sekuat tenaga untuk mengendalikan diri, menahan perasaan yang bergejolak, atau memaksakan suatu sikap tertentu agar terlihat wajar.',
    contoh1: '努めて（＝できるだけ）冷静にする。\n(Berusaha keras / sebisa mungkin untuk tetap menjaga ketenangan diri.)',
    contoh2: '悲しかったが、努めて明るく振る舞った。\n(Meskipun sedih, saya berusaha sekuat tenaga untuk bertingkah laku ceria.)'
  },
  {
    id: 'm3h6_10',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'ひいては',
    furigana: 'ひいては',
    arti: 'Yang pada gilirannya / Berimbas pada',
    penjelasan: 'Kata sambung yang dipakai untuk menunjukkan bahwa efek, manfaat, atau dampak dari suatu tindakan tidak hanya berhenti di satu titik kecil itu saja, melainkan terus meluas dan berimbas pada hal lain dengan skala yang lebih besar.',
    contoh1: '自分のため、ひいては家族全体のために頑張ろう。\n(Mari kita berjuang untuk diri sendiri, yang pada gilirannya hal itu akan bermanfaat untuk seluruh keluarga kita.)',
    contoh2: 'この研究は、ひいては人類の未来を救うだろう。\n(Penelitian ini, pada akhirnya akan berimbas pada penyelamatan masa depan umat manusia.)'
  },
  {
    id: 'm3h6_11',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'もはや～ない',
    furigana: 'もはや～ない',
    arti: 'Sudah tidak (lagi)',
    penjelasan: 'Digunakan untuk menegaskan dengan nada pasrah bahwa suatu keadaan, kesempatan, atau harapan sudah sepenuhnya tertutup secara mutlak di masa sekarang, dan tidak ada lagi ruang untuk mengubahnya.',
    contoh1: 'もはや（＝もう）彼の回復は望めない。\n(Saat ini sudah tidak ada harapan lagi untuk kesembuhannya.)',
    contoh2: 'もはや後戻りすることはできない。\n(Keadaannya sudah tidak memungkinkan lagi bagi kita untuk mundur/berbalik arah.)'
  },
  {
    id: 'm3h6_12',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'かえって',
    furigana: 'かえって',
    arti: 'Malah / Sebaliknya',
    penjelasan: 'Kata ini menunjukkan situasi yang ironis; di mana sebuah tindakan yang pada awalnya dilakukan untuk mendapatkan hasil yang lebih baik, justru memberikan hasil akhir yang berkebalikan atau malah memperburuk keadaan.',
    contoh1: '近道したら、かえって時間がかかった。\n(Sengaja lewat jalan pintas, tapi nyatanya malah memakan lebih banyak waktu.)',
    contoh2: '薬を飲んだら、かえって気分が悪くなった。\n(Setelah minum obat, perasaan/kondisi tubuhku malah menjadi semakin buruk.)'
  },
  {
    id: 'm3h6_13',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '取りあえず',
    furigana: 'とりあえず',
    arti: 'Untuk sementara / Terlebih dahulu / Pokoknya',
    penjelasan: 'Digunakan saat penutur ingin mengambil keputusan atau tindakan awal yang dirasa paling logis, mendesak, atau mudah untuk saat ini, sebelum memikirkan masalah atau langkah selanjutnya yang lebih rumit secara detail.',
    contoh1: '取りあえず何か食べよう。\n(Untuk sementara / dari pada tidak ngapa-ngapain, ayo kita makan sesuatu dulu.)',
    contoh2: '取りあえず問題はないだろう。\n(Untuk saat ini setidaknya, sepertinya tidak akan ada masalah.)'
  },
  {
    id: 'm3h6_14',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'かろうじて',
    furigana: 'かろうじて',
    arti: 'Dengan susah payah / Hampir tidak / Nyaris',
    penjelasan: 'Menggambarkan situasi kritis di mana seseorang nyaris saja gagal atau terlambat, namun pada akhirnya berhasil mencapai tujuan atau melewati batas dengan batas waktu atau kondisi yang sangat tipis (pas-pasan).',
    contoh1: 'かろうじて最終電車に間に合った。\n(Dengan susah payah dan nyaris saja telat, akhirnya saya sempat mengejar kereta terakhir.)',
    contoh2: 'かろうじて試験に合格した。\n(Berhasil lulus dalam ujian dengan nilai yang pas-pasan / nyaris tidak lulus.)'
  },
  {
    id: 'm3h6_15',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'ことごとく',
    furigana: 'ことごとく',
    arti: 'Semuanya / Sama sekali / Tanpa sisa',
    penjelasan: 'Digunakan untuk memberi penekanan emosional bahwa suatu hal terjadi pada keseluruhan aspek atau percobaan tanpa terkecuali satu pun. Biasanya sering dikaitkan dengan kegagalan, penolakan, atau hal yang meleset dari harapan.',
    contoh1: '私の案はことごとく却下された。\n(Ide-ide yang saya ajukan semuanya / tanpa sisa ditolak begitu saja.)',
    contoh2: '予想がことごとく外れた。\n(Tebakan saya meleset sama sekali untuk seluruh bagian.)'
  },
  {
    id: 'm3h6_16',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'ふんだんに',
    furigana: 'ふんだんに',
    arti: 'Secara melimpah / Sangat banyak',
    penjelasan: 'Menunjukkan ketersediaan, keberadaan, atau penggunaan sesuatu dalam jumlah yang sangat berlimpah ruah, mewah, tidak dibatasi, dan tidak pelit. Paling lazim digunakan untuk mendeskripsikan bahan makanan atau kucuran dana.',
    contoh1: 'イチゴをふんだんに使ったケーキ\n(Kue yang menggunakan buah stroberi secara melimpah ruah dan mewah.)',
    contoh2: '自然をふんだんに取り入れた家。\n(Rumah yang dibangun dengan memasukkan elemen alam secara maksimal dan melimpah.)'
  },
  {
    id: 'm3h6_17',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '幸い（に）',
    furigana: 'さいわい（に）',
    arti: 'Untungnya / Syukurlah / Berharap',
    penjelasan: 'Mengekspresikan rasa kelegaan yang amat sangat karena beruntung bisa terhindar dari nasib yang lebih buruk. Dalam urusan surat-menyurat resmi atau bisnis, kata ini dipakai secara halus untuk memohon agar permintaan dipenuhi ("akan sangat bersyukur jika...").',
    contoh1: '事故にあったが、幸いけがはなかった。\n(Memang benar saya mengalami kecelakaan, namun syukurlah/untungnya tidak ada yang terluka.)',
    contoh2: 'お返事をいただければ幸いです。\n(Saya akan merasa sangat bersyukur / beruntung jika Anda sudi memberikan balasan surat ini.)'
  },
  {
    id: 'm3h6_18',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '現に',
    furigana: 'げんに',
    arti: 'Kenyataannya / Pada kenyataannya',
    penjelasan: 'Digunakan untuk membantah keraguan atau meyakinkan pendengar dengan cara memberikan contoh atau menunjuk secara langsung pada fakta, bukti aktual, dan insiden yang nyata-nyata ada di depan mata.',
    contoh1: '現に（＝実際に）、私はそれを見た。\n(Pada kenyataannya / secara aktualnya, saya melihatnya dengan mata kepala saya sendiri.)',
    contoh2: '誰も信じないが、現にその事件は起きたのだ。\n(Mungkin tidak ada seorang pun yang percaya, tapi nyatanya insiden tersebut memang terjadi.)'
  },
  {
    id: 'm3h6_19',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'いずれも / いずれにしても / いずれにせよ',
    furigana: 'いずれも / いずれにしても / いずれにせよ',
    arti: 'Bagaimanapun juga / Apapun itu / Cepat atau lambat',
    penjelasan: 'Frasa yang digunakan untuk menyimpulkan sesuatu. Artinya, terlepas dari beberapa pilihan atau skenario yang ada, hasil akhirnya akan tetap sama. "Izure" secara tunggal juga bisa berarti "suatu saat nanti / kelak".',
    contoh1: 'いずれにしても、高くて買えない。\n(Bagaimanapun juga situasinya, harganya terlalu mahal dan saya tidak akan mampu membelinya.)',
    contoh2: 'いずれ（＝そのうち）また来ます。\n(Cepat atau lambat / suatu saat nanti saya pasti akan datang berkunjung lagi.)'
  },
  {
    id: 'm3h6_20',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: '仮に',
    furigana: 'かりに',
    arti: 'Seandainya / Misalkan / Umpamanya',
    penjelasan: 'Digunakan di awal kalimat untuk melontarkan sebuah pengandaian hipotesis tentang situasi yang belum tentu nyata atau belum terjadi sama sekali, untuk memikirkan tanggapan atau kesimpulan logis darinya.',
    contoh1: '仮に試験に落ちたら、どうしますか。\n(Seandainya kamu gagal dalam ujian nanti, apa yang rencananya akan kamu lakukan?)',
    contoh2: '仮にそれが事実だとしても、私は諦めない。\n(Kalaupun seandainya hal itu merupakan fakta yang benar, saya tetap tidak akan menyerah.)'
  },
  {
    id: 'm3h6_21',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'ひょっとすると / ひょっとして',
    furigana: 'ひょっとすると / ひょっとして',
    arti: 'Mungkin saja / Jangan-jangan',
    penjelasan: 'Kosa kata ini dipakai ketika penutur tiba-tiba menyadari suatu kemungkinan yang janggal, mengejutkan, atau tidak disangka-sangka. Kerap kali digabungkan dengan kata akhir "かもしれない" (mungkin).',
    contoh1: 'ひょっとすると彼の話はうそかもしれない。\n(Jangan-jangan / mungkin saja cerita dari orang itu sebenarnya adalah kebohongan belaka.)',
    contoh2: 'ひょっとして、あの人は山田さんですか。\n(Jangan-jangan, sosok orang yang di sana itu adalah Pak Yamada?)'
  },
  {
    id: 'm3h6_22',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'もしかして / もしかすると',
    furigana: 'もしかして / もしかすると',
    arti: 'Mungkinkah / Jangan-jangan',
    penjelasan: 'Sangat identik dan bisa ditukar pakai dengan "hyottoshite". Ini digunakan untuk mengungkapkan tebakan, intuisi, atau sedikit kecurigaan akan kebenaran suatu hal, yang ditanyakan langsung untuk meminta konfirmasi.',
    contoh1: 'もしかして、あなたは、田中さん？\n(Mungkinkah, sebenarnya Anda ini adalah Pak Tanaka?)',
    contoh2: 'もしかすると、明日は雪が降るかもしれない。\n(Mungkin saja, besok salju akan turun dari langit.)'
  },
  {
    id: 'm3h6_23',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'どうにか',
    furigana: 'どうにか',
    arti: 'Entah bagaimana / Bagaimanapun caranya',
    penjelasan: 'Kata ini memiliki dua nuansa: pertama, tekad kuat untuk mengusahakan dan menyelesaikan masalah "bagaimanapun juga caranya" walau sulit. Kedua, perasaan lega karena suatu tugas berhasil dilalui atau terselesaikan "dengan susah payah / entah bagaimana caranya".',
    contoh1: 'どうにかあの会社に就職したい。\n(Bagaimanapun caranya, saya bertekad ingin bisa bekerja di perusahaan tersebut.)',
    contoh2: 'どうにか大学は卒業した。\n(Dengan susah payah / entah bagaimana caranya, pada akhirnya saya lulus universitas juga.)'
  },
  {
    id: 'm3h6_24',
    minggu: '3',
    hari: '6',
    kategori: 'kata keterangan',
    kanji: 'どうやら',
    furigana: 'どうやら',
    arti: 'Sepertinya / Agaknya / Entah bagaimana akhirnya',
    penjelasan: 'Mirip dengan dounika, tapi juga sering digunakan untuk menarik suatu kesimpulan, tebakan, atau taksiran yang kuat berdasarkan tanda-tanda atau situasi sekeliling yang terlihat (bersinonim dengan おそらく).',
    contoh1: 'どうやら（＝おそらく）彼が優勝しそうだ。\n(Melihat gelagatnya, agaknya/sepertinya memang dialah yang akan keluar sebagai sang juara.)',
    contoh2: 'どうやら（＝どうにか）間に合った。\n(Akhirnya / entah bagaimana sempat juga datang tepat pada waktunya.)'
  }
];

window.vocabData.push(...kosakata_m3h6);